<a href="https://colab.research.google.com/github/LulutheBA/ANLOK-WATER-PREDICTION-PROJECT-/blob/main/Copy_of_notebook_1%262.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Install Required Packages
Install any needed Python packages.

In [ ]:
!pip install pandas numpy matplotlib plotly scikit-learn xgboost shap >/dev/null

Mount Google Drive
Mount the user’s Google Drive to access files.

In [ ]:
from google.colab import drive
drive.mount('/content/drive') # will prompt for authentication【1†L1012-L1015】

Mounted at /content/drive

GitHub Authentication
Securely enter a GitHub token to clone the private repository.

In [ ]:

from getpass import getpass
# Prompt for a GitHub personal access token (do NOT share your token publicly)
token = getpass("Enter your GitHub Personal Access Token: ")
# Define Git repo URL (replace <username> and <repo> with actual values)
github_user = "LulutheBA" # <-- placeholder
github_repo = "ANLOK-WATER-PREDICTION-PROJECT-" # <-- placeholder (repo name)
!rm -rf $github_repo # remove any existing folder
!git clone https://{token}@github.com/{github_user}/{github_repo}.git

Enter your GitHub Personal Access Token: ··········
Cloning into 'ANLOK-WATER-PREDICTION-PROJECT-'...
remote: Enumerating objects: 382, done.
remote: Counting objects: 100% (80/80), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 382 (delta 23), reused 2 (delta 2), pack-reused 302 (from 2)
Receiving objects: 100% (382/382), 764.07 KiB | 2.51 MiB/s, done.
Resolving deltas: 100% (171/171), done.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

5: Verify Repository Files
List the cloned repository contents to confirm cloning.

In [ ]:

import os
repo_path = f"/content/{github_repo}"
print("Repository structure:")
!ls "$repo_path"

Repository structure:
Data  notebook_1.ipynb	Notebooks  Outputs  Training

Import Libraries
Import all necessary Python libraries.

In [ ]:
# Data manipulation
import pandas as pd
import numpy as np
# Visualization
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
# Statistics
from scipy.stats import zscore
# Utilities
import glob
import os
import warnings
warnings.filterwarnings("ignore")
plt.rcParams["figure.figsize"] = (10, 6)

7: Locate All CSV Files
Automatically find all .csv files in the repository.

In [ ]:
# Use glob to recursively find CSV files (pandas, glob can locate files)
csv_files = glob.glob(os.path.join(repo_path, "**/*.csv"), recursive=True)
print(f"Found {len(csv_files)} CSV files.")
for file in csv_files:
    print(file)

Found 28 CSV files.
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Verified - River Flow ( National ).csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/NIWIS_WasteWaterQuality_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Potable Systems_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Surface Water Storage (2014-2020).csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Weather4355517.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/TimeSeries Population_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Vulnerability Score Per leg_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Operational_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Piped Water Households _ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/NIWIS_Water Supply Reliability - population_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Weather.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Timeseries Households_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/NIWIS_RWT_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Protests Identified by Municipal IQ_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/People Served with Water_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Areas of Highest Vulnerability_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Water demand growth_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Total Population_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/NIWIS_GroundwaterStatus_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Residential Tariffs_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Households Served with Water_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30].csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Institutional Compliance_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Surface Water Storage ( 2020 -2026).csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Total Households_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Microbiological _ Acute Health_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Source of Water Households _ 2026_04_21.csv

8: Load Datasets into Dictionary
Load each CSV into a pandas DataFrame stored in a dictionary.

In [ ]:
datasets = {}
for file in csv_files:
    name = os.path.splitext(os.path.basename(file))[0]
    try:
        datasets[name] = pd.read_csv(file)
    except Exception as e:
        print(f"Skipping {name}: {e}")
        continue
print("Datasets loaded:", list(datasets.keys()))

Skipping Weather4355517: No columns to parse from file
Datasets loaded: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21', 'Water demand growth_ 2026_04_21', 'Total Population_ 2026_04_21', 'NIWIS_GroundwaterStatus_16-Jul-2026 ', 'Residential Tariffs_ 2026_04_21', 'Households Served with Water_ 2026_04_21', 'Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]', 'Institutional Compliance_ 2026_04_21', 'Surface Water Storage ( 2020 -2026)', 'Total Households_ 2026_04_21', 'Microbiological _ Acute Health_ 2026_04_21', 'Source of Water Households _ 2026_04_21']

9: Create Inventory Table
Compute inventory (rows, columns, missing, duplicates, etc.) and display as DataFrame.

In [ ]:
inventory = []
for name, df in datasets.items():
    inventory.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Memory(MB)": round(df.memory_usage().sum() / 1024**2, 2),
        "Missing Values": df.isnull().sum().sum(),
        "Duplicate Rows": df.duplicated().sum(),
        "Numeric Columns": len(df.select_dtypes(include=np.number).columns),
        "Categorical Columns": len(df.select_dtypes(exclude=np.number).columns)
    })
inventory_df = pd.DataFrame(inventory)
display(inventory_df)

,Dataset,Rows,Columns,Memory(MB),Missing Values,Duplicate Rows,Numeric Columns,Categorical Columns
0,Verified - River Flow ( National ),7,2,0.00,0,0,1,1
1,NIWIS_WasteWaterQuality_16-Jul-2026,143,6,0.01,143,0,1,5
2,Potable Systems_ 2026_04_21,61,11,0.01,69,0,2,9
3,Surface Water Storage (2014-2020),374,9,0.03,1971,0,8,1
4,TimeSeries Population_ 2026_04_21,11,35,0.00,43,0,0,35
5,Vulnerability Score Per leg_ 2026_04_21,11,9,0.00,17,0,6,3
6,Operational_ 2026_04_21,11,8,0.00,16,0,2,6
7,Piped Water Households _ 2026_04_21,10,12,0.00,19,0,2,10
8,NIWIS_Water Supply Reliability - population_16...,144,14,0.02,189,0,1,13
9,Weather,21301,14,2.28,38846,0,7,7
10,Timeseries Households_ 2026_04_21,11,35,0.00,43,0,0,35
11,NIWIS_RWT_16-Jul-2026,9,5,0.00,0,0,4,1
12,Protests Identified by Municipal IQ_ 2026_04_21,11,16,0.00,24,0,13,3
13,People Served with Water_ 2026_04_21,11,17,0.00,25,0,1,16
14,NIWIS_Access to Water Infrastructure Delivered...,0,4,0.00,0,0,0,4
15,Areas of Highest Vulnerability_ 2026_04_21,11,21,0.00,29,0,0,21
16,Water demand growth_ 2026_04_21,11,10,0.00,18,0,3,7
17,Total Population_ 2026_04_21,11,8,0.00,16,0,1,7
18,NIWIS_GroundwaterStatus_16-Jul-2026,1947,8,0.12,2511,1,1,7
19,Residential Tariffs_ 2026_04_21,11,7,0.00,15,0,0,7
20,Households Served with Water_ 2026_04_21,11,17,0.00,25,0,2,15
21,Drinking Water Quality Compliance - SANS 241 _...,4,2,0.00,0,0,1,1
22,Institutional Compliance_ 2026_04_21,11,5,0.00,13,0,2,3
23,Surface Water Storage ( 2020 -2026),375,9,0.03,1953,0,8,1
24,Total Households_ 2026_04_21,11,8,0.00,16,0,1,7
25,Microbiological _ Acute Health_ 2026_04_21,11,8,0.00,16,0,2,6
26,Source of Water Households _ 2026_04_21,10,13,0.00,20,0,1,12

10: Save Inventory Table
Save the inventory table to CSV for record.

In [ ]:
outputs_dir = "Outputs"
os.makedirs(outputs_dir, exist_ok=True)
inventory_df.to_csv(os.path.join(outputs_dir, "dataset_inventory.csv"),
index=False)
print("Inventory saved to Outputs/dataset_inventory.csv")

Inventory saved to Outputs/dataset_inventory.csv

11: Preview One Dataset
Example: show first rows of one dataset to verify loading.

In [ ]:
# Replace with a valid dataset key if needed; here we try the first one
sample_key = list(datasets.keys())[0]
print(f"Sample dataset ({sample_key}):")
display(datasets[sample_key].head())

Sample dataset (Verified - River Flow ( National )):

              'Flow  'Flow Level :
0             'High            243
1  'Moderately High             54
2           'Normal             66
3   'Moderately Low             36
4              'Low             46

In [ ]:
# ============================================
# CELL 1: IMPORT LIBRARIES
# ============================================

import pandas as pd
import numpy as np
import os
import re
import glob
import warnings

from IPython.display import display

warnings.filterwarnings("ignore")

print("Libraries imported successfully.")

Libraries imported successfully.

In [ ]:
# ============================================
# CELL 2: CONFIRM DATASETS
# ============================================

print("=" * 80)
print("DATASETS LOADED")
print("=" * 80)

print(f"Total number of datasets: {len(datasets)}")
print()

for i, name in enumerate(datasets.keys(), start=1):
    print(f"{i}. {name}")

================================================================================
DATASETS LOADED
================================================================================
Total number of datasets: 27

1. Verified - River Flow ( National )
2. NIWIS_WasteWaterQuality_16-Jul-2026
3. Potable Systems_ 2026_04_21
4. Surface Water Storage (2014-2020)
5. TimeSeries Population_ 2026_04_21
6. Vulnerability Score Per leg_ 2026_04_21
7. Operational_ 2026_04_21
8. Piped Water Households _ 2026_04_21
9. NIWIS_Water Supply Reliability - population_16-Jul-2026
10. Weather
11. Timeseries Households_ 2026_04_21
12. NIWIS_RWT_16-Jul-2026
13. Protests Identified by Municipal IQ_ 2026_04_21
14. People Served with Water_ 2026_04_21
15. NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026
16. Areas of Highest Vulnerability_ 2026_04_21
17. Water demand growth_ 2026_04_21
18. Total Population_ 2026_04_21
19. NIWIS_GroundwaterStatus_16-Jul-2026
20. Residential Tariffs_ 2026_04_21
21. Households Served with Water_ 2026_04_21
22. Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]
23. Institutional Compliance_ 2026_04_21
24. Surface Water Storage ( 2020 -2026)
25. Total Households_ 2026_04_21
26. Microbiological _ Acute Health_ 2026_04_21
27. Source of Water Households _ 2026_04_21

In [ ]:
# ============================================
# CELL 3: COMPLETE DATASET OVERVIEW
# ============================================

overview = []

for name, df in datasets.items():

    overview.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": int(df.isnull().sum().sum()),
        "Duplicate Rows": int(df.duplicated().sum()),
        "Numeric Columns": len(
            df.select_dtypes(include=np.number).columns
        ),
        "Categorical Columns": len(
            df.select_dtypes(include="object").columns
        ),
        "Memory (MB)": round(
            df.memory_usage(deep=True).sum() / 1024**2,
            2
        )
    })

overview_df = pd.DataFrame(overview)

display(overview_df)

,Dataset,Rows,Columns,Missing Values,Duplicate Rows,Numeric Columns,Categorical Columns,Memory (MB)
0,Verified - River Flow ( National ),7,2,0,0,1,1,0.00
1,NIWIS_WasteWaterQuality_16-Jul-2026,143,6,143,0,1,5,0.04
2,Potable Systems_ 2026_04_21,61,11,69,0,2,9,0.04
3,Surface Water Storage (2014-2020),374,9,1971,0,8,1,0.05
4,TimeSeries Population_ 2026_04_21,11,35,43,0,0,35,0.03
5,Vulnerability Score Per leg_ 2026_04_21,11,9,17,0,6,3,0.00
6,Operational_ 2026_04_21,11,8,16,0,2,6,0.00
7,Piped Water Households _ 2026_04_21,10,12,19,0,2,10,0.01
8,NIWIS_Water Supply Reliability - population_16...,144,14,189,0,1,13,0.10
9,Weather,21301,14,38846,0,7,7,8.86
10,Timeseries Households_ 2026_04_21,11,35,43,0,0,35,0.03
11,NIWIS_RWT_16-Jul-2026,9,5,0,0,4,1,0.00
12,Protests Identified by Municipal IQ_ 2026_04_21,11,16,24,0,13,3,0.00
13,People Served with Water_ 2026_04_21,11,17,25,0,1,16,0.01
14,NIWIS_Access to Water Infrastructure Delivered...,0,4,0,0,0,4,0.00
15,Areas of Highest Vulnerability_ 2026_04_21,11,21,29,0,0,21,0.01
16,Water demand growth_ 2026_04_21,11,10,18,0,3,7,0.01
17,Total Population_ 2026_04_21,11,8,16,0,1,7,0.01
18,NIWIS_GroundwaterStatus_16-Jul-2026,1947,8,2511,1,1,7,0.69
19,Residential Tariffs_ 2026_04_21,11,7,15,0,0,7,0.00
20,Households Served with Water_ 2026_04_21,11,17,25,0,2,15,0.01
21,Drinking Water Quality Compliance - SANS 241 _...,4,2,0,0,1,1,0.00
22,Institutional Compliance_ 2026_04_21,11,5,13,0,2,3,0.01
23,Surface Water Storage ( 2020 -2026),375,9,1953,0,8,1,0.05
24,Total Households_ 2026_04_21,11,8,16,0,1,7,0.01
25,Microbiological _ Acute Health_ 2026_04_21,11,8,16,0,2,6,0.00
26,Source of Water Households _ 2026_04_21,10,13,20,0,1,12,0.01

In [ ]:
# ============================================
# CELL 4: INSPECT EVERY DATASET
# ============================================

for name, df in datasets.items():

    print("\n")
    print("=" * 100)
    print(f"DATASET: {name}")
    print("=" * 100)

    print(f"Rows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")

    print("\nColumn names:")
    print(list(df.columns))

    print("\nData types:")
    print(df.dtypes)

    print("\nMissing values:")
    missing = df.isnull().sum()
    missing = missing[missing > 0]

    if len(missing) == 0:
        print("No missing values.")
    else:
        print(missing)

    print("\nDuplicate rows:")
    print(df.duplicated().sum())

    print("\nFirst 5 rows:")
    display(df.head())

    print("\nNumerical summary:")
    display(df.describe(include="all").T)

====================================================================================================
DATASET: Verified - River Flow ( National )
====================================================================================================
Rows: 7
Columns: 2

Column names:
["'Flow", "'Flow Level :"]

Data types:
'Flow            object
'Flow Level :     int64
dtype: object

Missing values:
No missing values.

Duplicate rows:
0

First 5 rows:

              'Flow  'Flow Level :
0             'High            243
1  'Moderately High             54
2           'Normal             66
3   'Moderately Low             36
4              'Low             46

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
'Flow,7,7,'High,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Flow Level :,7.0,NaN,NaN,NaN,76.857143,74.44557,30.0,41.0,54.0,64.5,243.0

====================================================================================================
DATASET: NIWIS_WasteWaterQuality_16-Jul-2026
====================================================================================================
Rows: 143
Columns: 6

Column names:
['Unnamed: 0', 'WSA', 'Chemical', 'Microbiological', 'Physical', 'Monitoring']

Data types:
Unnamed: 0         float64
WSA                 object
Chemical            object
Microbiological     object
Physical            object
Monitoring          object
dtype: object

Missing values:
Unnamed: 0    143
dtype: int64

Duplicate rows:
0

First 5 rows:

,Unnamed: 0,WSA,Chemical,Microbiological,Physical,Monitoring
0,NaN,Buffalo City,74%,29%,82%,75%
1,NaN,City of Cape Town,68%,65%,74%,92%
2,NaN,Ekurhuleni,76%,78%,88%,84%
3,NaN,eThekwini,68%,60%,83%,93%
4,NaN,City of Johannesburg,73%,68%,85%,92%

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Unnamed: 0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WSA,143,143,Buffalo City,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Chemical,143,62,0%,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Microbiological,143,69,0%,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Physical,143,51,79%,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Monitoring,143,59,89%,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN

====================================================================================================
DATASET: Potable Systems_ 2026_04_21
====================================================================================================
Rows: 61
Columns: 11

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'System name', 'System area', 'Population in system', 'Households in System', 'Households with Access to RDP Water', 'Households with Access to Reliable Water', 'Drinking Water Quality Percentage', 'Latest Blue Drop Score']

Data types:
Region                                       object
Time Frame                                   object
Unnamed: 2                                   object
System name                                  object
System area                                  object
Population in system                         object
Households in System                         object
Households with Access to RDP Water          object
Households with Access to Reliable Water     object
Drinking Water Quality Percentage           float64
Latest Blue Drop Score                      float64
dtype: object

Missing values:
Time Frame                                   1
Unnamed: 2                                  60
System name                                  1
System area                                  1
Population in system                         1
Households in System                         1
Households with Access to RDP Water          1
Households with Access to Reliable Water     1
Drinking Water Quality Percentage            1
Latest Blue Drop Score                       1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,System name,System area,Population in system,Households in System,Households with Access to RDP Water,Households with Access to Reliable Water,Drinking Water Quality Percentage,Latest Blue Drop Score
0,City of Johannesburg Metropolitan Municipality,April 2022,NaN,Greater Johannesburg Water Supply System,"Alexandra,East Bank ,Tsutsumani ,Bultfontein ,...",4 434 827,1 733 856,1 733 856,1 404 854,99.67,98.10
1,City of Tshwane Metropolitan Municipality,April 2022,NaN,PRETORIA Central & South (Rietvlei WTW & Rand ...,"Rietvalleipark, Rietvalleirand, Elarduspark, W...",1 523 194,551 867,534 627,455 074,99.92,89.36
2,City of Tshwane Metropolitan Municipality,April 2022,NaN,PRETORIA Findley (Fountains),Central Business District,6 322,2 291,2 219,1 889,99.48,64.44
3,City of Tshwane Metropolitan Municipality,April 2022,NaN,PRETORIA Temba (Temba WTW; Klipdrift WTW),"Stinkwater,Kudube,Hammanskraal ,Temba, Skampan...",400 875,145 241,140 703,119 767,99.66,55.97
4,City of Tshwane Metropolitan Municipality,April 2022,NaN,PRETORIA North - (Roodeplaat WTW),"Montana, Montana Tuine, Pumulani AH, Wolmarans...",413 860,149 945,145 261,123 646,100.00,63.56

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,61,11,Gauteng,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,60,1,April 2022,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,<b>Data Source:</b> DWS Water Services and Reg...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
System name,60,30,Greater Johannesburg Water Supply System,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
System area,60,30,"Alexandra,East Bank ,Tsutsumani ,Bultfontein ,...",2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population in system,60,26,22 750,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households in System,60,29,8 243,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households with Access to RDP Water,60,29,7 985,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households with Access to Reliable Water,60,29,6 797,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Drinking Water Quality Percentage,60.0,NaN,NaN,NaN,90.268,26.286442,0.0,98.39,99.895,100.0,100.0
Latest Blue Drop Score,60.0,NaN,NaN,NaN,77.852667,17.270366,42.3,63.56,86.515,89.36,98.1

====================================================================================================
DATASET: Surface Water Storage (2014-2020)
====================================================================================================
Rows: 374
Columns: 9

Column names:
["'DateTime", "'High", "'Moderately High", "'Normal", "'Moderately Low", "'Low", "'Very Low", "'2018/2019", "'2019/2020"]

Data types:
'DateTime            object
'High               float64
'Moderately High    float64
'Normal             float64
'Moderately Low     float64
'Low                float64
'Very Low           float64
'2018/2019          float64
'2019/2020          float64
dtype: object

Missing values:
'High               302
'Moderately High    302
'Normal             302
'Moderately Low     302
'Low                302
'Very Low           302
'2018/2019           60
'2019/2020           99
dtype: int64

Duplicate rows:
0

First 5 rows:

,'DateTime,'High,'Moderately High,'Normal,'Moderately Low,'Low,'Very Low,'2018/2019,'2019/2020
0,'2014-10-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,76.958839,80.565839
1,'2014-10-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,76.068734,79.891470
2,'2014-10-15 00:00:00,90.99,86.4,82.04,78.74,71.9,61.906,74.552466,78.976701
3,'2014-10-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,73.780688,78.084224
4,'2014-10-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,73.613656,77.309324

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
'DateTime,374,374,'2020-09-30 00:00:00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'High,72.0,NaN,NaN,NaN,95.099167,2.235766,90.99,93.675,94.245,97.1075,98.7
'Moderately High,72.0,NaN,NaN,NaN,87.340729,2.041327,83.51,85.674375,87.03875,89.375,90.5925
'Normal,72.0,NaN,NaN,NaN,84.753583,2.72592,78.324,82.4315,85.807,86.792,88.998
'Moderately Low,72.0,NaN,NaN,NaN,79.158722,3.511085,70.724,76.936,79.695,81.746,85.01
'Low,72.0,NaN,NaN,NaN,71.164062,6.085211,59.88,66.695,72.3475,75.835625,81.0825
'Very Low,72.0,NaN,NaN,NaN,63.281028,4.106812,55.82,58.71125,64.2245,67.06825,69.599
'2018/2019,314.0,NaN,NaN,NaN,70.193007,10.908586,48.306678,62.517296,72.287366,78.90341,92.049189
'2019/2020,275.0,NaN,NaN,NaN,67.27277,9.7741,48.420322,59.438076,68.060977,74.855838,83.064876

====================================================================================================
DATASET: TimeSeries Population_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 35

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'April 1994', 'April 1995', 'April 1996', 'April 1997', 'April 1998', 'April 1999', 'April 2000', 'April 2001', 'April 2002', 'April 2004', 'April 2005', 'April 2006', 'April 2007', 'April 2008', 'April 2009', 'April 2010', 'April 2011', 'April 2012', 'April 2013', 'April 2014', 'April 2015', 'April 2016', 'April 2017', 'April 2018', 'April 2019', 'April 2020', 'April 2021', 'April 2022', 'April 2023', 'April 2024', 'April 2025', 'April 2026']

Data types:
Region        object
Time Frame    object
Unnamed: 2    object
April 1994    object
April 1995    object
April 1996    object
April 1997    object
April 1998    object
April 1999    object
April 2000    object
April 2001    object
April 2002    object
April 2004    object
April 2005    object
April 2006    object
April 2007    object
April 2008    object
April 2009    object
April 2010    object
April 2011    object
April 2012    object
April 2013    object
April 2014    object
April 2015    object
April 2016    object
April 2017    object
April 2018    object
April 2019    object
April 2020    object
April 2021    object
April 2022    object
April 2023    object
April 2024    object
April 2025    object
April 2026    object
dtype: object

Missing values:
Time Frame     1
Unnamed: 2    10
April 1994     1
April 1995     1
April 1996     1
April 1997     1
April 1998     1
April 1999     1
April 2000     1
April 2001     1
April 2002     1
April 2004     1
April 2005     1
April 2006     1
April 2007     1
April 2008     1
April 2009     1
April 2010     1
April 2011     1
April 2012     1
April 2013     1
April 2014     1
April 2015     1
April 2016     1
April 2017     1
April 2018     1
April 2019     1
April 2020     1
April 2021     1
April 2022     1
April 2023     1
April 2024     1
April 2025     1
April 2026     1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,April 1994,April 1995,April 1996,April 1997,April 1998,April 1999,April 2000,...,April 2017,April 2018,April 2019,April 2020,April 2021,April 2022,April 2023,April 2024,April 2025,April 2026
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,2 448 143,2 540 093,2 635 515,2 734 565,2 837 383,2 944 081,3 054 805,...,5 089 098,5 443 141,5 674 824,5 795 032,5 917 763,4 803 262,4 831 752,4 860 421,5 030 537,5 045 624
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,1 711 629,1 764 445,1 819 054,1 875 497,1 933 844,1 994 187,2 056 570,...,3 368 580,3 602 931,3 756 308,3 835 872,3 917 115,4 040 314,4 150 827,4 264 373,4 413 629,4 426 868
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,1 881 907,1 952 473,2 025 714,2 101 721,2 180 598,2 262 466,2 347 437,...,3 463 997,3 704 963,3 862 672,3 944 477,4 028 025,4 066 698,4 147 862,4 230 649,4 378 703,4 391 840
3,Emfuleni,April 2026,NaN,499 397,518 149,537 609,557 801,578 755,600 503,623 074,...,749 729,801 881,836 015,853 720,871 801,945 652,966 627,988 051,1 022 634,1 025 702
4,Lesedi,April 2026,NaN,54 264,56 298,58 412,60 607,62 884,65 244,67 695,...,115 739,123 790,129 059,131 794,134 585,132 783,135 952,139 201,144 071,144 504

Numerical summary:

,count,unique,top,freq
Region,11,11,City of Johannesburg Metropolitan Municipality,1
Time Frame,10,1,April 2026,10
Unnamed: 2,1,1,"<b>Data Source:</b> <a style=""font-weight: bol...",1
April 1994,10,10,2 448 143,1
April 1995,10,10,2 540 093,1
April 1996,10,10,2 635 515,1
April 1997,10,10,2 734 565,1
April 1998,10,10,2 837 383,1
April 1999,10,10,2 944 081,1
April 2000,10,10,3 054 805,1
April 2001,10,10,3 169 720,1
April 2002,10,10,3 319 296,1
April 2004,10,10,3 541 100,1
April 2005,10,10,3 683 235,1
April 2006,10,10,3 757 176,1
April 2007,10,10,3 779 716,1
April 2008,10,10,3 836 405,1
April 2009,10,10,3 859 421,1
April 2010,10,10,4 299 568,1
April 2011,10,10,4 434 852,1
April 2012,10,10,4 539 527,1
April 2013,10,10,4 646 670,1
April 2014,10,10,4 756 359,1
April 2015,10,10,4 868 627,1
April 2016,10,10,4 983 549,1
April 2017,10,10,5 089 098,1
April 2018,10,10,5 443 141,1
April 2019,10,10,5 674 824,1
April 2020,10,10,5 795 032,1
April 2021,10,10,5 917 763,1
April 2022,10,10,4 803 262,1
April 2023,10,10,4 831 752,1
April 2024,10,10,4 860 421,1
April 2025,10,10,5 030 537,1
April 2026,10,10,5 045 624,1

====================================================================================================
DATASET: Vulnerability Score Per leg_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 9

Column names:
['Region', 'Time Frame', 'Unnamed: 2', '1# Water Services Planning', '4# Technical Staff Capacity (Numbers)', '6# Water Conservation & Water Demand Management (WC/WDM)', '7# Drinking Water Safety & Regulatory Compliance', '10# Infrastructure Asset Management (IAM)', '11# Operation & Maintenance (O&M) of Assets']

Data types:
Region                                                       object
Time Frame                                                   object
Unnamed: 2                                                   object
1# Water Services Planning                                  float64
4# Technical Staff Capacity (Numbers)                       float64
6# Water Conservation & Water Demand Management (WC/WDM)    float64
7# Drinking Water Safety & Regulatory Compliance            float64
10# Infrastructure Asset Management (IAM)                   float64
11# Operation & Maintenance (O&M) of Assets                 float64
dtype: object

Missing values:
Time Frame                                                   1
Unnamed: 2                                                  10
1# Water Services Planning                                   1
4# Technical Staff Capacity (Numbers)                        1
6# Water Conservation & Water Demand Management (WC/WDM)     1
7# Drinking Water Safety & Regulatory Compliance             1
10# Infrastructure Asset Management (IAM)                    1
11# Operation & Maintenance (O&M) of Assets                  1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,1# Water Services Planning,4# Technical Staff Capacity (Numbers),6# Water Conservation & Water Demand Management (WC/WDM),7# Drinking Water Safety & Regulatory Compliance,10# Infrastructure Asset Management (IAM),11# Operation & Maintenance (O&M) of Assets
0,City of Johannesburg Metropolitan Municipality,2 018,NaN,93.0,79.0,80.0,98.0,99.0,65.0
1,City of Tshwane Metropolitan Municipality,2 018,NaN,90.0,20.0,80.0,80.0,60.0,40.0
2,Ekurhuleni Metropolitan Municipality,2 018,NaN,95.0,80.0,80.0,100.0,90.0,70.0
3,Emfuleni,2 018,NaN,40.0,15.0,55.0,65.0,54.0,30.0
4,Lesedi,2 018,NaN,65.0,69.0,80.0,74.0,55.0,35.0

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,11,11,City of Johannesburg Metropolitan Municipality,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,10,1,2 018,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,"<b>Data Source:</b> <a style=""font-weight: bol...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1# Water Services Planning,10.0,NaN,NaN,NaN,69.778,26.464978,20.0,53.75,72.39,92.25,100.0
4# Technical Staff Capacity (Numbers),10.0,NaN,NaN,NaN,53.889,24.798945,15.0,45.0,49.445,76.5,87.0
6# Water Conservation & Water Demand Management (WC/WDM),10.0,NaN,NaN,NaN,71.556,11.89875,55.0,59.14,77.5,80.0,84.0
7# Drinking Water Safety & Regulatory Compliance,10.0,NaN,NaN,NaN,77.222,16.890351,55.0,65.0,75.61,93.5,100.0
10# Infrastructure Asset Management (IAM),10.0,NaN,NaN,NaN,68.667,19.165942,45.0,55.0,62.5,84.6675,99.0
11# Operation & Maintenance (O&M) of Assets,10.0,NaN,NaN,NaN,53.333,15.986105,30.0,41.25,51.665,68.75,75.0

====================================================================================================
DATASET: Operational_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 8

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Risk Type', 'Analysis Done', 'Analysis Failed', 'Compliance Percentage', 'Compliance Result']

Data types:
Region                    object
Time Frame                object
Unnamed: 2                object
Risk Type                 object
Analysis Done             object
Analysis Failed          float64
Compliance Percentage    float64
Compliance Result         object
dtype: object

Missing values:
Time Frame                1
Unnamed: 2               10
Risk Type                 1
Analysis Done             1
Analysis Failed           1
Compliance Percentage     1
Compliance Result         1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Risk Type,Analysis Done,Analysis Failed,Compliance Percentage,Compliance Result
0,City of Johannesburg Metropolitan Municipality,2 026,NaN,Operational,4 751,66.0,98.61,Excellent
1,City of Tshwane Metropolitan Municipality,2 026,NaN,Operational,1 508,196.0,87.00,Poor
2,Ekurhuleni Metropolitan Municipality,2 026,NaN,Operational,3 308,35.0,98.94,Excellent
3,Emfuleni,2 026,NaN,Operational,0,0.0,0.00,Bad
4,Lesedi,2 026,NaN,Operational,124,1.0,99.19,Excellent

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,11,11,City of Johannesburg Metropolitan Municipality,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,10,1,2 026,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,"<b>Data Source:</b> <a style=""font-weight: bol...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Risk Type,10,1,Operational,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Analysis Done,10,9,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Analysis Failed,10.0,NaN,NaN,NaN,81.2,129.743165,0.0,2.25,22.5,85.5,406.0
Compliance Percentage,10.0,NaN,NaN,NaN,76.927,40.711937,0.0,88.535,96.99,98.56,99.19
Compliance Result,10,4,Excellent,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN

====================================================================================================
DATASET: Piped Water Households _ 2026_04_21
====================================================================================================
Rows: 10
Columns: 12

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Piped (tap) water inside dwelling/institution', 'Piped (tap) water inside yard', 'Piped (tap) water on community stand: distance less than 200m fr', 'Piped (tap) water on community stand: distance between 200m and ', 'Piped (tap) water on community stand: distance between 500m and ', 'Piped (tap) water on community stand: distance greater than 1000', 'No access to piped (tap) water', 'Unspecified', 'Not applicable']

Data types:
Region                                                               object
Time Frame                                                           object
Unnamed: 2                                                           object
Piped (tap) water inside dwelling/institution                        object
Piped (tap) water inside yard                                        object
Piped (tap) water on community stand: distance less than 200m fr     object
Piped (tap) water on community stand: distance between 200m and      object
Piped (tap) water on community stand: distance between 500m and      object
Piped (tap) water on community stand: distance greater than 1000     object
No access to piped (tap) water                                       object
Unspecified                                                         float64
Not applicable                                                      float64
dtype: object

Missing values:
Time Frame                                                          1
Unnamed: 2                                                          9
Piped (tap) water inside dwelling/institution                       1
Piped (tap) water inside yard                                       1
Piped (tap) water on community stand: distance less than 200m fr    1
Piped (tap) water on community stand: distance between 200m and     1
Piped (tap) water on community stand: distance between 500m and     1
Piped (tap) water on community stand: distance greater than 1000    1
No access to piped (tap) water                                      1
Unspecified                                                         1
Not applicable                                                      1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Piped (tap) water inside dwelling/institution,Piped (tap) water inside yard,Piped (tap) water on community stand: distance less than 200m fr,Piped (tap) water on community stand: distance between 200m and,Piped (tap) water on community stand: distance between 500m and,Piped (tap) water on community stand: distance greater than 1000,No access to piped (tap) water,Unspecified,Not applicable
0,City of Johannesburg Metropolitan Municipality,Oct 2011,NaN,928 267,386 020,73 265,18 453,6 353,1 970,19 553,0.0,0.0
1,City of Tshwane Metropolitan Municipality,Oct 2011,NaN,585 274,227 278,47 986,12 204,4 942,2 228,30 873,0.0,0.0
2,Ekurhuleni Metropolitan Municipality,Oct 2011,NaN,580 851,303 882,75 741,25 119,13 247,4 783,11 132,0.0,0.0
3,Emfuleni,Oct 2011,NaN,153 874,53 421,7 287,2 312,1 311,535,1 211,0.0,0.0
4,Lesedi,Oct 2011,NaN,15 533,11 813,1 583,214,51,115,346,0.0,0.0

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,10,10,City of Johannesburg Metropolitan Municipality,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,9,1,Oct 2011,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,"<b>Data Source:</b> <a style=""font-weight: bol...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Piped (tap) water inside dwelling/institution,9,9,928 267,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Piped (tap) water inside yard,9,9,386 020,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Piped (tap) water on community stand: distance less than 200m fr,9,9,73 265,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Piped (tap) water on community stand: distance between 200m and,9,9,18 453,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Piped (tap) water on community stand: distance between 500m and,9,9,6 353,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Piped (tap) water on community stand: distance greater than 1000,9,9,1 970,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
No access to piped (tap) water,9,9,19 553,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unspecified,9.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Not applicable,9.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0

====================================================================================================
DATASET: NIWIS_Water Supply Reliability - population_16-Jul-2026
====================================================================================================
Rows: 144
Columns: 14

Column names:
['Unnamed: 0', 'WSA Name', 'population', 'population with access  to water', 'population Reliable Supply', '% population Reliable Supply', 'Urban population', 'Urban population with access to water', 'Urban population Reliable Supply', '% Urban population Reliable Supply', 'Rural population', 'Rural population  with access  to water', 'Rural population Reliable Supply', '% Rural population Reliable Supply']

Data types:
Unnamed: 0                                 float64
WSA Name                                    object
population                                  object
population with access  to water            object
population Reliable Supply                  object
% population Reliable Supply                object
Urban population                            object
Urban population with access to water       object
Urban population Reliable Supply            object
% Urban population Reliable Supply          object
Rural population                            object
Rural population  with access  to water     object
Rural population Reliable Supply            object
% Rural population Reliable Supply          object
dtype: object

Missing values:
Unnamed: 0                                 144
population with access  to water             9
Urban population                             2
Urban population with access to water        2
Urban population Reliable Supply             2
% Urban population Reliable Supply           2
Rural population                             7
Rural population  with access  to water      7
Rural population Reliable Supply             7
% Rural population Reliable Supply           7
dtype: int64

Duplicate rows:
0

First 5 rows:

,Unnamed: 0,WSA Name,population,population with access to water,population Reliable Supply,% population Reliable Supply,Urban population,Urban population with access to water,Urban population Reliable Supply,% Urban population Reliable Supply,Rural population,Rural population with access to water,Rural population Reliable Supply,% Rural population Reliable Supply
0,NaN,Alfred Nzo,829 109,323 859,131 977,16%,46 614,17 722,7 144,15%,782 495,306 137,124 833,16%
1,NaN,Amathole,838 800,509 183,195 069,23%,148 028,106 420,50 650,34%,690 772,402 763,144 419,21%
2,NaN,Blue Crane Route,34 291,32 784,29 486,86%,26 791,25 604,23 029,86%,7 500,7 180,6 457,86%
3,NaN,Buffalo City Metropolitan Municipality,796 675,771 345,571 873,72%,465 125,450 270,338 003,73%,331 550,321 075,233 870,71%
4,NaN,Chris Hani,800 718,596 366,322 992,40%,171 148,157 242,118 650,69%,629 570,439 124,204 342,32%

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Unnamed: 0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WSA Name,144,144,Alfred Nzo,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
population,144,144,829 109,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
population with access to water,135,135,323 859,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
population Reliable Supply,144,144,131 977,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
% population Reliable Supply,144,52,86%,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Urban population,142,142,46 614,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Urban population with access to water,142,142,17 722,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Urban population Reliable Supply,142,142,7 144,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
% Urban population Reliable Supply,142,48,78%,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rural population,137,136,161,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rural population with access to water,137,137,306 137,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rural population Reliable Supply,137,136,2 733,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
% Rural population Reliable Supply,137,57,84%,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN

====================================================================================================
DATASET: Weather
====================================================================================================
Rows: 21301
Columns: 14

Column names:
['STATION', 'NAME', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'DATE', 'PRCP', 'PRCP_ATTRIBUTES', 'TAVG', 'TAVG_ATTRIBUTES', 'TMAX', 'TMAX_ATTRIBUTES', 'TMIN', 'TMIN_ATTRIBUTES']

Data types:
STATION             object
NAME                object
LATITUDE           float64
LONGITUDE          float64
ELEVATION          float64
DATE                object
PRCP               float64
PRCP_ATTRIBUTES     object
TAVG               float64
TAVG_ATTRIBUTES     object
TMAX               float64
TMAX_ATTRIBUTES     object
TMIN               float64
TMIN_ATTRIBUTES     object
dtype: object

Missing values:
PRCP               13284
PRCP_ATTRIBUTES    13284
TMAX                1640
TMAX_ATTRIBUTES     1640
TMIN                4499
TMIN_ATTRIBUTES     4499
dtype: int64

Duplicate rows:
0

First 5 rows:

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,PRCP_ATTRIBUTES,TAVG,TAVG_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES,TMIN,TMIN_ATTRIBUTES
0,SFM00068368,"JOHANNESBURG INTERNATIONAL, SF",-26.139,28.246,1694.1,2000-01-01,15.5,",,S",17.2,"H,,S",26.8,",,S",13.7,",,S"
1,SFM00068368,"JOHANNESBURG INTERNATIONAL, SF",-26.139,28.246,1694.1,2000-01-02,0.5,",,S",18.3,"H,,S",24.4,",,S",NaN,NaN
2,SFM00068368,"JOHANNESBURG INTERNATIONAL, SF",-26.139,28.246,1694.1,2000-01-03,5.6,",,S",16.0,"H,,S",24.4,",,S",13.4,",,S"
3,SFM00068368,"JOHANNESBURG INTERNATIONAL, SF",-26.139,28.246,1694.1,2000-01-04,1.5,",,S",16.7,"H,,S",21.7,",,S",12.3,",,S"
4,SFM00068368,"JOHANNESBURG INTERNATIONAL, SF",-26.139,28.246,1694.1,2000-01-05,7.4,",,S",17.2,"H,,S",21.7,",,S",14.3,",,S"

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
STATION,21301,3,SFM00068263,9126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NAME,21301,3,"PRETORIA IRENE, SF",9126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LATITUDE,21301.0,NaN,NaN,NaN,-25.945538,0.153683,-26.139,-26.139,-25.917,-25.917,-25.733
LONGITUDE,21301.0,NaN,NaN,NaN,28.218314,0.023565,28.183,28.217,28.217,28.246,28.246
ELEVATION,21301.0,NaN,NaN,NaN,1520.803319,140.180907,1322.0,1500.0,1500.0,1694.1,1694.1
DATE,21301,9241,2018-04-23,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PRCP,8017.0,NaN,NaN,NaN,4.384533,10.589892,0.0,0.0,0.5,4.3,340.1
PRCP_ATTRIBUTES,8017,4,",,S",6469,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TAVG,21301.0,NaN,NaN,NaN,17.58986,4.466002,0.8,14.3,18.1,20.9,31.4
TAVG_ATTRIBUTES,21301,1,"H,,S",21301,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TMAX,19661.0,NaN,NaN,NaN,25.256096,4.623825,6.9,22.0,25.6,28.7,38.8
TMAX_ATTRIBUTES,19661,2,",,S",19660,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TMIN,16802.0,NaN,NaN,NaN,11.36129,4.973602,-7.0,7.5,12.2,15.3,26.1
TMIN_ATTRIBUTES,16802,3,",,S",16798,NaN,NaN,NaN,NaN,NaN,NaN,NaN

====================================================================================================
DATASET: Timeseries Households_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 35

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'April 1994', 'April 1995', 'April 1996', 'April 1997', 'April 1998', 'April 1999', 'April 2000', 'April 2001', 'April 2002', 'April 2004', 'April 2005', 'April 2006', 'April 2007', 'April 2008', 'April 2009', 'April 2010', 'April 2011', 'April 2012', 'April 2013', 'April 2014', 'April 2015', 'April 2016', 'April 2017', 'April 2018', 'April 2019', 'April 2020', 'April 2021', 'April 2022', 'April 2023', 'April 2024', 'April 2025', 'April 2026']

Data types:
Region        object
Time Frame    object
Unnamed: 2    object
April 1994    object
April 1995    object
April 1996    object
April 1997    object
April 1998    object
April 1999    object
April 2000    object
April 2001    object
April 2002    object
April 2004    object
April 2005    object
April 2006    object
April 2007    object
April 2008    object
April 2009    object
April 2010    object
April 2011    object
April 2012    object
April 2013    object
April 2014    object
April 2015    object
April 2016    object
April 2017    object
April 2018    object
April 2019    object
April 2020    object
April 2021    object
April 2022    object
April 2023    object
April 2024    object
April 2025    object
April 2026    object
dtype: object

Missing values:
Time Frame     1
Unnamed: 2    10
April 1994     1
April 1995     1
April 1996     1
April 1997     1
April 1998     1
April 1999     1
April 2000     1
April 2001     1
April 2002     1
April 2004     1
April 2005     1
April 2006     1
April 2007     1
April 2008     1
April 2009     1
April 2010     1
April 2011     1
April 2012     1
April 2013     1
April 2014     1
April 2015     1
April 2016     1
April 2017     1
April 2018     1
April 2019     1
April 2020     1
April 2021     1
April 2022     1
April 2023     1
April 2024     1
April 2025     1
April 2026     1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,April 1994,April 1995,April 1996,April 1997,April 1998,April 1999,April 2000,...,April 2017,April 2018,April 2019,April 2020,April 2021,April 2022,April 2023,April 2024,April 2025,April 2026
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,674 814,716 493,760 743,807 730,857 635,910 638,966 931,...,1 928 958,2 063 091,2 150 924,2 196 476,2 243 001,1 841 886,1 879 191,1 917 263,1 957 863,1 999 327
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,417 911,442 164,467 847,495 038,523 835,554 333,586 634,...,1 183 242,1 265 542,1 319 400,1 347 343,1 375 878,1 322 267,1 364 820,1 408 735,1 438 582,1 469 057
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,498 971,529 782,562 507,597 248,634 137,673 317,714 930,...,1 352 475,1 446 278,1 507 844,1 539 784,1 572 389,1 420 998,1 461 524,1 503 219,1 535 062,1 567 566
3,Emfuleni,April 2026,NaN,125 377,133 102,141 300,150 003,159 248,169 071,179 505,...,263 813,281 072,293 031,299 242,305 585,297 907,305 424,313 129,319 762,326 534
4,Lesedi,April 2026,NaN,12 323,13 082,13 891,14 749,15 660,16 625,17 653,...,40 891,43 735,45 596,46 561,47 546,42 599,43 927,45 294,46 254,47 233

Numerical summary:

,count,unique,top,freq
Region,11,11,City of Johannesburg Metropolitan Municipality,1
Time Frame,10,1,April 2026,10
Unnamed: 2,1,1,"<b>Data Source:</b> <a style=""font-weight: bol...",1
April 1994,10,10,674 814,1
April 1995,10,10,716 493,1
April 1996,10,10,760 743,1
April 1997,10,10,807 730,1
April 1998,10,10,857 635,1
April 1999,10,10,910 638,1
April 2000,10,10,966 931,1
April 2001,10,10,1 026 709,1
April 2002,10,10,1 087 654,1
April 2004,10,10,1 160 326,1
April 2005,10,10,1 206 903,1
April 2006,10,10,1 231 136,1
April 2007,10,10,1 238 524,1
April 2008,10,10,1 257 092,1
April 2009,10,10,1 264 631,1
April 2010,10,10,1 323 652,1
April 2011,10,10,1 434 871,1
April 2012,10,10,1 510 231,1
April 2013,10,10,1 589 534,1
April 2014,10,10,1 673 007,1
April 2015,10,10,1 760 869,1
April 2016,10,10,1 853 348,1
April 2017,10,10,1 928 958,1
April 2018,10,10,2 063 091,1
April 2019,10,10,2 150 924,1
April 2020,10,10,2 196 476,1
April 2021,10,10,2 243 001,1
April 2022,10,10,1 841 886,1
April 2023,10,10,1 879 191,1
April 2024,10,10,1 917 263,1
April 2025,10,10,1 957 863,1
April 2026,10,10,1 999 327,1

====================================================================================================
DATASET: NIWIS_RWT_16-Jul-2026
====================================================================================================
Rows: 9
Columns: 5

Column names:
['WMA', 'Date', 'Domestic and Industry c/m3', 'Irrigation c/m3', 'Forestry c/m3']

Data types:
WMA                            object
Date                            int64
Domestic and Industry c/m3    float64
Irrigation c/m3               float64
Forestry c/m3                 float64
dtype: object

Missing values:
No missing values.

Duplicate rows:
0

First 5 rows:

,WMA,Date,Domestic and Industry c/m3,Irrigation c/m3,Forestry c/m3
0,Berg Olifants,2025,6.59,3.22,3.15
1,Breede Gouritz,2025,6.14,3.43,1.76
2,Inkomati Usuthu,2025,5.48,2.70,2.15
3,Limpopo NorthWest,2025,5.21,3.84,3.09
4,Mzimvubu Tsitsikamma,2025,4.38,3.50,3.18

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
WMA,9,9,Berg Olifants,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date,9.0,NaN,NaN,NaN,2025.0,0.0,2025.0,2025.0,2025.0,2025.0,2025.0
Domestic and Industry c/m3,9.0,NaN,NaN,NaN,4.581111,1.488367,1.98,3.56,4.78,5.48,6.59
Irrigation c/m3,9.0,NaN,NaN,NaN,2.981111,0.82788,1.15,2.64,3.22,3.5,3.84
Forestry c/m3,9.0,NaN,NaN,NaN,2.358889,1.010105,0.0,2.15,2.64,3.09,3.18

====================================================================================================
DATASET: Protests Identified by Municipal IQ_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 16

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Total Protests', 'Informal', 'Violent', 'Xenophobia', 'Criminality', 'Corruption', 'Councillor', 'Water', 'Sanitation', 'Electricity', 'Refuse Removal', 'Roads', 'Housing']

Data types:
Region             object
Time Frame         object
Unnamed: 2         object
Total Protests    float64
Informal          float64
Violent           float64
Xenophobia        float64
Criminality       float64
Corruption        float64
Councillor        float64
Water             float64
Sanitation        float64
Electricity       float64
Refuse Removal    float64
Roads             float64
Housing           float64
dtype: object

Missing values:
Time Frame         1
Unnamed: 2        10
Total Protests     1
Informal           1
Violent            1
Xenophobia         1
Criminality        1
Corruption         1
Councillor         1
Water              1
Sanitation         1
Electricity        1
Refuse Removal     1
Roads              1
Housing            1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Total Protests,Informal,Violent,Xenophobia,Criminality,Corruption,Councillor,Water,Sanitation,Electricity,Refuse Removal,Roads,Housing
0,City of Johannesburg Metropolitan Municipality,2 018,NaN,174.0,101.0,143.0,4.0,17.0,5.0,35.0,37.0,26.0,76.0,7.0,9.0,77.0
1,City of Tshwane Metropolitan Municipality,2 018,NaN,85.0,28.0,64.0,2.0,7.0,16.0,33.0,36.0,18.0,29.0,2.0,11.0,38.0
2,Ekurhuleni Metropolitan Municipality,2 018,NaN,73.0,42.0,57.0,3.0,6.0,9.0,18.0,16.0,12.0,31.0,1.0,2.0,27.0
3,Emfuleni,2 018,NaN,15.0,3.0,13.0,1.0,2.0,2.0,4.0,3.0,1.0,1.0,0.0,4.0,4.0
4,Lesedi,2 018,NaN,2.0,0.0,2.0,2.0,2.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,11,11,City of Johannesburg Metropolitan Municipality,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,10,1,2 018,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,"<b>Data Source:</b> <a style=""font-weight: bol...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Protests,10.0,NaN,NaN,NaN,76.2,120.400074,2.0,7.25,13.5,82.0,381.0
Informal,10.0,NaN,NaN,NaN,37.8,61.705033,0.0,3.25,5.5,38.5,189.0
Violent,10.0,NaN,NaN,NaN,60.8,96.402858,1.0,5.0,12.5,62.25,304.0
Xenophobia,10.0,NaN,NaN,NaN,3.0,4.447221,0.0,0.25,2.0,3.0,15.0
Criminality,10.0,NaN,NaN,NaN,7.8,12.044362,0.0,1.25,2.5,6.75,39.0
Corruption,10.0,NaN,NaN,NaN,7.4,11.529672,0.0,1.25,2.0,8.0,37.0
Councillor,10.0,NaN,NaN,NaN,21.0,32.228352,0.0,2.5,6.0,29.25,105.0
Water,10.0,NaN,NaN,NaN,20.0,31.53129,0.0,2.0,3.0,31.0,100.0
Sanitation,10.0,NaN,NaN,NaN,12.8,20.048829,0.0,1.0,2.5,16.5,64.0
Electricity,10.0,NaN,NaN,NaN,30.6,49.09673,1.0,2.0,5.5,30.5,153.0
Refuse Removal,10.0,NaN,NaN,NaN,2.4,4.005552,0.0,0.0,0.5,2.0,12.0
Roads,10.0,NaN,NaN,NaN,5.6,8.796464,0.0,0.0,2.0,7.75,28.0
Housing,10.0,NaN,NaN,NaN,31.2,50.272148,0.0,2.25,3.5,35.25,156.0

====================================================================================================
DATASET: People Served with Water_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 17

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Population served with water 1994 to April 2025', 'Population served with water 201415', 'Population served with water 201516', 'Population served with water 201617', 'Population served with water 201718', 'Population served with water 201819', 'Population served with water 201920', 'Population served with water 202021', 'Population served with water 202122', 'Population served with water 202223', 'Population served with water 202324', 'Population served with water 202425', 'Population served with water 202526', 'Planned Population to be served 202627']

Data types:
Region                                              object
Time Frame                                          object
Unnamed: 2                                          object
Population served with water 1994 to April 2025     object
Population served with water 201415                 object
Population served with water 201516                 object
Population served with water 201617                 object
Population served with water 201718                 object
Population served with water 201819                 object
Population served with water 201920                 object
Population served with water 202021                 object
Population served with water 202122                float64
Population served with water 202223                 object
Population served with water 202324                 object
Population served with water 202425                 object
Population served with water 202526                 object
Planned Population to be served 202627              object
dtype: object

Missing values:
Time Frame                                          1
Unnamed: 2                                         10
Population served with water 1994 to April 2025     1
Population served with water 201415                 1
Population served with water 201516                 1
Population served with water 201617                 1
Population served with water 201718                 1
Population served with water 201819                 1
Population served with water 201920                 1
Population served with water 202021                 1
Population served with water 202122                 1
Population served with water 202223                 1
Population served with water 202324                 1
Population served with water 202425                 1
Population served with water 202526                 1
Planned Population to be served 202627              1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Population served with water 1994 to April 2025,Population served with water 201415,Population served with water 201516,Population served with water 201617,Population served with water 201718,Population served with water 201819,Population served with water 201920,Population served with water 202021,Population served with water 202122,Population served with water 202223,Population served with water 202324,Population served with water 202425,Population served with water 202526,Planned Population to be served 202627
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,1 877 971,877,61 779,37 123,94 764,62 860,30 140,30 769,0.0,24 998,7 780,52 267,14 933,8 299
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,1 154 171,153,32 631,29 923,56 353,41 544,24 560,23 822,0.0,16 038,27 098,42 371,12 617,7 764
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,1 528 720,658,24 089,37 491,66 459,46 565,26 498,21 012,0.0,17 028,21 736,46 224,13 094,11 383
3,Emfuleni,April 2026,NaN,392 260,0,2 117,2 189,13 579,9 070,5 101,4 584,0.0,3 687,5 296,11 809,3 067,5 531
4,Lesedi,April 2026,NaN,46 377,278,1 213,742,1 514,1 356,757,818,0.0,555,801,1 429,425,210

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,11,11,City of Johannesburg Metropolitan Municipality,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,10,1,April 2026,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,<b>Data Source:</b> Census 2011 Modelled and U...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population served with water 1994 to April 2025,10,10,1 877 971,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population served with water 201415,10,6,0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population served with water 201516,10,10,61 779,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population served with water 201617,10,10,37 123,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population served with water 201718,10,10,94 764,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population served with water 201819,10,10,62 860,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population served with water 201920,10,10,30 140,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population served with water 202021,10,10,30 769,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population served with water 202122,10.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Population served with water 202223,10,10,24 998,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population served with water 202324,10,10,7 780,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population served with water 202425,10,10,52 267,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population served with water 202526,10,10,14 933,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Planned Population to be served 202627,10,10,8 299,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

====================================================================================================
DATASET: NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026
====================================================================================================
Rows: 0
Columns: 4

Column names:
['WSA', 'Population', 'Population with access', '%Population  with access']

Data types:
WSA                         object
Population                  object
Population with access      object
%Population  with access    object
dtype: object

Missing values:
No missing values.

Duplicate rows:
0

First 5 rows:

Empty DataFrame
Columns: [WSA, Population, Population with access, %Population  with access]
Index: []

Numerical summary:

                         count unique  top freq
WSA                          0      0  NaN  NaN
Population                   0      0  NaN  NaN
Population with access       0      0  NaN  NaN
%Population  with access     0      0  NaN  NaN

====================================================================================================
DATASET: Areas of Highest Vulnerability_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 21

Column names:
['Region', 'Time Frame', 'Unnamed: 2', '1# Water Services Planning', '2# Management Skill Level (Technical)', '3# Staff Skill Level (Technical)', '4# Technical Staff Capacity (Numbers)', '5# Water Resource Management (WRM)', '6# Water Conservation & Water Demand Management (WC/WDM)', '7# Drinking Water Safety & Regulatory Compliance', '8# Basic Sanitation', '9# Wastewater/Environmental Safety & Regulatory Compliance', '10# Infrastructure Asset Management (IAM)', '11# Operation & Maintenance (O&M) of Assets', '12# Financial Management', '13# Revenue Collection', '14# Financial Asset Management', '15# Information Management (IT)', '16# Organisational Performance Monitoring', '17# Water and Sanitation Service Quality', '18# Customer Care (CRM)']

Data types:
Region                                                        object
Time Frame                                                    object
Unnamed: 2                                                    object
1# Water Services Planning                                    object
2# Management Skill Level (Technical)                         object
3# Staff Skill Level (Technical)                              object
4# Technical Staff Capacity (Numbers)                         object
5# Water Resource Management (WRM)                            object
6# Water Conservation & Water Demand Management (WC/WDM)      object
7# Drinking Water Safety & Regulatory Compliance              object
8# Basic Sanitation                                           object
9# Wastewater/Environmental Safety & Regulatory Compliance    object
10# Infrastructure Asset Management (IAM)                     object
11# Operation & Maintenance (O&M) of Assets                   object
12# Financial Management                                      object
13# Revenue Collection                                        object
14# Financial Asset Management                                object
15# Information Management (IT)                               object
16# Organisational Performance Monitoring                     object
17# Water and Sanitation Service Quality                      object
18# Customer Care (CRM)                                       object
dtype: object

Missing values:
Time Frame                                                     1
Unnamed: 2                                                    10
1# Water Services Planning                                     1
2# Management Skill Level (Technical)                          1
3# Staff Skill Level (Technical)                               1
4# Technical Staff Capacity (Numbers)                          1
5# Water Resource Management (WRM)                             1
6# Water Conservation & Water Demand Management (WC/WDM)       1
7# Drinking Water Safety & Regulatory Compliance               1
8# Basic Sanitation                                            1
9# Wastewater/Environmental Safety & Regulatory Compliance     1
10# Infrastructure Asset Management (IAM)                      1
11# Operation & Maintenance (O&M) of Assets                    1
12# Financial Management                                       1
13# Revenue Collection                                         1
14# Financial Asset Management                                 1
15# Information Management (IT)                                1
16# Organisational Performance Monitoring                      1
17# Water and Sanitation Service Quality                       1
18# Customer Care (CRM)                                        1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,1# Water Services Planning,2# Management Skill Level (Technical),3# Staff Skill Level (Technical),4# Technical Staff Capacity (Numbers),5# Water Resource Management (WRM),6# Water Conservation & Water Demand Management (WC/WDM),7# Drinking Water Safety & Regulatory Compliance,...,9# Wastewater/Environmental Safety & Regulatory Compliance,10# Infrastructure Asset Management (IAM),11# Operation & Maintenance (O&M) of Assets,12# Financial Management,13# Revenue Collection,14# Financial Asset Management,15# Information Management (IT),16# Organisational Performance Monitoring,17# Water and Sanitation Service Quality,18# Customer Care (CRM)
0,City of Johannesburg Metropolitan Municipality,2 018,NaN,Low,Low,Low,Low,Extreme,Low,Low,...,Low,Low,Moderate,Low,Low,Low,Low,Low,Low,Low
1,City of Tshwane Metropolitan Municipality,2 018,NaN,Low,Low,Low,Extreme,Moderate,Low,Low,...,Extreme,Moderate,Extreme,Low,Low,Extreme,Low,Low,Low,Low
2,Ekurhuleni Metropolitan Municipality,2 018,NaN,Low,Moderate,Low,Low,Low,Low,Low,...,Moderate,Low,Moderate,Low,Low,High,Low,Low,Low,Low
3,Emfuleni,2 018,NaN,Extreme,Extreme,Extreme,Extreme,High,High,Moderate,...,Extreme,High,Extreme,Extreme,High,Extreme,Extreme,Low,Moderate,Extreme
4,Lesedi,2 018,NaN,Moderate,Moderate,Moderate,Moderate,Extreme,Low,Moderate,...,High,High,Extreme,Extreme,Low,Extreme,Low,Low,Moderate,Low

Numerical summary:

,count,unique,top,freq
Region,11,11,City of Johannesburg Metropolitan Municipality,1
Time Frame,10,1,2 018,10
Unnamed: 2,1,1,"<b>Data Source:</b> <a style=""font-weight: bol...",1
1# Water Services Planning,10,4,Low,5
2# Management Skill Level (Technical),10,3,Moderate,4
3# Staff Skill Level (Technical),10,4,Low,4
4# Technical Staff Capacity (Numbers),10,4,Extreme,5
5# Water Resource Management (WRM),10,4,Low,5
6# Water Conservation & Water Demand Management (WC/WDM),10,3,Low,6
7# Drinking Water Safety & Regulatory Compliance,10,3,Low,5
8# Basic Sanitation,10,3,Moderate,5
9# Wastewater/Environmental Safety & Regulatory Compliance,10,4,Extreme,4
10# Infrastructure Asset Management (IAM),10,4,Low,3
11# Operation & Maintenance (O&M) of Assets,10,4,Extreme,4
12# Financial Management,10,3,Low,5
13# Revenue Collection,10,4,Low,4
14# Financial Asset Management,10,4,Extreme,7
15# Information Management (IT),10,2,Low,9
16# Organisational Performance Monitoring,10,2,Low,9
17# Water and Sanitation Service Quality,10,3,Low,7
18# Customer Care (CRM),10,3,Low,6

====================================================================================================
DATASET: Water demand growth_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 10

Column names:
['Region', 'Time Frame', 'Unnamed: 2', '% Water Demand Growth', '% Non-Revenue Water', '% Water Losses', 'System input volume (litres)', 'Revenue water (litres)', 'Non-Revenue water (litres)', 'Water Losses (litres)']

Data types:
Region                           object
Time Frame                       object
Unnamed: 2                       object
% Water Demand Growth           float64
% Non-Revenue Water             float64
% Water Losses                  float64
System input volume (litres)     object
Revenue water (litres)           object
Non-Revenue water (litres)       object
Water Losses (litres)            object
dtype: object

Missing values:
Time Frame                       1
Unnamed: 2                      10
% Water Demand Growth            1
% Non-Revenue Water              1
% Water Losses                   1
System input volume (litres)     1
Revenue water (litres)           1
Non-Revenue water (litres)       1
Water Losses (litres)            1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,% Water Demand Growth,% Non-Revenue Water,% Water Losses,System input volume (litres),Revenue water (litres),Non-Revenue water (litres),Water Losses (litres)
0,City of Johannesburg Metropolitan Municipality,2 018,NaN,2.24,35.74,34.34,536 312 001.00,344 641 579.00,191 670 422.00,184 160 156.00
1,City of Tshwane Metropolitan Municipality,2 018,NaN,-0.40,25.48,24.42,318 733 465.00,237 530 661.00,81 202 804.00,77 831 360.00
2,Ekurhuleni Metropolitan Municipality,2 018,NaN,3.35,39.34,31.30,338 742 752.00,205 497 030.00,133 245 722.00,106 026 481.00
3,Emfuleni,2 018,NaN,-1.12,48.80,48.80,82 417 605.00,42 197 813.76,40 219 791.24,40 219 791.00
4,Lesedi,2 018,NaN,-1.73,23.00,23.00,6 328 721.00,4 873 115.17,1 455 605.83,1 455 606.00

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,11,11,City of Johannesburg Metropolitan Municipality,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,10,1,2 018,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,<b>Data Source:</b> Census 2001 Modelled and U...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
% Water Demand Growth,10.0,NaN,NaN,NaN,0.651,4.909982,-10.13,-0.94,0.575,3.0725,8.9
% Non-Revenue Water,10.0,NaN,NaN,NaN,33.889,7.591215,23.0,28.69,35.02,37.4275,48.8
% Water Losses,10.0,NaN,NaN,NaN,31.864,7.504036,23.0,27.45,30.25,34.33,48.8
System input volume (litres),10,10,536 312 001.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Revenue water (litres),10,10,344 641 579.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Non-Revenue water (litres),10,10,191 670 422.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Water Losses (litres),10,10,184 160 156.00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

====================================================================================================
DATASET: Total Population_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 8

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Total Population', 'Total Households', 'HH Density', 'Urban Population', 'Rural Population']

Data types:
Region               object
Time Frame           object
Unnamed: 2           object
Total Population     object
Total Households     object
HH Density          float64
Urban Population     object
Rural Population     object
dtype: object

Missing values:
Time Frame           1
Unnamed: 2          10
Total Population     1
Total Households     1
HH Density           1
Urban Population     1
Rural Population     1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Total Population,Total Households,HH Density,Urban Population,Rural Population
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,5 045 624,1 999 327,2.52,4 827 348,218 276
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,4 426 868,1 469 057,3.01,3 977 415,449 453
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,4 391 840,1 567 566,2.80,3 824 427,567 413
3,Emfuleni,April 2026,NaN,1 025 702,326 534,3.14,952 341,73 361
4,Lesedi,April 2026,NaN,144 504,47 233,3.06,118 922,25 582

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,11,11,City of Johannesburg Metropolitan Municipality,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,10,1,April 2026,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,"<b>Data Source:</b> <a style=""font-weight: bol...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Population,10,10,5 045 624,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Households,10,10,1 999 327,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HH Density,10.0,NaN,NaN,NaN,2.861,0.217432,2.51,2.785,2.87,3.04,3.14
Urban Population,10,10,4 827 348,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rural Population,10,10,218 276,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

====================================================================================================
DATASET: NIWIS_GroundwaterStatus_16-Jul-2026
====================================================================================================
Rows: 1947
Columns: 8

Column names:
['Quaternary', 'Reserve Study', 'Available (GRA2)(m3/a)', 'Recharge (GWR)(m3/a)', 'Reserve (GWR)(m3/a)', 'Abstracted (WARMS)(m3/a)', 'Surplus (GRA2)(m3/a)', 'Surplus (GWR)(m3/a)']

Data types:
Quaternary                  object
Reserve Study                int64
Available (GRA2)(m3/a)      object
Recharge (GWR)(m3/a)        object
Reserve (GWR)(m3/a)         object
Abstracted (WARMS)(m3/a)    object
Surplus (GRA2)(m3/a)        object
Surplus (GWR)(m3/a)         object
dtype: object

Missing values:
Recharge (GWR)(m3/a)    837
Reserve (GWR)(m3/a)     837
Surplus (GWR)(m3/a)     837
dtype: int64

Duplicate rows:
1

First 5 rows:

,Quaternary,Reserve Study,Available (GRA2)(m3/a),Recharge (GWR)(m3/a),Reserve (GWR)(m3/a),Abstracted (WARMS)(m3/a),Surplus (GRA2)(m3/a),Surplus (GWR)(m3/a)
0,E10A,1,3 797 140,30 120 000,5 440 000,123 420,3 673 720,24 556 580
1,E10B,1,5 302 850,37 170 000,6 790 000,12 050 080,-6 747 230,18 329 920
2,E10C,1,3 596 190,24 790 000,5 660 000,991 600,2 604 590,18 138 400
3,E10D,1,2 737 390,24 350 000,5 740 000,0,2 737 390,18 610 000
4,E10E,1,2 361 910,30 670 000,7 490 000,2 091 128,270 782,21 088 872

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Quaternary,1947,1946,H70K,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Reserve Study,1947.0,NaN,NaN,NaN,0.570108,0.495188,0.0,0.0,1.0,1.0,1.0
Available (GRA2)(m3/a),1947,1863,0,83,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Recharge (GWR)(m3/a),1110,949,500 000,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Reserve (GWR)(m3/a),1110,712,0,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Abstracted (WARMS)(m3/a),1947,1515,0,378,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Surplus (GRA2)(m3/a),1947,1866,0,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Surplus (GWR)(m3/a),1110,1105,500 000,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN

====================================================================================================
DATASET: Residential Tariffs_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 7

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Tariff 0-6kl (incl#VAT)', 'Tariff 6-20kl (incl#VAT)', 'Tariff 20-60kl (incl#VAT)', 'Tariff >60kl (incl#VAT)']

Data types:
Region                       object
Time Frame                   object
Unnamed: 2                   object
Tariff 0-6kl (incl#VAT)      object
Tariff 6-20kl (incl#VAT)     object
Tariff 20-60kl (incl#VAT)    object
Tariff >60kl (incl#VAT)      object
dtype: object

Missing values:
Time Frame                    1
Unnamed: 2                   10
Tariff 0-6kl (incl#VAT)       1
Tariff 6-20kl (incl#VAT)      1
Tariff 20-60kl (incl#VAT)     1
Tariff >60kl (incl#VAT)       1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Tariff 0-6kl (incl#VAT),Tariff 6-20kl (incl#VAT),Tariff 20-60kl (incl#VAT),Tariff >60kl (incl#VAT)
0,City of Johannesburg Metropolitan Municipality,2 018,NaN,"R0,00","R13,90","R33,73","R38,13"
1,City of Tshwane Metropolitan Municipality,2 018,NaN,"R10,95","R18,89","R29,39","R33,63"
2,Ekurhuleni Metropolitan Municipality,2 018,NaN,"R0,00","R18,30","R26,80","R31,83"
3,Emfuleni,2 018,NaN,"R15,99","R26,94","R39,35","R43,57"
4,Lesedi,2 018,NaN,"R16,06","R19,50","R28,06","R42,45"

Numerical summary:

,count,unique,top,freq
Region,11,11,City of Johannesburg Metropolitan Municipality,1
Time Frame,10,1,2 018,10
Unnamed: 2,1,1,<b>Data Source:</b> Census 2001 Modelled and U...,1
Tariff 0-6kl (incl#VAT),10,8,"R0,00",3
Tariff 6-20kl (incl#VAT),10,10,"R13,90",1
Tariff 20-60kl (incl#VAT),10,10,"R33,73",1
Tariff >60kl (incl#VAT),10,10,"R38,13",1

====================================================================================================
DATASET: Households Served with Water_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 17

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Households served with water 1994 to April 2025', 'Households served with water 201415', 'Households served with water 201516', 'Households served with water 201617', 'Households served with water 201718', 'Households served with water 201819', 'Households served with water 201920', 'Households served with water 202021', 'Households served with water 202122', 'Households served with water 202223', 'Households served with water 202324', 'Households served with water 202425', 'Households served with water 202526', 'Planned Households to be served 202627']

Data types:
Region                                              object
Time Frame                                          object
Unnamed: 2                                          object
Households served with water 1994 to April 2025     object
Households served with water 201415                float64
Households served with water 201516                 object
Households served with water 201617                 object
Households served with water 201718                 object
Households served with water 201819                 object
Households served with water 201920                 object
Households served with water 202021                 object
Households served with water 202122                float64
Households served with water 202223                 object
Households served with water 202324                 object
Households served with water 202425                 object
Households served with water 202526                 object
Planned Households to be served 202627              object
dtype: object

Missing values:
Time Frame                                          1
Unnamed: 2                                         10
Households served with water 1994 to April 2025     1
Households served with water 201415                 1
Households served with water 201516                 1
Households served with water 201617                 1
Households served with water 201718                 1
Households served with water 201819                 1
Households served with water 201920                 1
Households served with water 202021                 1
Households served with water 202122                 1
Households served with water 202223                 1
Households served with water 202324                 1
Households served with water 202425                 1
Households served with water 202526                 1
Planned Households to be served 202627              1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Households served with water 1994 to April 2025,Households served with water 201415,Households served with water 201516,Households served with water 201617,Households served with water 201718,Households served with water 201819,Households served with water 201920,Households served with water 202021,Households served with water 202122,Households served with water 202223,Households served with water 202324,Households served with water 202425,Households served with water 202526,Planned Households to be served 202627
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,653 974,276.0,22 986,14 316,35 909,23 781,11 412,11 653,0.0,9 810,3 077,20 334,5 912,2 762
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,370 255,18.0,11 244,10 653,19 806,14 583,8 630,8 355,0.0,5 835,8 976,13 803,4 187,2 394
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,517 293,190.0,9 227,14 617,25 932,18 215,10 356,8 200,0.0,6 886,7 704,16 217,4 679,2 940
3,Emfuleni,April 2026,NaN,121 764,0.0,726,807,4 759,3 174,1 774,1 600,0.0,1 324,1 674,3 693,968,1 016
4,Lesedi,April 2026,NaN,13 756,98.0,420,251,532,479,265,287,0.0,201,259,458,140,63

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,11,11,City of Johannesburg Metropolitan Municipality,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,10,1,April 2026,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,<b>Data Source:</b> Census 2011 Modelled and U...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households served with water 1994 to April 2025,10,10,653 974,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households served with water 201415,10.0,NaN,NaN,NaN,116.4,190.157362,0.0,0.0,9.0,167.0,582.0
Households served with water 201516,10,10,22 986,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households served with water 201617,10,10,14 316,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households served with water 201718,10,10,35 909,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households served with water 201819,10,10,23 781,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households served with water 201920,10,10,11 412,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households served with water 202021,10,10,11 653,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households served with water 202122,10.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Households served with water 202223,10,10,9 810,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households served with water 202324,10,10,3 077,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households served with water 202425,10,10,20 334,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Households served with water 202526,10,10,5 912,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Planned Households to be served 202627,10,10,2 762,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

====================================================================================================
DATASET: Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]
====================================================================================================
Rows: 4
Columns: 2

Column names:
["'Category", "'SANS 241 :2006:"]

Data types:
'Category            object
'SANS 241 :2006:    float64
dtype: object

Missing values:
No missing values.

Duplicate rows:
0

First 5 rows:

                             'Category  'SANS 241 :2006:
0                   'Chemical : Health         94.857059
1            'Microbiological : Health         96.086215
2            'Operational : Non-Health         91.560539
3  'Physical Orhanoleptic : Non-Health         98.819385

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
'Category,4,4,'Chemical : Health,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'SANS 241 :2006:,4.0,NaN,NaN,NaN,95.330799,3.009993,91.560539,94.032929,95.471637,96.769507,98.819385

====================================================================================================
DATASET: Institutional Compliance_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 5

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Potable Water Compliance Percentage', 'Effluent Water Compliance Percentage']

Data types:
Region                                   object
Time Frame                               object
Unnamed: 2                               object
Potable Water Compliance Percentage     float64
Effluent Water Compliance Percentage    float64
dtype: object

Missing values:
Time Frame                               1
Unnamed: 2                              10
Potable Water Compliance Percentage      1
Effluent Water Compliance Percentage     1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Potable Water Compliance Percentage,Effluent Water Compliance Percentage
0,City of Johannesburg Metropolitan Municipality,April 2022,NaN,102.68,96.99
1,City of Tshwane Metropolitan Municipality,April 2022,NaN,89.45,74.85
2,Ekurhuleni Metropolitan Municipality,April 2022,NaN,101.55,98.91
3,Emfuleni,April 2022,NaN,62.20,77.38
4,Lesedi,April 2022,NaN,97.16,88.04

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,11,11,City of Johannesburg Metropolitan Municipality,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,10,1,April 2022,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,<b>Data Source:</b> DWS Water Services and Reg...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Potable Water Compliance Percentage,10.0,NaN,NaN,NaN,93.051,14.545463,62.2,91.3775,99.54,102.3975,103.51
Effluent Water Compliance Percentage,10.0,NaN,NaN,NaN,76.749,15.78266,52.33,68.4325,76.115,87.25,98.91

====================================================================================================
DATASET: Surface Water Storage ( 2020 -2026)
====================================================================================================
Rows: 375
Columns: 9

Column names:
["'DateTime", "'High", "'Moderately High", "'Normal", "'Moderately Low", "'Low", "'Very Low", "'2024/2025", "'2025/2026"]

Data types:
'DateTime            object
'High               float64
'Moderately High    float64
'Normal             float64
'Moderately Low     float64
'Low                float64
'Very Low           float64
'2024/2025          float64
'2025/2026          float64
dtype: object

Missing values:
'High               303
'Moderately High    303
'Normal             303
'Moderately Low     303
'Low                303
'Very Low           303
'2024/2025           62
'2025/2026           73
dtype: int64

Duplicate rows:
0

First 5 rows:

,'DateTime,'High,'Moderately High,'Normal,'Moderately Low,'Low,'Very Low,'2024/2025,'2025/2026
0,'2020-10-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,64.673521,63.926720
1,'2020-10-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,63.827687,63.278295
2,'2020-10-15 00:00:00,90.99,84.02,79.47,70.61,64.17,61.1,62.867617,62.632930
3,'2020-10-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,61.857000,61.851849
4,'2020-10-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,60.946196,61.128307

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
'DateTime,375,375,'2026-09-24 00:00:00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'High,72.0,NaN,NaN,NaN,96.222917,2.434156,90.99,94.46,96.64,97.4,101.7
'Moderately High,72.0,NaN,NaN,NaN,87.777188,2.258706,82.935,85.81875,88.3975,89.5875,91.2
'Normal,72.0,NaN,NaN,NaN,84.295917,3.050318,77.8,81.9025,85.739,86.6475,88.428
'Moderately Low,72.0,NaN,NaN,NaN,78.023972,3.987864,66.3,75.298,79.116,80.9905,84.094
'Low,72.0,NaN,NaN,NaN,68.60684,5.609553,60.11,63.6575,69.2875,73.4975,78.5925
'Very Low,72.0,NaN,NaN,NaN,63.392375,4.005177,57.008,58.7855,64.3,67.15,69.324
'2024/2025,313.0,NaN,NaN,NaN,83.470865,11.447626,56.56236,76.524777,85.979025,93.298052,100.215673
'2025/2026,302.0,NaN,NaN,NaN,88.218523,8.35538,60.947382,84.365152,91.374867,94.346891,100.84599

====================================================================================================
DATASET: Total Households_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 8

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Total Households', 'Total Population', 'HH Density', 'Urban Households', 'Rural Households']

Data types:
Region               object
Time Frame           object
Unnamed: 2           object
Total Households     object
Total Population     object
HH Density          float64
Urban Households     object
Rural Households     object
dtype: object

Missing values:
Time Frame           1
Unnamed: 2          10
Total Households     1
Total Population     1
HH Density           1
Urban Households     1
Rural Households     1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Total Households,Total Population,HH Density,Urban Households,Rural Households
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,1 999 327,5 045 624,2.52,1 908 922,90 405
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,1 469 057,4 426 868,3.01,1 320 442,148 615
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,1 567 566,4 391 840,2.80,1 369 578,197 988
3,Emfuleni,April 2026,NaN,326 534,1 025 702,3.14,302 095,24 439
4,Lesedi,April 2026,NaN,47 233,144 504,3.06,39 418,7 815

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,11,11,City of Johannesburg Metropolitan Municipality,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,10,1,April 2026,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,"<b>Data Source:</b> <a style=""font-weight: bol...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Households,10,10,1 999 327,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Population,10,10,5 045 624,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HH Density,10.0,NaN,NaN,NaN,2.861,0.217432,2.51,2.785,2.87,3.04,3.14
Urban Households,10,10,1 908 922,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rural Households,10,10,90 405,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

====================================================================================================
DATASET: Microbiological _ Acute Health_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 8

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Risk Type', 'Analysis Done', 'Analysis Failed', 'Compliance Percentage', 'Compliance Result']

Data types:
Region                    object
Time Frame                object
Unnamed: 2                object
Risk Type                 object
Analysis Done             object
Analysis Failed          float64
Compliance Percentage    float64
Compliance Result         object
dtype: object

Missing values:
Time Frame                1
Unnamed: 2               10
Risk Type                 1
Analysis Done             1
Analysis Failed           1
Compliance Percentage     1
Compliance Result         1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Risk Type,Analysis Done,Analysis Failed,Compliance Percentage,Compliance Result
0,City of Johannesburg Metropolitan Municipality,2 026,NaN,Microbiological : Acute Health,1 159,13.0,98.88,Good
1,City of Tshwane Metropolitan Municipality,2 026,NaN,Microbiological : Acute Health,377,59.0,84.35,Bad
2,Ekurhuleni Metropolitan Municipality,2 026,NaN,Microbiological : Acute Health,819,9.0,98.90,Good
3,Emfuleni,2 026,NaN,Microbiological : Acute Health,0,0.0,0.00,Bad
4,Lesedi,2 026,NaN,Microbiological : Acute Health,54,0.0,100.00,Excellent

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,11,11,City of Johannesburg Metropolitan Municipality,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,10,1,2 026,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,"<b>Data Source:</b> <a style=""font-weight: bol...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Risk Type,10,1,Microbiological : Acute Health,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Analysis Done,10,9,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Analysis Failed,10.0,NaN,NaN,NaN,21.6,35.450121,0.0,0.25,5.5,21.25,108.0
Compliance Percentage,10.0,NaN,NaN,NaN,76.83,40.751744,0.0,86.5275,97.08,98.895,100.0
Compliance Result,10,4,Good,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

====================================================================================================
DATASET: Source of Water Households _ 2026_04_21
====================================================================================================
Rows: 10
Columns: 13

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Regional/local water scheme (operated by municipality or other w', 'Borehole', 'Spring', 'Rain water tank', 'Dam/pool/stagnant water', 'River/stream', 'Water vendor', 'Water tanker', 'Other', 'Not applicable']

Data types:
Region                                                               object
Time Frame                                                           object
Unnamed: 2                                                           object
Regional/local water scheme (operated by municipality or other w     object
Borehole                                                             object
Spring                                                               object
Rain water tank                                                      object
Dam/pool/stagnant water                                              object
River/stream                                                         object
Water vendor                                                         object
Water tanker                                                         object
Other                                                                object
Not applicable                                                      float64
dtype: object

Missing values:
Time Frame                                                          1
Unnamed: 2                                                          9
Regional/local water scheme (operated by municipality or other w    1
Borehole                                                            1
Spring                                                              1
Rain water tank                                                     1
Dam/pool/stagnant water                                             1
River/stream                                                        1
Water vendor                                                        1
Water tanker                                                        1
Other                                                               1
Not applicable                                                      1
dtype: int64

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Regional/local water scheme (operated by municipality or other w,Borehole,Spring,Rain water tank,Dam/pool/stagnant water,River/stream,Water vendor,Water tanker,Other,Not applicable
0,City of Johannesburg Metropolitan Municipality,Oct 2011,NaN,1 371 966,14 478,1 215,1 556,1 531,424,5 592,20 887,15 833,0.0
1,City of Tshwane Metropolitan Municipality,Oct 2011,NaN,825 746,25 730,1 231,1 426,2 409,550,5 615,30 864,16 983,0.0
2,Ekurhuleni Metropolitan Municipality,Oct 2011,NaN,972 647,10 997,985,1 065,923,253,3 703,9 247,14 629,0.0
3,Emfuleni,Oct 2011,NaN,211 967,3 781,98,395,225,90,619,425,2 295,0.0
4,Lesedi,Oct 2011,NaN,26 377,2 495,68,55,98,28,40,193,279,0.0

Numerical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Region,10,10,City of Johannesburg Metropolitan Municipality,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Frame,9,1,Oct 2011,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,1,1,"<b>Data Source:</b> <a style=""font-weight: bol...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Regional/local water scheme (operated by municipality or other w,9,9,1 371 966,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Borehole,9,9,14 478,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Spring,9,9,1 215,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rain water tank,9,9,1 556,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dam/pool/stagnant water,9,9,1 531,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
River/stream,9,9,424,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Water vendor,9,9,5 592,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Water tanker,9,9,20 887,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Other,9,9,15 833,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Not applicable,9.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# ============================================
# CELL 5: COLUMN-LEVEL DATA AUDIT
# ============================================

column_audit = []

for name, df in datasets.items():

    for col in df.columns:

        column_audit.append({
            "Dataset": name,
            "Column": col,
            "Data Type": str(df[col].dtype),
            "Rows": len(df),
            "Missing": int(df[col].isnull().sum()),
            "Missing %": round(
                df[col].isnull().mean() * 100,
                2
            ),
            "Unique Values": int(df[col].nunique(dropna=True)),
            "Duplicate Values": int(
                df[col].duplicated().sum()
            )
        })

column_audit_df = pd.DataFrame(column_audit)

display(column_audit_df)

,Dataset,Column,Data Type,Rows,Missing,Missing %,Unique Values,Duplicate Values
0,Verified - River Flow ( National ),'Flow,object,7,0,0.0,7,0
1,Verified - River Flow ( National ),'Flow Level :,int64,7,0,0.0,7,0
2,NIWIS_WasteWaterQuality_16-Jul-2026,Unnamed: 0,float64,143,143,100.0,0,142
3,NIWIS_WasteWaterQuality_16-Jul-2026,WSA,object,143,0,0.0,143,0
4,NIWIS_WasteWaterQuality_16-Jul-2026,Chemical,object,143,0,0.0,62,81
...,...,...,...,...,...,...,...,...
308,Source of Water Households _ 2026_04_21,River/stream,object,10,1,10.0,9,0
309,Source of Water Households _ 2026_04_21,Water vendor,object,10,1,10.0,9,0
310,Source of Water Households _ 2026_04_21,Water tanker,object,10,1,10.0,9,0
311,Source of Water Households _ 2026_04_21,Other,object,10,1,10.0,9,0
312,Source of Water Households _ 2026_04_21,Not applicable,float64,10,1,10.0,1,8

In [ ]:
# ============================================
# CELL 6: MISSING VALUE ANALYSIS
# ============================================

missing_columns = column_audit_df[
    column_audit_df["Missing"] > 0
].copy()

print(
    f"Number of columns containing missing values: "
    f"{len(missing_columns)}"
)

display(missing_columns)

Number of columns containing missing values: 259

,Dataset,Column,Data Type,Rows,Missing,Missing %,Unique Values,Duplicate Values
2,NIWIS_WasteWaterQuality_16-Jul-2026,Unnamed: 0,float64,143,143,100.00,0,142
9,Potable Systems_ 2026_04_21,Time Frame,object,61,1,1.64,1,59
10,Potable Systems_ 2026_04_21,Unnamed: 2,object,61,60,98.36,1,59
11,Potable Systems_ 2026_04_21,System name,object,61,1,1.64,30,30
12,Potable Systems_ 2026_04_21,System area,object,61,1,1.64,30,30
...,...,...,...,...,...,...,...,...
308,Source of Water Households _ 2026_04_21,River/stream,object,10,1,10.00,9,0
309,Source of Water Households _ 2026_04_21,Water vendor,object,10,1,10.00,9,0
310,Source of Water Households _ 2026_04_21,Water tanker,object,10,1,10.00,9,0
311,Source of Water Households _ 2026_04_21,Other,object,10,1,10.00,9,0
312,Source of Water Households _ 2026_04_21,Not applicable,float64,10,1,10.00,1,8

In [ ]:
# ============================================
# CELL 7: MISSING VALUES BY DATASET
# ============================================

missing_summary = (
    overview_df[
        ["Dataset", "Rows", "Columns", "Missing Values"]
    ]
    .sort_values(
        by="Missing Values",
        ascending=False
    )
)

display(missing_summary)

,Dataset,Rows,Columns,Missing Values
9,Weather,21301,14,38846
18,NIWIS_GroundwaterStatus_16-Jul-2026,1947,8,2511
3,Surface Water Storage (2014-2020),374,9,1971
23,Surface Water Storage ( 2020 -2026),375,9,1953
8,NIWIS_Water Supply Reliability - population_16...,144,14,189
1,NIWIS_WasteWaterQuality_16-Jul-2026,143,6,143
2,Potable Systems_ 2026_04_21,61,11,69
10,Timeseries Households_ 2026_04_21,11,35,43
4,TimeSeries Population_ 2026_04_21,11,35,43
15,Areas of Highest Vulnerability_ 2026_04_21,11,21,29
13,People Served with Water_ 2026_04_21,11,17,25
20,Households Served with Water_ 2026_04_21,11,17,25
12,Protests Identified by Municipal IQ_ 2026_04_21,11,16,24
26,Source of Water Households _ 2026_04_21,10,13,20
7,Piped Water Households _ 2026_04_21,10,12,19
16,Water demand growth_ 2026_04_21,11,10,18
5,Vulnerability Score Per leg_ 2026_04_21,11,9,17
25,Microbiological _ Acute Health_ 2026_04_21,11,8,16
6,Operational_ 2026_04_21,11,8,16
17,Total Population_ 2026_04_21,11,8,16
24,Total Households_ 2026_04_21,11,8,16
19,Residential Tariffs_ 2026_04_21,11,7,15
22,Institutional Compliance_ 2026_04_21,11,5,13
0,Verified - River Flow ( National ),7,2,0
14,NIWIS_Access to Water Infrastructure Delivered...,0,4,0
11,NIWIS_RWT_16-Jul-2026,9,5,0
21,Drinking Water Quality Compliance - SANS 241 _...,4,2,0

In [ ]:
# ============================================
# CELL 8: DUPLICATE ANALYSIS
# ============================================

duplicate_summary = (
    overview_df[
        ["Dataset", "Rows", "Duplicate Rows"]
    ]
    .sort_values(
        by="Duplicate Rows",
        ascending=False
    )
)

display(duplicate_summary)

                                              Dataset   Rows  Duplicate Rows
18               NIWIS_GroundwaterStatus_16-Jul-2026    1947               1
1                NIWIS_WasteWaterQuality_16-Jul-2026     143               0
0                  Verified - River Flow ( National )      7               0
3                   Surface Water Storage (2014-2020)    374               0
4                   TimeSeries Population_ 2026_04_21     11               0
5             Vulnerability Score Per leg_ 2026_04_21     11               0
6                             Operational_ 2026_04_21     11               0
7                 Piped Water Households _ 2026_04_21     10               0
8   NIWIS_Water Supply Reliability - population_16...    144               0
9                                             Weather  21301               0
2                         Potable Systems_ 2026_04_21     61               0
10                  Timeseries Households_ 2026_04_21     11               0
11                             NIWIS_RWT_16-Jul-2026       9               0
13               People Served with Water_ 2026_04_21     11               0
12    Protests Identified by Municipal IQ_ 2026_04_21     11               0
14  NIWIS_Access to Water Infrastructure Delivered...      0               0
15         Areas of Highest Vulnerability_ 2026_04_21     11               0
16                    Water demand growth_ 2026_04_21     11               0
17                       Total Population_ 2026_04_21     11               0
19                    Residential Tariffs_ 2026_04_21     11               0
20           Households Served with Water_ 2026_04_21     11               0
21  Drinking Water Quality Compliance - SANS 241 _...      4               0
22               Institutional Compliance_ 2026_04_21     11               0
23                Surface Water Storage ( 2020 -2026)    375               0
24                       Total Households_ 2026_04_21     11               0
25         Microbiological _ Acute Health_ 2026_04_21     11               0
26            Source of Water Households _ 2026_04_21     10               0

In [ ]:
# ============================================
# CELL 9: DISPLAY DUPLICATE ROWS
# ============================================

for name, df in datasets.items():

    duplicate_rows = df[df.duplicated(keep=False)]

    if not duplicate_rows.empty:

        print("\n")
        print("=" * 100)
        print(f"DUPLICATES FOUND: {name}")
        print("=" * 100)

        print(
            f"Number of duplicate rows: "
            f"{len(duplicate_rows)}"
        )

        display(duplicate_rows.head(20))

====================================================================================================
DUPLICATES FOUND: NIWIS_GroundwaterStatus_16-Jul-2026
====================================================================================================
Number of duplicate rows: 2

,Quaternary,Reserve Study,Available (GRA2)(m3/a),Recharge (GWR)(m3/a),Reserve (GWR)(m3/a),Abstracted (WARMS)(m3/a),Surplus (GRA2)(m3/a),Surplus (GWR)(m3/a)
195,H70K,0,335 546,NaN,NaN,74 073,261 473,NaN
196,H70K,0,335 546,NaN,NaN,74 073,261 473,NaN

In [ ]:
# ============================================
# CELL 10: IDENTIFY DATE/YEAR COLUMNS
# ============================================

date_columns = []

for name, df in datasets.items():

    for col in df.columns:

        col_lower = str(col).lower()

        if (
            "date" in col_lower
            or "year" in col_lower
            or "time" in col_lower
            or "month" in col_lower
        ):

            date_columns.append({
                "Dataset": name,
                "Column": col,
                "Data Type": str(df[col].dtype),
                "Example Values": df[col]
                    .dropna()
                    .astype(str)
                    .head(5)
                    .tolist()
            })

date_columns_df = pd.DataFrame(date_columns)

display(date_columns_df)

,Dataset,Column,Data Type,Example Values
0,Potable Systems_ 2026_04_21,Time Frame,object,"[April 2022, April 2022, April 2022, April 202..."
1,Surface Water Storage (2014-2020),'DateTime,object,"['2014-10-01 00:00:00, '2014-10-08 00:00:00, '..."
2,TimeSeries Population_ 2026_04_21,Time Frame,object,"[April 2026, April 2026, April 2026, April 202..."
3,Vulnerability Score Per leg_ 2026_04_21,Time Frame,object,"[2 018, 2 018, 2 018, 2 018, 2 018]"
4,Operational_ 2026_04_21,Time Frame,object,"[2 026, 2 026, 2 026, 2 026, 2 026]"
5,Piped Water Households _ 2026_04_21,Time Frame,object,"[Oct 2011, Oct 2011, Oct 2011, Oct 2011, Oct 2..."
6,Weather,DATE,object,"[2000-01-01, 2000-01-02, 2000-01-03, 2000-01-0..."
7,Timeseries Households_ 2026_04_21,Time Frame,object,"[April 2026, April 2026, April 2026, April 202..."
8,NIWIS_RWT_16-Jul-2026,Date,int64,"[2025, 2025, 2025, 2025, 2025]"
9,Protests Identified by Municipal IQ_ 2026_04_21,Time Frame,object,"[2 018, 2 018, 2 018, 2 018, 2 018]"
10,People Served with Water_ 2026_04_21,Time Frame,object,"[April 2026, April 2026, April 2026, April 202..."
11,Areas of Highest Vulnerability_ 2026_04_21,Time Frame,object,"[2 018, 2 018, 2 018, 2 018, 2 018]"
12,Water demand growth_ 2026_04_21,Time Frame,object,"[2 018, 2 018, 2 018, 2 018, 2 018]"
13,Total Population_ 2026_04_21,Time Frame,object,"[April 2026, April 2026, April 2026, April 202..."
14,Residential Tariffs_ 2026_04_21,Time Frame,object,"[2 018, 2 018, 2 018, 2 018, 2 018]"
15,Households Served with Water_ 2026_04_21,Time Frame,object,"[April 2026, April 2026, April 2026, April 202..."
16,Institutional Compliance_ 2026_04_21,Time Frame,object,"[April 2022, April 2022, April 2022, April 202..."
17,Surface Water Storage ( 2020 -2026),'DateTime,object,"['2020-10-01 00:00:00, '2020-10-08 00:00:00, '..."
18,Total Households_ 2026_04_21,Time Frame,object,"[April 2026, April 2026, April 2026, April 202..."
19,Microbiological _ Acute Health_ 2026_04_21,Time Frame,object,"[2 026, 2 026, 2 026, 2 026, 2 026]"
20,Source of Water Households _ 2026_04_21,Time Frame,object,"[Oct 2011, Oct 2011, Oct 2011, Oct 2011, Oct 2..."

In [ ]:
# ============================================
# CELL 11: IDENTIFY LOCATION COLUMNS
# ============================================

location_columns = []

location_keywords = [
    "region",
    "municipality",
    "province",
    "district",
    "city",
    "location",
    "area"
]

for name, df in datasets.items():

    for col in df.columns:

        col_lower = str(col).lower()

        if any(
            keyword in col_lower
            for keyword in location_keywords
        ):

            location_columns.append({
                "Dataset": name,
                "Column": col,
                "Unique Values": df[col].nunique(
                    dropna=True
                ),
                "Example Values": df[col]
                    .dropna()
                    .astype(str)
                    .unique()[:5]
                    .tolist()
            })

location_columns_df = pd.DataFrame(
    location_columns
)

display(location_columns_df)

,Dataset,Column,Unique Values,Example Values
0,Potable Systems_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
1,Potable Systems_ 2026_04_21,System area,30,"[Alexandra,East Bank ,Tsutsumani ,Bultfontein ..."
2,TimeSeries Population_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
3,Vulnerability Score Per leg_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
4,Vulnerability Score Per leg_ 2026_04_21,4# Technical Staff Capacity (Numbers),8,"[79.0, 20.0, 80.0, 15.0, 69.0]"
5,Operational_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
6,Piped Water Households _ 2026_04_21,Region,10,[City of Johannesburg Metropolitan Municipalit...
7,Timeseries Households_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
8,Protests Identified by Municipal IQ_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
9,Protests Identified by Municipal IQ_ 2026_04_21,Electricity,8,"[76.0, 29.0, 31.0, 1.0, 2.0]"
10,People Served with Water_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
11,Areas of Highest Vulnerability_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
12,Areas of Highest Vulnerability_ 2026_04_21,4# Technical Staff Capacity (Numbers),4,"[Low, Extreme, Moderate, High]"
13,Water demand growth_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
14,Total Population_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
15,Residential Tariffs_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
16,Households Served with Water_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
17,Institutional Compliance_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
18,Total Households_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
19,Microbiological _ Acute Health_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
20,Source of Water Households _ 2026_04_21,Region,10,[City of Johannesburg Metropolitan Municipalit...
21,Source of Water Households _ 2026_04_21,Regional/local water scheme (operated by munic...,9,"[1 371 966, 825 746, 972 647, 211 967, 26 377]"

In [ ]:
# ============================================
# CELL 12: NUMERICAL VARIABLES
# ============================================

numeric_summary = []

for name, df in datasets.items():

    numeric_cols = df.select_dtypes(
        include=np.number
    ).columns

    for col in numeric_cols:

        numeric_summary.append({
            "Dataset": name,
            "Column": col,
            "Min": df[col].min(),
            "Max": df[col].max(),
            "Mean": df[col].mean(),
            "Median": df[col].median(),
            "Std": df[col].std(),
            "Missing": df[col].isnull().sum()
        })

numeric_summary_df = pd.DataFrame(
    numeric_summary
)

display(numeric_summary_df)

,Dataset,Column,Min,Max,Mean,Median,Std,Missing
0,Verified - River Flow ( National ),'Flow Level :,30.000000,243.00000,76.857143,54.000000,74.445570,0
1,NIWIS_WasteWaterQuality_16-Jul-2026,Unnamed: 0,NaN,NaN,NaN,NaN,NaN,143
2,Potable Systems_ 2026_04_21,Drinking Water Quality Percentage,0.000000,100.00000,90.268000,99.895000,26.286442,1
3,Potable Systems_ 2026_04_21,Latest Blue Drop Score,42.300000,98.10000,77.852667,86.515000,17.270366,1
4,Surface Water Storage (2014-2020),'High,90.990000,98.70000,95.099167,94.245000,2.235766,302
...,...,...,...,...,...,...,...,...
65,Surface Water Storage ( 2020 -2026),'2025/2026,60.947382,100.84599,88.218523,91.374867,8.355380,73
66,Total Households_ 2026_04_21,HH Density,2.510000,3.14000,2.861000,2.870000,0.217432,1
67,Microbiological _ Acute Health_ 2026_04_21,Analysis Failed,0.000000,108.00000,21.600000,5.500000,35.450121,1
68,Microbiological _ Acute Health_ 2026_04_21,Compliance Percentage,0.000000,100.00000,76.830000,97.080000,40.751744,1
69,Source of Water Households _ 2026_04_21,Not applicable,0.000000,0.00000,0.000000,0.000000,0.000000,1

In [ ]:
# ============================================
# CELL 13: OUTLIER AUDIT USING IQR
# ============================================

outlier_summary = []

for name, df in datasets.items():

    numeric_cols = df.select_dtypes(
        include=np.number
    ).columns

    for col in numeric_cols:

        series = df[col].dropna()

        if len(series) < 4:
            continue

        Q1 = series.quantile(0.25)
        Q3 = series.quantile(0.75)

        IQR = Q3 - Q1

        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        outliers = (
            (series < lower_bound)
            |
            (series > upper_bound)
        )

        outlier_summary.append({
            "Dataset": name,
            "Column": col,
            "Q1": Q1,
            "Q3": Q3,
            "IQR": IQR,
            "Lower Bound": lower_bound,
            "Upper Bound": upper_bound,
            "Outlier Count": int(outliers.sum()),
            "Outlier %": round(
                outliers.mean() * 100,
                2
            )
        })

outlier_df = pd.DataFrame(outlier_summary)

display(
    outlier_df.sort_values(
        "Outlier Count",
        ascending=False
    )
)

,Dataset,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count,Outlier %
24,Weather,PRCP,0.000000,4.300000,4.300000,-6.450000,10.750000,1028,12.82
26,Weather,TMAX,22.000000,28.700000,6.700000,11.950000,38.750000,49,0.25
25,Weather,TAVG,14.300000,20.900000,6.600000,4.400000,30.800000,40,0.19
63,Surface Water Storage ( 2020 -2026),'2025/2026,84.365152,94.346891,9.981739,69.392543,109.319499,14,4.64
1,Potable Systems_ 2026_04_21,Drinking Water Quality Percentage,98.390000,100.000000,1.610000,95.975000,102.415000,8,13.33
...,...,...,...,...,...,...,...,...,...
60,Surface Water Storage ( 2020 -2026),'Low,63.657500,73.497500,9.840000,48.897500,88.257500,0,0.00
62,Surface Water Storage ( 2020 -2026),'2024/2025,76.524777,93.298052,16.773275,51.364864,118.457965,0,0.00
61,Surface Water Storage ( 2020 -2026),'Very Low,58.785500,67.150000,8.364500,46.238750,79.696750,0,0.00
64,Total Households_ 2026_04_21,HH Density,2.785000,3.040000,0.255000,2.402500,3.422500,0,0.00
67,Source of Water Households _ 2026_04_21,Not applicable,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.00

In [ ]:
# ============================================
# CELL 14: MASTER AUDIT REPORT
# ============================================

audit_report = overview_df.copy()

audit_report["Missing %"] = (
    audit_report["Missing Values"]
    / audit_report["Rows"]
    * 100
).round(2)

audit_report["Duplicate %"] = (
    audit_report["Duplicate Rows"]
    / audit_report["Rows"]
    * 100
).round(2)

display(audit_report)

,Dataset,Rows,Columns,Missing Values,Duplicate Rows,Numeric Columns,Categorical Columns,Memory (MB),Missing %,Duplicate %
0,Verified - River Flow ( National ),7,2,0,0,1,1,0.00,0.00,0.00
1,NIWIS_WasteWaterQuality_16-Jul-2026,143,6,143,0,1,5,0.04,100.00,0.00
2,Potable Systems_ 2026_04_21,61,11,69,0,2,9,0.04,113.11,0.00
3,Surface Water Storage (2014-2020),374,9,1971,0,8,1,0.05,527.01,0.00
4,TimeSeries Population_ 2026_04_21,11,35,43,0,0,35,0.03,390.91,0.00
5,Vulnerability Score Per leg_ 2026_04_21,11,9,17,0,6,3,0.00,154.55,0.00
6,Operational_ 2026_04_21,11,8,16,0,2,6,0.00,145.45,0.00
7,Piped Water Households _ 2026_04_21,10,12,19,0,2,10,0.01,190.00,0.00
8,NIWIS_Water Supply Reliability - population_16...,144,14,189,0,1,13,0.10,131.25,0.00
9,Weather,21301,14,38846,0,7,7,8.86,182.37,0.00
10,Timeseries Households_ 2026_04_21,11,35,43,0,0,35,0.03,390.91,0.00
11,NIWIS_RWT_16-Jul-2026,9,5,0,0,4,1,0.00,0.00,0.00
12,Protests Identified by Municipal IQ_ 2026_04_21,11,16,24,0,13,3,0.00,218.18,0.00
13,People Served with Water_ 2026_04_21,11,17,25,0,1,16,0.01,227.27,0.00
14,NIWIS_Access to Water Infrastructure Delivered...,0,4,0,0,0,4,0.00,NaN,NaN
15,Areas of Highest Vulnerability_ 2026_04_21,11,21,29,0,0,21,0.01,263.64,0.00
16,Water demand growth_ 2026_04_21,11,10,18,0,3,7,0.01,163.64,0.00
17,Total Population_ 2026_04_21,11,8,16,0,1,7,0.01,145.45,0.00
18,NIWIS_GroundwaterStatus_16-Jul-2026,1947,8,2511,1,1,7,0.69,128.97,0.05
19,Residential Tariffs_ 2026_04_21,11,7,15,0,0,7,0.00,136.36,0.00
20,Households Served with Water_ 2026_04_21,11,17,25,0,2,15,0.01,227.27,0.00
21,Drinking Water Quality Compliance - SANS 241 _...,4,2,0,0,1,1,0.00,0.00,0.00
22,Institutional Compliance_ 2026_04_21,11,5,13,0,2,3,0.01,118.18,0.00
23,Surface Water Storage ( 2020 -2026),375,9,1953,0,8,1,0.05,520.80,0.00
24,Total Households_ 2026_04_21,11,8,16,0,1,7,0.01,145.45,0.00
25,Microbiological _ Acute Health_ 2026_04_21,11,8,16,0,2,6,0.00,145.45,0.00
26,Source of Water Households _ 2026_04_21,10,13,20,0,1,12,0.01,200.00,0.00

In [ ]:
# ============================================
# CELL 15: SAVE AUDIT RESULTS
# ============================================

audit_dir = "Outputs/DataAudit"

os.makedirs(
    audit_dir,
    exist_ok=True
)

overview_df.to_csv(
    os.path.join(
        audit_dir,
        "dataset_overview.csv"
    ),
    index=False
)

column_audit_df.to_csv(
    os.path.join(
        audit_dir,
        "column_audit.csv"
    ),
    index=False
)

missing_columns.to_csv(
    os.path.join(
        audit_dir,
        "missing_columns.csv"
    ),
    index=False
)

duplicate_summary.to_csv(
    os.path.join(
        audit_dir,
        "duplicate_summary.csv"
    ),
    index=False
)

numeric_summary_df.to_csv(
    os.path.join(
        audit_dir,
        "numeric_summary.csv"
    ),
    index=False
)

outlier_df.to_csv(
    os.path.join(
        audit_dir,
        "outlier_summary.csv"
    ),
    index=False
)

print("Data audit reports saved successfully.")
print(f"Location: {audit_dir}")

Data audit reports saved successfully.
Location: Outputs/DataAudit

Notebook 2

In [ ]:
import pandas as pd
import numpy as np from scipy.stats
import zscore import os, glob,
warnings warnings.filterwarnings("ignore")

SyntaxError: invalid syntax (830179280.py, line 2)

In [ ]:
csv_files = glob.glob("/content/ANLOK-WATER-PREDICTION-PROJECT-/**/*.csv", recursive=True)
datasets = {}
for file in csv_files:
  name = os.path.splitext(os.path.basename(file))[0]
  try: datasets[name] = pd.read_csv(file)
  except Exception as e: continue
  print("Datasets to clean:", list(datasets.keys()))

Datasets to clean: ['Verified - River Flow ( National )']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21', 'Water demand growth_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21', 'Water demand growth_ 2026_04_21', 'Total Population_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21', 'Water demand growth_ 2026_04_21', 'Total Population_ 2026_04_21', 'NIWIS_GroundwaterStatus_16-Jul-2026 ']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21', 'Water demand growth_ 2026_04_21', 'Total Population_ 2026_04_21', 'NIWIS_GroundwaterStatus_16-Jul-2026 ', 'Residential Tariffs_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21', 'Water demand growth_ 2026_04_21', 'Total Population_ 2026_04_21', 'NIWIS_GroundwaterStatus_16-Jul-2026 ', 'Residential Tariffs_ 2026_04_21', 'Households Served with Water_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21', 'Water demand growth_ 2026_04_21', 'Total Population_ 2026_04_21', 'NIWIS_GroundwaterStatus_16-Jul-2026 ', 'Residential Tariffs_ 2026_04_21', 'Households Served with Water_ 2026_04_21', 'Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21', 'Water demand growth_ 2026_04_21', 'Total Population_ 2026_04_21', 'NIWIS_GroundwaterStatus_16-Jul-2026 ', 'Residential Tariffs_ 2026_04_21', 'Households Served with Water_ 2026_04_21', 'Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]', 'Institutional Compliance_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21', 'Water demand growth_ 2026_04_21', 'Total Population_ 2026_04_21', 'NIWIS_GroundwaterStatus_16-Jul-2026 ', 'Residential Tariffs_ 2026_04_21', 'Households Served with Water_ 2026_04_21', 'Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]', 'Institutional Compliance_ 2026_04_21', 'Surface Water Storage ( 2020 -2026)']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21', 'Water demand growth_ 2026_04_21', 'Total Population_ 2026_04_21', 'NIWIS_GroundwaterStatus_16-Jul-2026 ', 'Residential Tariffs_ 2026_04_21', 'Households Served with Water_ 2026_04_21', 'Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]', 'Institutional Compliance_ 2026_04_21', 'Surface Water Storage ( 2020 -2026)', 'Total Households_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21', 'Water demand growth_ 2026_04_21', 'Total Population_ 2026_04_21', 'NIWIS_GroundwaterStatus_16-Jul-2026 ', 'Residential Tariffs_ 2026_04_21', 'Households Served with Water_ 2026_04_21', 'Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]', 'Institutional Compliance_ 2026_04_21', 'Surface Water Storage ( 2020 -2026)', 'Total Households_ 2026_04_21', 'Microbiological _ Acute Health_ 2026_04_21']
Datasets to clean: ['Verified - River Flow ( National )', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Potable Systems_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'TimeSeries Population_ 2026_04_21', 'Vulnerability Score Per leg_ 2026_04_21', 'Operational_ 2026_04_21', 'Piped Water Households _ 2026_04_21', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Weather', 'Timeseries Households_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Protests Identified by Municipal IQ_ 2026_04_21', 'People Served with Water_ 2026_04_21', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'Areas of Highest Vulnerability_ 2026_04_21', 'Water demand growth_ 2026_04_21', 'Total Population_ 2026_04_21', 'NIWIS_GroundwaterStatus_16-Jul-2026 ', 'Residential Tariffs_ 2026_04_21', 'Households Served with Water_ 2026_04_21', 'Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]', 'Institutional Compliance_ 2026_04_21', 'Surface Water Storage ( 2020 -2026)', 'Total Households_ 2026_04_21', 'Microbiological _ Acute Health_ 2026_04_21', 'Source of Water Households _ 2026_04_21']

In [ ]:
def clean_dataframe(df):
  df = df.copy()
  # Drop exact duplicate rows
  before = df.shape[0]
  df = df.drop_duplicates()
  after = df.shape[0]
  print(f"Dropped {before-after} duplicates")
  # Standardize column names: strip, lower-case, replace spaces with underscores
  df.columns = df.columns.str.strip().str.lower().str.replace(r'\s+', '_', regex=True)
  # Drop completely empty rows/columns
  df = df.dropna(axis=0, how='all').dropna(axis=1, how='all')
  # Strip whitespace from string entries
  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()
  return df

In [ ]:
cleaned = {}
for name, df in datasets.items():
  print(f"\nCleaning {name}:")
  df_clean = clean_dataframe(df)
  cleaned[name] = df_clean

Cleaning Verified - River Flow ( National ):
Dropped 0 duplicates

Cleaning NIWIS_WasteWaterQuality_16-Jul-2026 :
Dropped 0 duplicates

Cleaning Potable Systems_ 2026_04_21:
Dropped 0 duplicates

Cleaning Surface Water Storage (2014-2020):
Dropped 0 duplicates

Cleaning TimeSeries Population_ 2026_04_21:
Dropped 0 duplicates

Cleaning Vulnerability Score Per leg_ 2026_04_21:
Dropped 0 duplicates

Cleaning Operational_ 2026_04_21:
Dropped 0 duplicates

Cleaning Piped Water Households _ 2026_04_21:
Dropped 0 duplicates

Cleaning NIWIS_Water Supply Reliability - population_16-Jul-2026 :
Dropped 0 duplicates

Cleaning Weather:
Dropped 0 duplicates

Cleaning Timeseries Households_ 2026_04_21:
Dropped 0 duplicates

Cleaning NIWIS_RWT_16-Jul-2026 :
Dropped 0 duplicates

Cleaning Protests Identified by Municipal IQ_ 2026_04_21:
Dropped 0 duplicates

Cleaning People Served with Water_ 2026_04_21:
Dropped 0 duplicates

Cleaning NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 :
Dropped 0 duplicates

Cleaning Areas of Highest Vulnerability_ 2026_04_21:
Dropped 0 duplicates

Cleaning Water demand growth_ 2026_04_21:
Dropped 0 duplicates

Cleaning Total Population_ 2026_04_21:
Dropped 0 duplicates

Cleaning NIWIS_GroundwaterStatus_16-Jul-2026 :
Dropped 1 duplicates

Cleaning Residential Tariffs_ 2026_04_21:
Dropped 0 duplicates

Cleaning Households Served with Water_ 2026_04_21:
Dropped 0 duplicates

Cleaning Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]:
Dropped 0 duplicates

Cleaning Institutional Compliance_ 2026_04_21:
Dropped 0 duplicates

Cleaning Surface Water Storage ( 2020 -2026):
Dropped 0 duplicates

Cleaning Total Households_ 2026_04_21:
Dropped 0 duplicates

Cleaning Microbiological _ Acute Health_ 2026_04_21:
Dropped 0 duplicates

Cleaning Source of Water Households _ 2026_04_21:
Dropped 0 duplicates

In [ ]:
for name, df in cleaned.items():
  # Example: Convert date columns to datetime if any
  for col in df.columns:
    if 'date' in col or 'year' in col:
      try:
        df[col] = pd.to_datetime(df[col])
        print(f"Converted {name}.{col} to datetime")
      except:
        pass

  # Impute or flag missing numerical values
  numeric_cols = df.select_dtypes(include=np.number).columns
  if len(numeric_cols) > 0:
    imputer = SimpleImputer(strategy='mean')
    df[numeric_cols] = imputer.fit_transform(df[numeric_cols])
    print(f"Imputed missing numeric values in {name}")

  # For categorical: fill missing with 'Unknown'
  cat_cols = df.select_dtypes(include='object').columns
  for col in cat_cols:
    df[col] = df[col].fillna('Unknown')

  cleaned[name] = df

Imputed missing numeric values in Verified - River Flow ( National )
Imputed missing numeric values in Potable Systems_ 2026_04_21
Converted Surface Water Storage (2014-2020).'datetime to datetime
Imputed missing numeric values in Surface Water Storage (2014-2020)
Imputed missing numeric values in Vulnerability Score Per leg_ 2026_04_21
Imputed missing numeric values in Operational_ 2026_04_21
Imputed missing numeric values in Piped Water Households _ 2026_04_21
Converted Weather.date to datetime
Imputed missing numeric values in Weather
Converted NIWIS_RWT_16-Jul-2026 .date to datetime
Imputed missing numeric values in NIWIS_RWT_16-Jul-2026
Imputed missing numeric values in Protests Identified by Municipal IQ_ 2026_04_21
Imputed missing numeric values in People Served with Water_ 2026_04_21
Imputed missing numeric values in Water demand growth_ 2026_04_21
Imputed missing numeric values in Total Population_ 2026_04_21
Imputed missing numeric values in NIWIS_GroundwaterStatus_16-Jul-2026
Imputed missing numeric values in Households Served with Water_ 2026_04_21
Imputed missing numeric values in Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]
Imputed missing numeric values in Institutional Compliance_ 2026_04_21
Converted Surface Water Storage ( 2020 -2026).'datetime to datetime
Imputed missing numeric values in Surface Water Storage ( 2020 -2026)
Imputed missing numeric values in Total Households_ 2026_04_21
Imputed missing numeric values in Microbiological _ Acute Health_ 2026_04_21
Imputed missing numeric values in Source of Water Households _ 2026_04_21

In [ ]:
for name, df in cleaned.items():
  numeric = df.select_dtypes(include=np.number)
  if not numeric.empty:
    z_scores = np.abs(zscore(numeric, nan_policy='omit'))
    outliers = (z_scores > 3).sum(axis=0)
    print(f"{name} outliers per column:\n{outliers}")
    # (Optional) Remove rows with any outlier in numeric columns:
    # df = df[(z_scores < 3).all(axis=1)]
    # cleaned[name] = df

Verified - River Flow ( National ) outliers per column:
[0]
Potable Systems_ 2026_04_21 outliers per column:
[4 0]
Surface Water Storage (2014-2020) outliers per column:
[18 16 12 17 17  8  0  0]
Vulnerability Score Per leg_ 2026_04_21 outliers per column:
[0 0 0 0 0 0]
Operational_ 2026_04_21 outliers per column:
[0 0]
Piped Water Households _ 2026_04_21 outliers per column:
[0 0]
Weather outliers per column:
[  0   0   0 334  33  51  46]
NIWIS_RWT_16-Jul-2026  outliers per column:
[0 0 0]
Protests Identified by Municipal IQ_ 2026_04_21 outliers per column:
[0 0 0 0 0 0 0 0 0 0 0 0 0]
People Served with Water_ 2026_04_21 outliers per column:
[0]
Water demand growth_ 2026_04_21 outliers per column:
[0 0 0]
Total Population_ 2026_04_21 outliers per column:
[0]
NIWIS_GroundwaterStatus_16-Jul-2026  outliers per column:
[0]
Households Served with Water_ 2026_04_21 outliers per column:
[0 0]
Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30] outliers per column:
[0]
Institutional Compliance_ 2026_04_21 outliers per column:
[0 0]
Surface Water Storage ( 2020 -2026) outliers per column:
[13 12 11 10 14 12  0 12]
Total Households_ 2026_04_21 outliers per column:
[0]
Microbiological _ Acute Health_ 2026_04_21 outliers per column:
[0 0]
Source of Water Households _ 2026_04_21 outliers per column:
[0]

In [ ]:
report = []
for name, df in cleaned.items():
  report.append({
      "Dataset": name,
      "Rows": len(df),
      "Columns": df.shape[1],
      "Missing": df.isnull().sum().sum(),
      "Duplicates": df.duplicated().sum()
  })
report_df = pd.DataFrame(report)
display(report_df)

,Dataset,Rows,Columns,Missing,Duplicates
0,Verified - River Flow ( National ),7,2,0.0,0
1,NIWIS_WasteWaterQuality_16-Jul-2026,143,5,0.0,0
2,Potable Systems_ 2026_04_21,61,11,0.0,0
3,Surface Water Storage (2014-2020),374,9,0.0,0
4,TimeSeries Population_ 2026_04_21,11,35,0.0,0
5,Vulnerability Score Per leg_ 2026_04_21,11,9,0.0,0
6,Operational_ 2026_04_21,11,8,0.0,0
7,Piped Water Households _ 2026_04_21,10,12,0.0,0
8,NIWIS_Water Supply Reliability - population_16...,144,13,0.0,0
9,Weather,21301,14,0.0,0
10,Timeseries Households_ 2026_04_21,11,35,0.0,0
11,NIWIS_RWT_16-Jul-2026,9,5,0.0,0
12,Protests Identified by Municipal IQ_ 2026_04_21,11,16,0.0,0
13,People Served with Water_ 2026_04_21,11,17,0.0,0
14,NIWIS_Access to Water Infrastructure Delivered...,0,0,0.0,0
15,Areas of Highest Vulnerability_ 2026_04_21,11,21,0.0,0
16,Water demand growth_ 2026_04_21,11,10,0.0,0
17,Total Population_ 2026_04_21,11,8,0.0,0
18,NIWIS_GroundwaterStatus_16-Jul-2026,1946,8,0.0,0
19,Residential Tariffs_ 2026_04_21,11,7,0.0,0
20,Households Served with Water_ 2026_04_21,11,17,0.0,0
21,Drinking Water Quality Compliance - SANS 241 _...,4,2,0.0,0
22,Institutional Compliance_ 2026_04_21,11,5,0.0,0
23,Surface Water Storage ( 2020 -2026),375,9,0.0,0
24,Total Households_ 2026_04_21,11,8,0.0,0
25,Microbiological _ Acute Health_ 2026_04_21,11,8,0.0,0
26,Source of Water Households _ 2026_04_21,10,13,0.0,0

In [ ]:
clean_dir = os.path.join("Outputs", "CleanData")
os.makedirs(clean_dir, exist_ok=True)

for name, df in cleaned.items():
  out_path = os.path.join(clean_dir, f"{name}_clean.csv")
  df.to_csv(out_path, index=False)
  print(f"Saved cleaned {name} ({df.shape}) to {out_path})")

# Each cleaned CSV is saved for future use (e.g. merged dataset)

Saved cleaned Verified - River Flow ( National ) ((7, 2)) to Outputs/CleanData/Verified - River Flow ( National )_clean.csv)
Saved cleaned NIWIS_WasteWaterQuality_16-Jul-2026  ((143, 5)) to Outputs/CleanData/NIWIS_WasteWaterQuality_16-Jul-2026 _clean.csv)
Saved cleaned Potable Systems_ 2026_04_21 ((61, 11)) to Outputs/CleanData/Potable Systems_ 2026_04_21_clean.csv)
Saved cleaned Surface Water Storage (2014-2020) ((374, 9)) to Outputs/CleanData/Surface Water Storage (2014-2020)_clean.csv)
Saved cleaned TimeSeries Population_ 2026_04_21 ((11, 35)) to Outputs/CleanData/TimeSeries Population_ 2026_04_21_clean.csv)
Saved cleaned Vulnerability Score Per leg_ 2026_04_21 ((11, 9)) to Outputs/CleanData/Vulnerability Score Per leg_ 2026_04_21_clean.csv)
Saved cleaned Operational_ 2026_04_21 ((11, 8)) to Outputs/CleanData/Operational_ 2026_04_21_clean.csv)
Saved cleaned Piped Water Households _ 2026_04_21 ((10, 12)) to Outputs/CleanData/Piped Water Households _ 2026_04_21_clean.csv)
Saved cleaned NIWIS_Water Supply Reliability - population_16-Jul-2026  ((144, 13)) to Outputs/CleanData/NIWIS_Water Supply Reliability - population_16-Jul-2026 _clean.csv)
Saved cleaned Weather ((21301, 14)) to Outputs/CleanData/Weather_clean.csv)
Saved cleaned Timeseries Households_ 2026_04_21 ((11, 35)) to Outputs/CleanData/Timeseries Households_ 2026_04_21_clean.csv)
Saved cleaned NIWIS_RWT_16-Jul-2026  ((9, 5)) to Outputs/CleanData/NIWIS_RWT_16-Jul-2026 _clean.csv)
Saved cleaned Protests Identified by Municipal IQ_ 2026_04_21 ((11, 16)) to Outputs/CleanData/Protests Identified by Municipal IQ_ 2026_04_21_clean.csv)
Saved cleaned People Served with Water_ 2026_04_21 ((11, 17)) to Outputs/CleanData/People Served with Water_ 2026_04_21_clean.csv)
Saved cleaned NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026  ((0, 0)) to Outputs/CleanData/NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 _clean.csv)
Saved cleaned Areas of Highest Vulnerability_ 2026_04_21 ((11, 21)) to Outputs/CleanData/Areas of Highest Vulnerability_ 2026_04_21_clean.csv)
Saved cleaned Water demand growth_ 2026_04_21 ((11, 10)) to Outputs/CleanData/Water demand growth_ 2026_04_21_clean.csv)
Saved cleaned Total Population_ 2026_04_21 ((11, 8)) to Outputs/CleanData/Total Population_ 2026_04_21_clean.csv)
Saved cleaned NIWIS_GroundwaterStatus_16-Jul-2026  ((1946, 8)) to Outputs/CleanData/NIWIS_GroundwaterStatus_16-Jul-2026 _clean.csv)
Saved cleaned Residential Tariffs_ 2026_04_21 ((11, 7)) to Outputs/CleanData/Residential Tariffs_ 2026_04_21_clean.csv)
Saved cleaned Households Served with Water_ 2026_04_21 ((11, 17)) to Outputs/CleanData/Households Served with Water_ 2026_04_21_clean.csv)
Saved cleaned Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30] ((4, 2)) to Outputs/CleanData/Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]_clean.csv)
Saved cleaned Institutional Compliance_ 2026_04_21 ((11, 5)) to Outputs/CleanData/Institutional Compliance_ 2026_04_21_clean.csv)
Saved cleaned Surface Water Storage ( 2020 -2026) ((375, 9)) to Outputs/CleanData/Surface Water Storage ( 2020 -2026)_clean.csv)
Saved cleaned Total Households_ 2026_04_21 ((11, 8)) to Outputs/CleanData/Total Households_ 2026_04_21_clean.csv)
Saved cleaned Microbiological _ Acute Health_ 2026_04_21 ((11, 8)) to Outputs/CleanData/Microbiological _ Acute Health_ 2026_04_21_clean.csv)
Saved cleaned Source of Water Households _ 2026_04_21 ((10, 13)) to Outputs/CleanData/Source of Water Households _ 2026_04_21_clean.csv)