<a href="https://colab.research.google.com/github/LulutheBA/ANLOK-WATER-PREDICTION-PROJECT-/blob/main/NB1_OP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 INSTALL REQUIRED PACKAGES

In [1]:
!pip install pandas numpy matplotlib plotly scikit-learn scipy xgboost shap >/dev/null

print("Required packages installed successfully.")

Required packages installed successfully.

MOUNT GOOGLE DRIVE

In [2]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

GITHUB AUTHENTICATION

In [3]:
from getpass import getpass

token = getpass(
    "Enter your GitHub Personal Access Token: "
)

github_user = "LulutheBA"

github_repo = "ANLOK-WATER-PREDICTION-PROJECT-"

print("GitHub credentials received securely.")

Enter your GitHub Personal Access Token: ··········
GitHub credentials received securely.

Clone Repository

In [4]:
import os

repo_path = f"/content/{github_repo}"

# Remove an existing copy if one exists
if os.path.exists(repo_path):
    !rm -rf "$repo_path"

# Clone repository
!git clone https://{token}@github.com/{github_user}/{github_repo}.git

print()
print("Repository cloned successfully.")
print(f"Repository location: {repo_path}")

Cloning into 'ANLOK-WATER-PREDICTION-PROJECT-'...
remote: Enumerating objects: 394, done.
remote: Counting objects: 100% (92/92), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 394 (delta 30), reused 2 (delta 2), pack-reused 302 (from 2)
Receiving objects: 100% (394/394), 6.22 MiB | 6.69 MiB/s, done.
Resolving deltas: 100% (178/178), done.

Repository cloned successfully.
Repository location: /content/ANLOK-WATER-PREDICTION-PROJECT-

VERIFY REPOSITORY

In [5]:
print("=" * 80)
print("REPOSITORY CONTENTS")
print("=" * 80)

if os.path.exists(repo_path):

    for item in os.listdir(repo_path):
        print(item)

else:

    print("Repository was not found.")

================================================================================
REPOSITORY CONTENTS
================================================================================
NB2_OP.ipynb
Notebooks
Copy_of_notebook_1&2.ipynb
README.md
.git
Training
Data
notebook_1.ipynb
Outputs

IMPORT LIBRARIES

In [6]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

from scipy.stats import zscore

import glob
import os
import warnings

from IPython.display import display

warnings.filterwarnings("ignore")

plt.rcParams["figure.figsize"] = (10, 6)

print("Libraries imported successfully.")

Libraries imported successfully.

LOCATE ALL CSV FILES

In [7]:
csv_files = glob.glob(
    os.path.join(
        repo_path,
        "**",
        "*.csv"
    ),
    recursive=True
)

print(
    f"Found {len(csv_files)} CSV files."
)

print()

for file in csv_files:
    print(file)

Found 28 CSV files.

/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/NIWIS_Water Supply Reliability - population_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Water demand growth_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Institutional Compliance_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Microbiological _ Acute Health_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30].csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Surface Water Storage ( 2020 -2026).csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Households Served with Water_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/NIWIS_GroundwaterStatus_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Surface Water Storage (2014-2020).csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/People Served with Water_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Areas of Highest Vulnerability_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Protests Identified by Municipal IQ_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Verified - River Flow ( National ).csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Weather.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Total Households_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Potable Systems_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Source of Water Households _ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Vulnerability Score Per leg_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Weather4355517.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Total Population_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/TimeSeries Population_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Piped Water Households _ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/NIWIS_WasteWaterQuality_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Operational_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/NIWIS_RWT_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Timeseries Households_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Data/Raw/Residential Tariffs_ 2026_04_21.csv

LOAD DATASETS

In [8]:
datasets = {}

for file in csv_files:

    name = os.path.splitext(
        os.path.basename(file)
    )[0]

    try:

        datasets[name] = pd.read_csv(file)

    except Exception as e:

        print(
            f"Skipping {name}: {e}"
        )

print(
    f"Successfully loaded "
    f"{len(datasets)} datasets."
)

print()

for name, df in datasets.items():

    print(
        f"{name}: {df.shape}"
    )

Skipping Weather4355517: No columns to parse from file
Successfully loaded 27 datasets.

NIWIS_Water Supply Reliability - population_16-Jul-2026 : (144, 14)
Water demand growth_ 2026_04_21: (11, 10)
NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 : (0, 4)
Institutional Compliance_ 2026_04_21: (11, 5)
Microbiological _ Acute Health_ 2026_04_21: (11, 8)
Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]: (4, 2)
Surface Water Storage ( 2020 -2026): (375, 9)
Households Served with Water_ 2026_04_21: (11, 17)
NIWIS_GroundwaterStatus_16-Jul-2026 : (1947, 8)
Surface Water Storage (2014-2020): (374, 9)
People Served with Water_ 2026_04_21: (11, 17)
Areas of Highest Vulnerability_ 2026_04_21: (11, 21)
Protests Identified by Municipal IQ_ 2026_04_21: (11, 16)
Verified - River Flow ( National ): (7, 2)
Weather: (21301, 14)
Total Households_ 2026_04_21: (11, 8)
Potable Systems_ 2026_04_21: (61, 11)
Source of Water Households _ 2026_04_21: (10, 13)
Vulnerability Score Per leg_ 2026_04_21: (11, 9)
Total Population_ 2026_04_21: (11, 8)
TimeSeries Population_ 2026_04_21: (11, 35)
Piped Water Households _ 2026_04_21: (10, 12)
NIWIS_WasteWaterQuality_16-Jul-2026 : (143, 6)
Operational_ 2026_04_21: (11, 8)
NIWIS_RWT_16-Jul-2026 : (9, 5)
Timeseries Households_ 2026_04_21: (11, 35)
Residential Tariffs_ 2026_04_21: (11, 7)

DATASET OVERVIEW

In [9]:
overview = []

for name, df in datasets.items():

    overview.append({

        "Dataset": name,

        "Rows": df.shape[0],

        "Columns": df.shape[1],

        "Memory (MB)": round(
            df.memory_usage(
                deep=True
            ).sum() / 1024**2,
            2
        ),

        "Missing Values": int(
            df.isnull().sum().sum()
        ),

        "Duplicate Rows": int(
            df.duplicated().sum()
        ),

        "Numeric Columns": len(
            df.select_dtypes(
                include=np.number
            ).columns
        ),

        "Categorical Columns": len(
            df.select_dtypes(
                exclude=np.number
            ).columns
        )
    })

overview_df = pd.DataFrame(
    overview
)

display(overview_df)

,Dataset,Rows,Columns,Memory (MB),Missing Values,Duplicate Rows,Numeric Columns,Categorical Columns
0,NIWIS_Water Supply Reliability - population_16...,144,14,0.10,189,0,1,13
1,Water demand growth_ 2026_04_21,11,10,0.01,18,0,3,7
2,NIWIS_Access to Water Infrastructure Delivered...,0,4,0.00,0,0,0,4
3,Institutional Compliance_ 2026_04_21,11,5,0.00,13,0,2,3
4,Microbiological _ Acute Health_ 2026_04_21,11,8,0.00,16,0,2,6
5,Drinking Water Quality Compliance - SANS 241 _...,4,2,0.00,0,0,1,1
6,Surface Water Storage ( 2020 -2026),375,9,0.05,1953,0,8,1
7,Households Served with Water_ 2026_04_21,11,17,0.01,25,0,2,15
8,NIWIS_GroundwaterStatus_16-Jul-2026,1947,8,0.69,2511,1,1,7
9,Surface Water Storage (2014-2020),374,9,0.05,1971,0,8,1
10,People Served with Water_ 2026_04_21,11,17,0.01,25,0,1,16
11,Areas of Highest Vulnerability_ 2026_04_21,11,21,0.01,29,0,0,21
12,Protests Identified by Municipal IQ_ 2026_04_21,11,16,0.00,24,0,13,3
13,Verified - River Flow ( National ),7,2,0.00,0,0,1,1
14,Weather,21301,14,8.86,38846,0,7,7
15,Total Households_ 2026_04_21,11,8,0.01,16,0,1,7
16,Potable Systems_ 2026_04_21,61,11,0.04,69,0,2,9
17,Source of Water Households _ 2026_04_21,10,13,0.01,20,0,1,12
18,Vulnerability Score Per leg_ 2026_04_21,11,9,0.00,17,0,6,3
19,Total Population_ 2026_04_21,11,8,0.01,16,0,1,7
20,TimeSeries Population_ 2026_04_21,11,35,0.03,43,0,0,35
21,Piped Water Households _ 2026_04_21,10,12,0.01,19,0,2,10
22,NIWIS_WasteWaterQuality_16-Jul-2026,143,6,0.04,143,0,1,5
23,Operational_ 2026_04_21,11,8,0.00,16,0,2,6
24,NIWIS_RWT_16-Jul-2026,9,5,0.00,0,0,4,1
25,Timeseries Households_ 2026_04_21,11,35,0.03,43,0,0,35
26,Residential Tariffs_ 2026_04_21,11,7,0.00,15,0,0,7

INSPECT EVERY DATASET

In [10]:
for name, df in datasets.items():

    print()
    print("=" * 100)
    print(f"DATASET: {name}")
    print("=" * 100)

    print(
        f"Rows: {df.shape[0]}"
    )

    print(
        f"Columns: {df.shape[1]}"
    )

    print("\nColumn names:")

    print(
        list(df.columns)
    )

    print("\nData types:")

    display(
        df.dtypes.to_frame(
            "Data Type"
        )
    )

    print("\nMissing values:")

    missing = df.isnull().sum()

    missing = missing[
        missing > 0
    ]

    if missing.empty:

        print(
            "No missing values."
        )

    else:

        display(
            missing.to_frame(
                "Missing Values"
            )
        )

    print("\nDuplicate rows:")

    print(
        df.duplicated().sum()
    )

    print("\nFirst 5 rows:")

    display(
        df.head()
    )

    print("\nNumerical summary:")

    numeric_cols = df.select_dtypes(
        include=np.number
    ).columns

    if len(numeric_cols) > 0:

        display(
            df[numeric_cols]
            .describe()
            .T
        )

    else:

        print(
            "No numerical columns."
        )

====================================================================================================
DATASET: NIWIS_Water Supply Reliability - population_16-Jul-2026
====================================================================================================
Rows: 144
Columns: 14

Column names:
['Unnamed: 0', 'WSA Name', 'population', 'population with access  to water', 'population Reliable Supply', '% population Reliable Supply', 'Urban population', 'Urban population with access to water', 'Urban population Reliable Supply', '% Urban population Reliable Supply', 'Rural population', 'Rural population  with access  to water', 'Rural population Reliable Supply', '% Rural population Reliable Supply']

Data types:

                                        Data Type
Unnamed: 0                                float64
WSA Name                                   object
population                                 object
population with access  to water           object
population Reliable Supply                 object
% population Reliable Supply               object
Urban population                           object
Urban population with access to water      object
Urban population Reliable Supply           object
% Urban population Reliable Supply         object
Rural population                           object
Rural population  with access  to water    object
Rural population Reliable Supply           object
% Rural population Reliable Supply         object

Missing values:

                                         Missing Values
Unnamed: 0                                          144
population with access  to water                      9
Urban population                                      2
Urban population with access to water                 2
Urban population Reliable Supply                      2
% Urban population Reliable Supply                    2
Rural population                                      7
Rural population  with access  to water               7
Rural population Reliable Supply                      7
% Rural population Reliable Supply                    7

Duplicate rows:
0

First 5 rows:

,Unnamed: 0,WSA Name,population,population with access to water,population Reliable Supply,% population Reliable Supply,Urban population,Urban population with access to water,Urban population Reliable Supply,% Urban population Reliable Supply,Rural population,Rural population with access to water,Rural population Reliable Supply,% Rural population Reliable Supply
0,NaN,Alfred Nzo,829 109,323 859,131 977,16%,46 614,17 722,7 144,15%,782 495,306 137,124 833,16%
1,NaN,Amathole,838 800,509 183,195 069,23%,148 028,106 420,50 650,34%,690 772,402 763,144 419,21%
2,NaN,Blue Crane Route,34 291,32 784,29 486,86%,26 791,25 604,23 029,86%,7 500,7 180,6 457,86%
3,NaN,Buffalo City Metropolitan Municipality,796 675,771 345,571 873,72%,465 125,450 270,338 003,73%,331 550,321 075,233 870,71%
4,NaN,Chris Hani,800 718,596 366,322 992,40%,171 148,157 242,118 650,69%,629 570,439 124,204 342,32%

Numerical summary:

            count  mean  std  min  25%  50%  75%  max
Unnamed: 0    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN

====================================================================================================
DATASET: Water demand growth_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 10

Column names:
['Region', 'Time Frame', 'Unnamed: 2', '% Water Demand Growth', '% Non-Revenue Water', '% Water Losses', 'System input volume (litres)', 'Revenue water (litres)', 'Non-Revenue water (litres)', 'Water Losses (litres)']

Data types:

                             Data Type
Region                          object
Time Frame                      object
Unnamed: 2                      object
% Water Demand Growth          float64
% Non-Revenue Water            float64
% Water Losses                 float64
System input volume (litres)    object
Revenue water (litres)          object
Non-Revenue water (litres)      object
Water Losses (litres)           object

Missing values:

                              Missing Values
Time Frame                                 1
Unnamed: 2                                10
% Water Demand Growth                      1
% Non-Revenue Water                        1
% Water Losses                             1
System input volume (litres)               1
Revenue water (litres)                     1
Non-Revenue water (litres)                 1
Water Losses (litres)                      1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,% Water Demand Growth,% Non-Revenue Water,% Water Losses,System input volume (litres),Revenue water (litres),Non-Revenue water (litres),Water Losses (litres)
0,City of Johannesburg Metropolitan Municipality,2 018,NaN,2.24,35.74,34.34,536 312 001.00,344 641 579.00,191 670 422.00,184 160 156.00
1,City of Tshwane Metropolitan Municipality,2 018,NaN,-0.40,25.48,24.42,318 733 465.00,237 530 661.00,81 202 804.00,77 831 360.00
2,Ekurhuleni Metropolitan Municipality,2 018,NaN,3.35,39.34,31.30,338 742 752.00,205 497 030.00,133 245 722.00,106 026 481.00
3,Emfuleni,2 018,NaN,-1.12,48.80,48.80,82 417 605.00,42 197 813.76,40 219 791.24,40 219 791.00
4,Lesedi,2 018,NaN,-1.73,23.00,23.00,6 328 721.00,4 873 115.17,1 455 605.83,1 455 606.00

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
% Water Demand Growth,10.0,0.651,4.909982,-10.13,-0.94,0.575,3.0725,8.9
% Non-Revenue Water,10.0,33.889,7.591215,23.00,28.69,35.020,37.4275,48.8
% Water Losses,10.0,31.864,7.504036,23.00,27.45,30.250,34.3300,48.8

====================================================================================================
DATASET: NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026
====================================================================================================
Rows: 0
Columns: 4

Column names:
['WSA', 'Population', 'Population with access', '%Population  with access']

Data types:

                         Data Type
WSA                         object
Population                  object
Population with access      object
%Population  with access    object

Missing values:
No missing values.

Duplicate rows:
0

First 5 rows:

Empty DataFrame
Columns: [WSA, Population, Population with access, %Population  with access]
Index: []

Numerical summary:
No numerical columns.

====================================================================================================
DATASET: Institutional Compliance_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 5

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Potable Water Compliance Percentage', 'Effluent Water Compliance Percentage']

Data types:

                                     Data Type
Region                                  object
Time Frame                              object
Unnamed: 2                              object
Potable Water Compliance Percentage    float64
Effluent Water Compliance Percentage   float64

Missing values:

                                      Missing Values
Time Frame                                         1
Unnamed: 2                                        10
Potable Water Compliance Percentage                1
Effluent Water Compliance Percentage               1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Potable Water Compliance Percentage,Effluent Water Compliance Percentage
0,City of Johannesburg Metropolitan Municipality,April 2022,NaN,102.68,96.99
1,City of Tshwane Metropolitan Municipality,April 2022,NaN,89.45,74.85
2,Ekurhuleni Metropolitan Municipality,April 2022,NaN,101.55,98.91
3,Emfuleni,April 2022,NaN,62.20,77.38
4,Lesedi,April 2022,NaN,97.16,88.04

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
Potable Water Compliance Percentage,10.0,93.051,14.545463,62.20,91.3775,99.540,102.3975,103.51
Effluent Water Compliance Percentage,10.0,76.749,15.782660,52.33,68.4325,76.115,87.2500,98.91

====================================================================================================
DATASET: Microbiological _ Acute Health_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 8

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Risk Type', 'Analysis Done', 'Analysis Failed', 'Compliance Percentage', 'Compliance Result']

Data types:

                      Data Type
Region                   object
Time Frame               object
Unnamed: 2               object
Risk Type                object
Analysis Done            object
Analysis Failed         float64
Compliance Percentage   float64
Compliance Result        object

Missing values:

                       Missing Values
Time Frame                          1
Unnamed: 2                         10
Risk Type                           1
Analysis Done                       1
Analysis Failed                     1
Compliance Percentage               1
Compliance Result                   1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Risk Type,Analysis Done,Analysis Failed,Compliance Percentage,Compliance Result
0,City of Johannesburg Metropolitan Municipality,2 026,NaN,Microbiological : Acute Health,1 159,13.0,98.88,Good
1,City of Tshwane Metropolitan Municipality,2 026,NaN,Microbiological : Acute Health,377,59.0,84.35,Bad
2,Ekurhuleni Metropolitan Municipality,2 026,NaN,Microbiological : Acute Health,819,9.0,98.90,Good
3,Emfuleni,2 026,NaN,Microbiological : Acute Health,0,0.0,0.00,Bad
4,Lesedi,2 026,NaN,Microbiological : Acute Health,54,0.0,100.00,Excellent

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
Analysis Failed,10.0,21.60,35.450121,0.0,0.2500,5.50,21.250,108.0
Compliance Percentage,10.0,76.83,40.751744,0.0,86.5275,97.08,98.895,100.0

====================================================================================================
DATASET: Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]
====================================================================================================
Rows: 4
Columns: 2

Column names:
["'Category", "'SANS 241 :2006:"]

Data types:

                 Data Type
'Category           object
'SANS 241 :2006:   float64

Missing values:
No missing values.

Duplicate rows:
0

First 5 rows:

                             'Category  'SANS 241 :2006:
0                   'Chemical : Health         94.857059
1            'Microbiological : Health         96.086215
2            'Operational : Non-Health         91.560539
3  'Physical Orhanoleptic : Non-Health         98.819385

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
'SANS 241 :2006:,4.0,95.330799,3.009993,91.560539,94.032929,95.471637,96.769507,98.819385

====================================================================================================
DATASET: Surface Water Storage ( 2020 -2026)
====================================================================================================
Rows: 375
Columns: 9

Column names:
["'DateTime", "'High", "'Moderately High", "'Normal", "'Moderately Low", "'Low", "'Very Low", "'2024/2025", "'2025/2026"]

Data types:

                 Data Type
'DateTime           object
'High              float64
'Moderately High   float64
'Normal            float64
'Moderately Low    float64
'Low               float64
'Very Low          float64
'2024/2025         float64
'2025/2026         float64

Missing values:

                  Missing Values
'High                        303
'Moderately High             303
'Normal                      303
'Moderately Low              303
'Low                         303
'Very Low                    303
'2024/2025                    62
'2025/2026                    73

Duplicate rows:
0

First 5 rows:

,'DateTime,'High,'Moderately High,'Normal,'Moderately Low,'Low,'Very Low,'2024/2025,'2025/2026
0,'2020-10-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,64.673521,63.926720
1,'2020-10-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,63.827687,63.278295
2,'2020-10-15 00:00:00,90.99,84.02,79.47,70.61,64.17,61.1,62.867617,62.632930
3,'2020-10-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,61.857000,61.851849
4,'2020-10-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,60.946196,61.128307

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
'High,72.0,96.222917,2.434156,90.990000,94.460000,96.640000,97.400000,101.700000
'Moderately High,72.0,87.777188,2.258706,82.935000,85.818750,88.397500,89.587500,91.200000
'Normal,72.0,84.295917,3.050318,77.800000,81.902500,85.739000,86.647500,88.428000
'Moderately Low,72.0,78.023972,3.987864,66.300000,75.298000,79.116000,80.990500,84.094000
'Low,72.0,68.606840,5.609553,60.110000,63.657500,69.287500,73.497500,78.592500
'Very Low,72.0,63.392375,4.005177,57.008000,58.785500,64.300000,67.150000,69.324000
'2024/2025,313.0,83.470865,11.447626,56.562360,76.524777,85.979025,93.298052,100.215673
'2025/2026,302.0,88.218523,8.355380,60.947382,84.365152,91.374867,94.346891,100.845990

====================================================================================================
DATASET: Households Served with Water_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 17

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Households served with water 1994 to April 2025', 'Households served with water 201415', 'Households served with water 201516', 'Households served with water 201617', 'Households served with water 201718', 'Households served with water 201819', 'Households served with water 201920', 'Households served with water 202021', 'Households served with water 202122', 'Households served with water 202223', 'Households served with water 202324', 'Households served with water 202425', 'Households served with water 202526', 'Planned Households to be served 202627']

Data types:

                                                Data Type
Region                                             object
Time Frame                                         object
Unnamed: 2                                         object
Households served with water 1994 to April 2025    object
Households served with water 201415               float64
Households served with water 201516                object
Households served with water 201617                object
Households served with water 201718                object
Households served with water 201819                object
Households served with water 201920                object
Households served with water 202021                object
Households served with water 202122               float64
Households served with water 202223                object
Households served with water 202324                object
Households served with water 202425                object
Households served with water 202526                object
Planned Households to be served 202627             object

Missing values:

                                                 Missing Values
Time Frame                                                    1
Unnamed: 2                                                   10
Households served with water 1994 to April 2025               1
Households served with water 201415                           1
Households served with water 201516                           1
Households served with water 201617                           1
Households served with water 201718                           1
Households served with water 201819                           1
Households served with water 201920                           1
Households served with water 202021                           1
Households served with water 202122                           1
Households served with water 202223                           1
Households served with water 202324                           1
Households served with water 202425                           1
Households served with water 202526                           1
Planned Households to be served 202627                        1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Households served with water 1994 to April 2025,Households served with water 201415,Households served with water 201516,Households served with water 201617,Households served with water 201718,Households served with water 201819,Households served with water 201920,Households served with water 202021,Households served with water 202122,Households served with water 202223,Households served with water 202324,Households served with water 202425,Households served with water 202526,Planned Households to be served 202627
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,653 974,276.0,22 986,14 316,35 909,23 781,11 412,11 653,0.0,9 810,3 077,20 334,5 912,2 762
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,370 255,18.0,11 244,10 653,19 806,14 583,8 630,8 355,0.0,5 835,8 976,13 803,4 187,2 394
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,517 293,190.0,9 227,14 617,25 932,18 215,10 356,8 200,0.0,6 886,7 704,16 217,4 679,2 940
3,Emfuleni,April 2026,NaN,121 764,0.0,726,807,4 759,3 174,1 774,1 600,0.0,1 324,1 674,3 693,968,1 016
4,Lesedi,April 2026,NaN,13 756,98.0,420,251,532,479,265,287,0.0,201,259,458,140,63

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
Households served with water 201415,10.0,116.4,190.157362,0.0,0.0,9.0,167.0,582.0
Households served with water 202122,10.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0

====================================================================================================
DATASET: NIWIS_GroundwaterStatus_16-Jul-2026
====================================================================================================
Rows: 1947
Columns: 8

Column names:
['Quaternary', 'Reserve Study', 'Available (GRA2)(m3/a)', 'Recharge (GWR)(m3/a)', 'Reserve (GWR)(m3/a)', 'Abstracted (WARMS)(m3/a)', 'Surplus (GRA2)(m3/a)', 'Surplus (GWR)(m3/a)']

Data types:

                         Data Type
Quaternary                  object
Reserve Study                int64
Available (GRA2)(m3/a)      object
Recharge (GWR)(m3/a)        object
Reserve (GWR)(m3/a)         object
Abstracted (WARMS)(m3/a)    object
Surplus (GRA2)(m3/a)        object
Surplus (GWR)(m3/a)         object

Missing values:

                      Missing Values
Recharge (GWR)(m3/a)             837
Reserve (GWR)(m3/a)              837
Surplus (GWR)(m3/a)              837

Duplicate rows:
1

First 5 rows:

,Quaternary,Reserve Study,Available (GRA2)(m3/a),Recharge (GWR)(m3/a),Reserve (GWR)(m3/a),Abstracted (WARMS)(m3/a),Surplus (GRA2)(m3/a),Surplus (GWR)(m3/a)
0,E10A,1,3 797 140,30 120 000,5 440 000,123 420,3 673 720,24 556 580
1,E10B,1,5 302 850,37 170 000,6 790 000,12 050 080,-6 747 230,18 329 920
2,E10C,1,3 596 190,24 790 000,5 660 000,991 600,2 604 590,18 138 400
3,E10D,1,2 737 390,24 350 000,5 740 000,0,2 737 390,18 610 000
4,E10E,1,2 361 910,30 670 000,7 490 000,2 091 128,270 782,21 088 872

Numerical summary:

                count      mean       std  min  25%  50%  75%  max
Reserve Study  1947.0  0.570108  0.495188  0.0  0.0  1.0  1.0  1.0

====================================================================================================
DATASET: Surface Water Storage (2014-2020)
====================================================================================================
Rows: 374
Columns: 9

Column names:
["'DateTime", "'High", "'Moderately High", "'Normal", "'Moderately Low", "'Low", "'Very Low", "'2018/2019", "'2019/2020"]

Data types:

                 Data Type
'DateTime           object
'High              float64
'Moderately High   float64
'Normal            float64
'Moderately Low    float64
'Low               float64
'Very Low          float64
'2018/2019         float64
'2019/2020         float64

Missing values:

                  Missing Values
'High                        302
'Moderately High             302
'Normal                      302
'Moderately Low              302
'Low                         302
'Very Low                    302
'2018/2019                    60
'2019/2020                    99

Duplicate rows:
0

First 5 rows:

,'DateTime,'High,'Moderately High,'Normal,'Moderately Low,'Low,'Very Low,'2018/2019,'2019/2020
0,'2014-10-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,76.958839,80.565839
1,'2014-10-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,76.068734,79.891470
2,'2014-10-15 00:00:00,90.99,86.4,82.04,78.74,71.9,61.906,74.552466,78.976701
3,'2014-10-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,73.780688,78.084224
4,'2014-10-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,73.613656,77.309324

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
'High,72.0,95.099167,2.235766,90.990000,93.675000,94.245000,97.107500,98.700000
'Moderately High,72.0,87.340729,2.041327,83.510000,85.674375,87.038750,89.375000,90.592500
'Normal,72.0,84.753583,2.725920,78.324000,82.431500,85.807000,86.792000,88.998000
'Moderately Low,72.0,79.158722,3.511085,70.724000,76.936000,79.695000,81.746000,85.010000
'Low,72.0,71.164062,6.085211,59.880000,66.695000,72.347500,75.835625,81.082500
'Very Low,72.0,63.281028,4.106812,55.820000,58.711250,64.224500,67.068250,69.599000
'2018/2019,314.0,70.193007,10.908586,48.306678,62.517296,72.287366,78.903410,92.049189
'2019/2020,275.0,67.272770,9.774100,48.420322,59.438076,68.060977,74.855838,83.064876

====================================================================================================
DATASET: People Served with Water_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 17

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Population served with water 1994 to April 2025', 'Population served with water 201415', 'Population served with water 201516', 'Population served with water 201617', 'Population served with water 201718', 'Population served with water 201819', 'Population served with water 201920', 'Population served with water 202021', 'Population served with water 202122', 'Population served with water 202223', 'Population served with water 202324', 'Population served with water 202425', 'Population served with water 202526', 'Planned Population to be served 202627']

Data types:

                                                Data Type
Region                                             object
Time Frame                                         object
Unnamed: 2                                         object
Population served with water 1994 to April 2025    object
Population served with water 201415                object
Population served with water 201516                object
Population served with water 201617                object
Population served with water 201718                object
Population served with water 201819                object
Population served with water 201920                object
Population served with water 202021                object
Population served with water 202122               float64
Population served with water 202223                object
Population served with water 202324                object
Population served with water 202425                object
Population served with water 202526                object
Planned Population to be served 202627             object

Missing values:

                                                 Missing Values
Time Frame                                                    1
Unnamed: 2                                                   10
Population served with water 1994 to April 2025               1
Population served with water 201415                           1
Population served with water 201516                           1
Population served with water 201617                           1
Population served with water 201718                           1
Population served with water 201819                           1
Population served with water 201920                           1
Population served with water 202021                           1
Population served with water 202122                           1
Population served with water 202223                           1
Population served with water 202324                           1
Population served with water 202425                           1
Population served with water 202526                           1
Planned Population to be served 202627                        1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Population served with water 1994 to April 2025,Population served with water 201415,Population served with water 201516,Population served with water 201617,Population served with water 201718,Population served with water 201819,Population served with water 201920,Population served with water 202021,Population served with water 202122,Population served with water 202223,Population served with water 202324,Population served with water 202425,Population served with water 202526,Planned Population to be served 202627
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,1 877 971,877,61 779,37 123,94 764,62 860,30 140,30 769,0.0,24 998,7 780,52 267,14 933,8 299
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,1 154 171,153,32 631,29 923,56 353,41 544,24 560,23 822,0.0,16 038,27 098,42 371,12 617,7 764
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,1 528 720,658,24 089,37 491,66 459,46 565,26 498,21 012,0.0,17 028,21 736,46 224,13 094,11 383
3,Emfuleni,April 2026,NaN,392 260,0,2 117,2 189,13 579,9 070,5 101,4 584,0.0,3 687,5 296,11 809,3 067,5 531
4,Lesedi,April 2026,NaN,46 377,278,1 213,742,1 514,1 356,757,818,0.0,555,801,1 429,425,210

Numerical summary:

                                     count  mean  std  min  25%  50%  75%  max
Population served with water 202122   10.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0

====================================================================================================
DATASET: Areas of Highest Vulnerability_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 21

Column names:
['Region', 'Time Frame', 'Unnamed: 2', '1# Water Services Planning', '2# Management Skill Level (Technical)', '3# Staff Skill Level (Technical)', '4# Technical Staff Capacity (Numbers)', '5# Water Resource Management (WRM)', '6# Water Conservation & Water Demand Management (WC/WDM)', '7# Drinking Water Safety & Regulatory Compliance', '8# Basic Sanitation', '9# Wastewater/Environmental Safety & Regulatory Compliance', '10# Infrastructure Asset Management (IAM)', '11# Operation & Maintenance (O&M) of Assets', '12# Financial Management', '13# Revenue Collection', '14# Financial Asset Management', '15# Information Management (IT)', '16# Organisational Performance Monitoring', '17# Water and Sanitation Service Quality', '18# Customer Care (CRM)']

Data types:

                                                   Data Type
Region                                                object
Time Frame                                            object
Unnamed: 2                                            object
1# Water Services Planning                            object
2# Management Skill Level (Technical)                 object
3# Staff Skill Level (Technical)                      object
4# Technical Staff Capacity (Numbers)                 object
5# Water Resource Management (WRM)                    object
6# Water Conservation & Water Demand Management...    object
7# Drinking Water Safety & Regulatory Compliance      object
8# Basic Sanitation                                   object
9# Wastewater/Environmental Safety & Regulatory...    object
10# Infrastructure Asset Management (IAM)             object
11# Operation & Maintenance (O&M) of Assets           object
12# Financial Management                              object
13# Revenue Collection                                object
14# Financial Asset Management                        object
15# Information Management (IT)                       object
16# Organisational Performance Monitoring             object
17# Water and Sanitation Service Quality              object
18# Customer Care (CRM)                               object

Missing values:

                                                    Missing Values
Time Frame                                                       1
Unnamed: 2                                                      10
1# Water Services Planning                                       1
2# Management Skill Level (Technical)                            1
3# Staff Skill Level (Technical)                                 1
4# Technical Staff Capacity (Numbers)                            1
5# Water Resource Management (WRM)                               1
6# Water Conservation & Water Demand Management...               1
7# Drinking Water Safety & Regulatory Compliance                 1
8# Basic Sanitation                                              1
9# Wastewater/Environmental Safety & Regulatory...               1
10# Infrastructure Asset Management (IAM)                        1
11# Operation & Maintenance (O&M) of Assets                      1
12# Financial Management                                         1
13# Revenue Collection                                           1
14# Financial Asset Management                                   1
15# Information Management (IT)                                  1
16# Organisational Performance Monitoring                        1
17# Water and Sanitation Service Quality                         1
18# Customer Care (CRM)                                          1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,1# Water Services Planning,2# Management Skill Level (Technical),3# Staff Skill Level (Technical),4# Technical Staff Capacity (Numbers),5# Water Resource Management (WRM),6# Water Conservation & Water Demand Management (WC/WDM),7# Drinking Water Safety & Regulatory Compliance,...,9# Wastewater/Environmental Safety & Regulatory Compliance,10# Infrastructure Asset Management (IAM),11# Operation & Maintenance (O&M) of Assets,12# Financial Management,13# Revenue Collection,14# Financial Asset Management,15# Information Management (IT),16# Organisational Performance Monitoring,17# Water and Sanitation Service Quality,18# Customer Care (CRM)
0,City of Johannesburg Metropolitan Municipality,2 018,NaN,Low,Low,Low,Low,Extreme,Low,Low,...,Low,Low,Moderate,Low,Low,Low,Low,Low,Low,Low
1,City of Tshwane Metropolitan Municipality,2 018,NaN,Low,Low,Low,Extreme,Moderate,Low,Low,...,Extreme,Moderate,Extreme,Low,Low,Extreme,Low,Low,Low,Low
2,Ekurhuleni Metropolitan Municipality,2 018,NaN,Low,Moderate,Low,Low,Low,Low,Low,...,Moderate,Low,Moderate,Low,Low,High,Low,Low,Low,Low
3,Emfuleni,2 018,NaN,Extreme,Extreme,Extreme,Extreme,High,High,Moderate,...,Extreme,High,Extreme,Extreme,High,Extreme,Extreme,Low,Moderate,Extreme
4,Lesedi,2 018,NaN,Moderate,Moderate,Moderate,Moderate,Extreme,Low,Moderate,...,High,High,Extreme,Extreme,Low,Extreme,Low,Low,Moderate,Low

Numerical summary:
No numerical columns.

====================================================================================================
DATASET: Protests Identified by Municipal IQ_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 16

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Total Protests', 'Informal', 'Violent', 'Xenophobia', 'Criminality', 'Corruption', 'Councillor', 'Water', 'Sanitation', 'Electricity', 'Refuse Removal', 'Roads', 'Housing']

Data types:

               Data Type
Region            object
Time Frame        object
Unnamed: 2        object
Total Protests   float64
Informal         float64
Violent          float64
Xenophobia       float64
Criminality      float64
Corruption       float64
Councillor       float64
Water            float64
Sanitation       float64
Electricity      float64
Refuse Removal   float64
Roads            float64
Housing          float64

Missing values:

                Missing Values
Time Frame                   1
Unnamed: 2                  10
Total Protests               1
Informal                     1
Violent                      1
Xenophobia                   1
Criminality                  1
Corruption                   1
Councillor                   1
Water                        1
Sanitation                   1
Electricity                  1
Refuse Removal               1
Roads                        1
Housing                      1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Total Protests,Informal,Violent,Xenophobia,Criminality,Corruption,Councillor,Water,Sanitation,Electricity,Refuse Removal,Roads,Housing
0,City of Johannesburg Metropolitan Municipality,2 018,NaN,174.0,101.0,143.0,4.0,17.0,5.0,35.0,37.0,26.0,76.0,7.0,9.0,77.0
1,City of Tshwane Metropolitan Municipality,2 018,NaN,85.0,28.0,64.0,2.0,7.0,16.0,33.0,36.0,18.0,29.0,2.0,11.0,38.0
2,Ekurhuleni Metropolitan Municipality,2 018,NaN,73.0,42.0,57.0,3.0,6.0,9.0,18.0,16.0,12.0,31.0,1.0,2.0,27.0
3,Emfuleni,2 018,NaN,15.0,3.0,13.0,1.0,2.0,2.0,4.0,3.0,1.0,1.0,0.0,4.0,4.0
4,Lesedi,2 018,NaN,2.0,0.0,2.0,2.0,2.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0

Numerical summary:

                count  mean         std  min   25%   50%    75%    max
Total Protests   10.0  76.2  120.400074  2.0  7.25  13.5  82.00  381.0
Informal         10.0  37.8   61.705033  0.0  3.25   5.5  38.50  189.0
Violent          10.0  60.8   96.402858  1.0  5.00  12.5  62.25  304.0
Xenophobia       10.0   3.0    4.447221  0.0  0.25   2.0   3.00   15.0
Criminality      10.0   7.8   12.044362  0.0  1.25   2.5   6.75   39.0
Corruption       10.0   7.4   11.529672  0.0  1.25   2.0   8.00   37.0
Councillor       10.0  21.0   32.228352  0.0  2.50   6.0  29.25  105.0
Water            10.0  20.0   31.531290  0.0  2.00   3.0  31.00  100.0
Sanitation       10.0  12.8   20.048829  0.0  1.00   2.5  16.50   64.0
Electricity      10.0  30.6   49.096730  1.0  2.00   5.5  30.50  153.0
Refuse Removal   10.0   2.4    4.005552  0.0  0.00   0.5   2.00   12.0
Roads            10.0   5.6    8.796464  0.0  0.00   2.0   7.75   28.0
Housing          10.0  31.2   50.272148  0.0  2.25   3.5  35.25  156.0

====================================================================================================
DATASET: Verified - River Flow ( National )
====================================================================================================
Rows: 7
Columns: 2

Column names:
["'Flow", "'Flow Level :"]

Data types:

              Data Type
'Flow            object
'Flow Level :     int64

Missing values:
No missing values.

Duplicate rows:
0

First 5 rows:

              'Flow  'Flow Level :
0             'High            243
1  'Moderately High             54
2           'Normal             66
3   'Moderately Low             36
4              'Low             46

Numerical summary:

               count       mean       std   min   25%   50%   75%    max
'Flow Level :    7.0  76.857143  74.44557  30.0  41.0  54.0  64.5  243.0

====================================================================================================
DATASET: Weather
====================================================================================================
Rows: 21301
Columns: 14

Column names:
['STATION', 'NAME', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'DATE', 'PRCP', 'PRCP_ATTRIBUTES', 'TAVG', 'TAVG_ATTRIBUTES', 'TMAX', 'TMAX_ATTRIBUTES', 'TMIN', 'TMIN_ATTRIBUTES']

Data types:

                Data Type
STATION            object
NAME               object
LATITUDE          float64
LONGITUDE         float64
ELEVATION         float64
DATE               object
PRCP              float64
PRCP_ATTRIBUTES    object
TAVG              float64
TAVG_ATTRIBUTES    object
TMAX              float64
TMAX_ATTRIBUTES    object
TMIN              float64
TMIN_ATTRIBUTES    object

Missing values:

                 Missing Values
PRCP                      13284
PRCP_ATTRIBUTES           13284
TMAX                       1640
TMAX_ATTRIBUTES            1640
TMIN                       4499
TMIN_ATTRIBUTES            4499

Duplicate rows:
0

First 5 rows:

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,PRCP_ATTRIBUTES,TAVG,TAVG_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES,TMIN,TMIN_ATTRIBUTES
0,SFM00068368,"JOHANNESBURG INTERNATIONAL, SF",-26.139,28.246,1694.1,2000-01-01,15.5,",,S",17.2,"H,,S",26.8,",,S",13.7,",,S"
1,SFM00068368,"JOHANNESBURG INTERNATIONAL, SF",-26.139,28.246,1694.1,2000-01-02,0.5,",,S",18.3,"H,,S",24.4,",,S",NaN,NaN
2,SFM00068368,"JOHANNESBURG INTERNATIONAL, SF",-26.139,28.246,1694.1,2000-01-03,5.6,",,S",16.0,"H,,S",24.4,",,S",13.4,",,S"
3,SFM00068368,"JOHANNESBURG INTERNATIONAL, SF",-26.139,28.246,1694.1,2000-01-04,1.5,",,S",16.7,"H,,S",21.7,",,S",12.3,",,S"
4,SFM00068368,"JOHANNESBURG INTERNATIONAL, SF",-26.139,28.246,1694.1,2000-01-05,7.4,",,S",17.2,"H,,S",21.7,",,S",14.3,",,S"

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
LATITUDE,21301.0,-25.945538,0.153683,-26.139,-26.139,-25.917,-25.917,-25.733
LONGITUDE,21301.0,28.218314,0.023565,28.183,28.217,28.217,28.246,28.246
ELEVATION,21301.0,1520.803319,140.180907,1322.000,1500.000,1500.000,1694.100,1694.100
PRCP,8017.0,4.384533,10.589892,0.000,0.000,0.500,4.300,340.100
TAVG,21301.0,17.589860,4.466002,0.800,14.300,18.100,20.900,31.400
TMAX,19661.0,25.256096,4.623825,6.900,22.000,25.600,28.700,38.800
TMIN,16802.0,11.361290,4.973602,-7.000,7.500,12.200,15.300,26.100

====================================================================================================
DATASET: Total Households_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 8

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Total Households', 'Total Population', 'HH Density', 'Urban Households', 'Rural Households']

Data types:

                 Data Type
Region              object
Time Frame          object
Unnamed: 2          object
Total Households    object
Total Population    object
HH Density         float64
Urban Households    object
Rural Households    object

Missing values:

                  Missing Values
Time Frame                     1
Unnamed: 2                    10
Total Households               1
Total Population               1
HH Density                     1
Urban Households               1
Rural Households               1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Total Households,Total Population,HH Density,Urban Households,Rural Households
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,1 999 327,5 045 624,2.52,1 908 922,90 405
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,1 469 057,4 426 868,3.01,1 320 442,148 615
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,1 567 566,4 391 840,2.80,1 369 578,197 988
3,Emfuleni,April 2026,NaN,326 534,1 025 702,3.14,302 095,24 439
4,Lesedi,April 2026,NaN,47 233,144 504,3.06,39 418,7 815

Numerical summary:

            count   mean       std   min    25%   50%   75%   max
HH Density   10.0  2.861  0.217432  2.51  2.785  2.87  3.04  3.14

====================================================================================================
DATASET: Potable Systems_ 2026_04_21
====================================================================================================
Rows: 61
Columns: 11

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'System name', 'System area', 'Population in system', 'Households in System', 'Households with Access to RDP Water', 'Households with Access to Reliable Water', 'Drinking Water Quality Percentage', 'Latest Blue Drop Score']

Data types:

                                         Data Type
Region                                      object
Time Frame                                  object
Unnamed: 2                                  object
System name                                 object
System area                                 object
Population in system                        object
Households in System                        object
Households with Access to RDP Water         object
Households with Access to Reliable Water    object
Drinking Water Quality Percentage          float64
Latest Blue Drop Score                     float64

Missing values:

                                          Missing Values
Time Frame                                             1
Unnamed: 2                                            60
System name                                            1
System area                                            1
Population in system                                   1
Households in System                                   1
Households with Access to RDP Water                    1
Households with Access to Reliable Water               1
Drinking Water Quality Percentage                      1
Latest Blue Drop Score                                 1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,System name,System area,Population in system,Households in System,Households with Access to RDP Water,Households with Access to Reliable Water,Drinking Water Quality Percentage,Latest Blue Drop Score
0,City of Johannesburg Metropolitan Municipality,April 2022,NaN,Greater Johannesburg Water Supply System,"Alexandra,East Bank ,Tsutsumani ,Bultfontein ,...",4 434 827,1 733 856,1 733 856,1 404 854,99.67,98.10
1,City of Tshwane Metropolitan Municipality,April 2022,NaN,PRETORIA Central & South (Rietvlei WTW & Rand ...,"Rietvalleipark, Rietvalleirand, Elarduspark, W...",1 523 194,551 867,534 627,455 074,99.92,89.36
2,City of Tshwane Metropolitan Municipality,April 2022,NaN,PRETORIA Findley (Fountains),Central Business District,6 322,2 291,2 219,1 889,99.48,64.44
3,City of Tshwane Metropolitan Municipality,April 2022,NaN,PRETORIA Temba (Temba WTW; Klipdrift WTW),"Stinkwater,Kudube,Hammanskraal ,Temba, Skampan...",400 875,145 241,140 703,119 767,99.66,55.97
4,City of Tshwane Metropolitan Municipality,April 2022,NaN,PRETORIA North - (Roodeplaat WTW),"Montana, Montana Tuine, Pumulani AH, Wolmarans...",413 860,149 945,145 261,123 646,100.00,63.56

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
Drinking Water Quality Percentage,60.0,90.268000,26.286442,0.0,98.39,99.895,100.00,100.0
Latest Blue Drop Score,60.0,77.852667,17.270366,42.3,63.56,86.515,89.36,98.1

====================================================================================================
DATASET: Source of Water Households _ 2026_04_21
====================================================================================================
Rows: 10
Columns: 13

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Regional/local water scheme (operated by municipality or other w', 'Borehole', 'Spring', 'Rain water tank', 'Dam/pool/stagnant water', 'River/stream', 'Water vendor', 'Water tanker', 'Other', 'Not applicable']

Data types:

                                                   Data Type
Region                                                object
Time Frame                                            object
Unnamed: 2                                            object
Regional/local water scheme (operated by munici...    object
Borehole                                              object
Spring                                                object
Rain water tank                                       object
Dam/pool/stagnant water                               object
River/stream                                          object
Water vendor                                          object
Water tanker                                          object
Other                                                 object
Not applicable                                       float64

Missing values:

                                                    Missing Values
Time Frame                                                       1
Unnamed: 2                                                       9
Regional/local water scheme (operated by munici...               1
Borehole                                                         1
Spring                                                           1
Rain water tank                                                  1
Dam/pool/stagnant water                                          1
River/stream                                                     1
Water vendor                                                     1
Water tanker                                                     1
Other                                                            1
Not applicable                                                   1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Regional/local water scheme (operated by municipality or other w,Borehole,Spring,Rain water tank,Dam/pool/stagnant water,River/stream,Water vendor,Water tanker,Other,Not applicable
0,City of Johannesburg Metropolitan Municipality,Oct 2011,NaN,1 371 966,14 478,1 215,1 556,1 531,424,5 592,20 887,15 833,0.0
1,City of Tshwane Metropolitan Municipality,Oct 2011,NaN,825 746,25 730,1 231,1 426,2 409,550,5 615,30 864,16 983,0.0
2,Ekurhuleni Metropolitan Municipality,Oct 2011,NaN,972 647,10 997,985,1 065,923,253,3 703,9 247,14 629,0.0
3,Emfuleni,Oct 2011,NaN,211 967,3 781,98,395,225,90,619,425,2 295,0.0
4,Lesedi,Oct 2011,NaN,26 377,2 495,68,55,98,28,40,193,279,0.0

Numerical summary:

                count  mean  std  min  25%  50%  75%  max
Not applicable    9.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0

====================================================================================================
DATASET: Vulnerability Score Per leg_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 9

Column names:
['Region', 'Time Frame', 'Unnamed: 2', '1# Water Services Planning', '4# Technical Staff Capacity (Numbers)', '6# Water Conservation & Water Demand Management (WC/WDM)', '7# Drinking Water Safety & Regulatory Compliance', '10# Infrastructure Asset Management (IAM)', '11# Operation & Maintenance (O&M) of Assets']

Data types:

                                                   Data Type
Region                                                object
Time Frame                                            object
Unnamed: 2                                            object
1# Water Services Planning                           float64
4# Technical Staff Capacity (Numbers)                float64
6# Water Conservation & Water Demand Management...   float64
7# Drinking Water Safety & Regulatory Compliance     float64
10# Infrastructure Asset Management (IAM)            float64
11# Operation & Maintenance (O&M) of Assets          float64

Missing values:

                                                    Missing Values
Time Frame                                                       1
Unnamed: 2                                                      10
1# Water Services Planning                                       1
4# Technical Staff Capacity (Numbers)                            1
6# Water Conservation & Water Demand Management...               1
7# Drinking Water Safety & Regulatory Compliance                 1
10# Infrastructure Asset Management (IAM)                        1
11# Operation & Maintenance (O&M) of Assets                      1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,1# Water Services Planning,4# Technical Staff Capacity (Numbers),6# Water Conservation & Water Demand Management (WC/WDM),7# Drinking Water Safety & Regulatory Compliance,10# Infrastructure Asset Management (IAM),11# Operation & Maintenance (O&M) of Assets
0,City of Johannesburg Metropolitan Municipality,2 018,NaN,93.0,79.0,80.0,98.0,99.0,65.0
1,City of Tshwane Metropolitan Municipality,2 018,NaN,90.0,20.0,80.0,80.0,60.0,40.0
2,Ekurhuleni Metropolitan Municipality,2 018,NaN,95.0,80.0,80.0,100.0,90.0,70.0
3,Emfuleni,2 018,NaN,40.0,15.0,55.0,65.0,54.0,30.0
4,Lesedi,2 018,NaN,65.0,69.0,80.0,74.0,55.0,35.0

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
1# Water Services Planning,10.0,69.778,26.464978,20.0,53.75,72.390,92.2500,100.0
4# Technical Staff Capacity (Numbers),10.0,53.889,24.798945,15.0,45.00,49.445,76.5000,87.0
6# Water Conservation & Water Demand Management (WC/WDM),10.0,71.556,11.898750,55.0,59.14,77.500,80.0000,84.0
7# Drinking Water Safety & Regulatory Compliance,10.0,77.222,16.890351,55.0,65.00,75.610,93.5000,100.0
10# Infrastructure Asset Management (IAM),10.0,68.667,19.165942,45.0,55.00,62.500,84.6675,99.0
11# Operation & Maintenance (O&M) of Assets,10.0,53.333,15.986105,30.0,41.25,51.665,68.7500,75.0

====================================================================================================
DATASET: Total Population_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 8

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Total Population', 'Total Households', 'HH Density', 'Urban Population', 'Rural Population']

Data types:

                 Data Type
Region              object
Time Frame          object
Unnamed: 2          object
Total Population    object
Total Households    object
HH Density         float64
Urban Population    object
Rural Population    object

Missing values:

                  Missing Values
Time Frame                     1
Unnamed: 2                    10
Total Population               1
Total Households               1
HH Density                     1
Urban Population               1
Rural Population               1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Total Population,Total Households,HH Density,Urban Population,Rural Population
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,5 045 624,1 999 327,2.52,4 827 348,218 276
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,4 426 868,1 469 057,3.01,3 977 415,449 453
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,4 391 840,1 567 566,2.80,3 824 427,567 413
3,Emfuleni,April 2026,NaN,1 025 702,326 534,3.14,952 341,73 361
4,Lesedi,April 2026,NaN,144 504,47 233,3.06,118 922,25 582

Numerical summary:

            count   mean       std   min    25%   50%   75%   max
HH Density   10.0  2.861  0.217432  2.51  2.785  2.87  3.04  3.14

====================================================================================================
DATASET: TimeSeries Population_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 35

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'April 1994', 'April 1995', 'April 1996', 'April 1997', 'April 1998', 'April 1999', 'April 2000', 'April 2001', 'April 2002', 'April 2004', 'April 2005', 'April 2006', 'April 2007', 'April 2008', 'April 2009', 'April 2010', 'April 2011', 'April 2012', 'April 2013', 'April 2014', 'April 2015', 'April 2016', 'April 2017', 'April 2018', 'April 2019', 'April 2020', 'April 2021', 'April 2022', 'April 2023', 'April 2024', 'April 2025', 'April 2026']

Data types:

           Data Type
Region        object
Time Frame    object
Unnamed: 2    object
April 1994    object
April 1995    object
April 1996    object
April 1997    object
April 1998    object
April 1999    object
April 2000    object
April 2001    object
April 2002    object
April 2004    object
April 2005    object
April 2006    object
April 2007    object
April 2008    object
April 2009    object
April 2010    object
April 2011    object
April 2012    object
April 2013    object
April 2014    object
April 2015    object
April 2016    object
April 2017    object
April 2018    object
April 2019    object
April 2020    object
April 2021    object
April 2022    object
April 2023    object
April 2024    object
April 2025    object
April 2026    object

Missing values:

            Missing Values
Time Frame               1
Unnamed: 2              10
April 1994               1
April 1995               1
April 1996               1
April 1997               1
April 1998               1
April 1999               1
April 2000               1
April 2001               1
April 2002               1
April 2004               1
April 2005               1
April 2006               1
April 2007               1
April 2008               1
April 2009               1
April 2010               1
April 2011               1
April 2012               1
April 2013               1
April 2014               1
April 2015               1
April 2016               1
April 2017               1
April 2018               1
April 2019               1
April 2020               1
April 2021               1
April 2022               1
April 2023               1
April 2024               1
April 2025               1
April 2026               1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,April 1994,April 1995,April 1996,April 1997,April 1998,April 1999,April 2000,...,April 2017,April 2018,April 2019,April 2020,April 2021,April 2022,April 2023,April 2024,April 2025,April 2026
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,2 448 143,2 540 093,2 635 515,2 734 565,2 837 383,2 944 081,3 054 805,...,5 089 098,5 443 141,5 674 824,5 795 032,5 917 763,4 803 262,4 831 752,4 860 421,5 030 537,5 045 624
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,1 711 629,1 764 445,1 819 054,1 875 497,1 933 844,1 994 187,2 056 570,...,3 368 580,3 602 931,3 756 308,3 835 872,3 917 115,4 040 314,4 150 827,4 264 373,4 413 629,4 426 868
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,1 881 907,1 952 473,2 025 714,2 101 721,2 180 598,2 262 466,2 347 437,...,3 463 997,3 704 963,3 862 672,3 944 477,4 028 025,4 066 698,4 147 862,4 230 649,4 378 703,4 391 840
3,Emfuleni,April 2026,NaN,499 397,518 149,537 609,557 801,578 755,600 503,623 074,...,749 729,801 881,836 015,853 720,871 801,945 652,966 627,988 051,1 022 634,1 025 702
4,Lesedi,April 2026,NaN,54 264,56 298,58 412,60 607,62 884,65 244,67 695,...,115 739,123 790,129 059,131 794,134 585,132 783,135 952,139 201,144 071,144 504

Numerical summary:
No numerical columns.

====================================================================================================
DATASET: Piped Water Households _ 2026_04_21
====================================================================================================
Rows: 10
Columns: 12

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Piped (tap) water inside dwelling/institution', 'Piped (tap) water inside yard', 'Piped (tap) water on community stand: distance less than 200m fr', 'Piped (tap) water on community stand: distance between 200m and ', 'Piped (tap) water on community stand: distance between 500m and ', 'Piped (tap) water on community stand: distance greater than 1000', 'No access to piped (tap) water', 'Unspecified', 'Not applicable']

Data types:

                                                   Data Type
Region                                                object
Time Frame                                            object
Unnamed: 2                                            object
Piped (tap) water inside dwelling/institution         object
Piped (tap) water inside yard                         object
Piped (tap) water on community stand: distance ...    object
Piped (tap) water on community stand: distance ...    object
Piped (tap) water on community stand: distance ...    object
Piped (tap) water on community stand: distance ...    object
No access to piped (tap) water                        object
Unspecified                                          float64
Not applicable                                       float64

Missing values:

                                                    Missing Values
Time Frame                                                       1
Unnamed: 2                                                       9
Piped (tap) water inside dwelling/institution                    1
Piped (tap) water inside yard                                    1
Piped (tap) water on community stand: distance ...               1
Piped (tap) water on community stand: distance ...               1
Piped (tap) water on community stand: distance ...               1
Piped (tap) water on community stand: distance ...               1
No access to piped (tap) water                                   1
Unspecified                                                      1
Not applicable                                                   1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Piped (tap) water inside dwelling/institution,Piped (tap) water inside yard,Piped (tap) water on community stand: distance less than 200m fr,Piped (tap) water on community stand: distance between 200m and,Piped (tap) water on community stand: distance between 500m and,Piped (tap) water on community stand: distance greater than 1000,No access to piped (tap) water,Unspecified,Not applicable
0,City of Johannesburg Metropolitan Municipality,Oct 2011,NaN,928 267,386 020,73 265,18 453,6 353,1 970,19 553,0.0,0.0
1,City of Tshwane Metropolitan Municipality,Oct 2011,NaN,585 274,227 278,47 986,12 204,4 942,2 228,30 873,0.0,0.0
2,Ekurhuleni Metropolitan Municipality,Oct 2011,NaN,580 851,303 882,75 741,25 119,13 247,4 783,11 132,0.0,0.0
3,Emfuleni,Oct 2011,NaN,153 874,53 421,7 287,2 312,1 311,535,1 211,0.0,0.0
4,Lesedi,Oct 2011,NaN,15 533,11 813,1 583,214,51,115,346,0.0,0.0

Numerical summary:

                count  mean  std  min  25%  50%  75%  max
Unspecified       9.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
Not applicable    9.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0

====================================================================================================
DATASET: NIWIS_WasteWaterQuality_16-Jul-2026
====================================================================================================
Rows: 143
Columns: 6

Column names:
['Unnamed: 0', 'WSA', 'Chemical', 'Microbiological', 'Physical', 'Monitoring']

Data types:

                Data Type
Unnamed: 0        float64
WSA                object
Chemical           object
Microbiological    object
Physical           object
Monitoring         object

Missing values:

            Missing Values
Unnamed: 0             143

Duplicate rows:
0

First 5 rows:

,Unnamed: 0,WSA,Chemical,Microbiological,Physical,Monitoring
0,NaN,Buffalo City,74%,29%,82%,75%
1,NaN,City of Cape Town,68%,65%,74%,92%
2,NaN,Ekurhuleni,76%,78%,88%,84%
3,NaN,eThekwini,68%,60%,83%,93%
4,NaN,City of Johannesburg,73%,68%,85%,92%

Numerical summary:

            count  mean  std  min  25%  50%  75%  max
Unnamed: 0    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN

====================================================================================================
DATASET: Operational_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 8

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Risk Type', 'Analysis Done', 'Analysis Failed', 'Compliance Percentage', 'Compliance Result']

Data types:

                      Data Type
Region                   object
Time Frame               object
Unnamed: 2               object
Risk Type                object
Analysis Done            object
Analysis Failed         float64
Compliance Percentage   float64
Compliance Result        object

Missing values:

                       Missing Values
Time Frame                          1
Unnamed: 2                         10
Risk Type                           1
Analysis Done                       1
Analysis Failed                     1
Compliance Percentage               1
Compliance Result                   1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Risk Type,Analysis Done,Analysis Failed,Compliance Percentage,Compliance Result
0,City of Johannesburg Metropolitan Municipality,2 026,NaN,Operational,4 751,66.0,98.61,Excellent
1,City of Tshwane Metropolitan Municipality,2 026,NaN,Operational,1 508,196.0,87.00,Poor
2,Ekurhuleni Metropolitan Municipality,2 026,NaN,Operational,3 308,35.0,98.94,Excellent
3,Emfuleni,2 026,NaN,Operational,0,0.0,0.00,Bad
4,Lesedi,2 026,NaN,Operational,124,1.0,99.19,Excellent

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
Analysis Failed,10.0,81.200,129.743165,0.0,2.250,22.50,85.50,406.00
Compliance Percentage,10.0,76.927,40.711937,0.0,88.535,96.99,98.56,99.19

====================================================================================================
DATASET: NIWIS_RWT_16-Jul-2026
====================================================================================================
Rows: 9
Columns: 5

Column names:
['WMA', 'Date', 'Domestic and Industry c/m3', 'Irrigation c/m3', 'Forestry c/m3']

Data types:

                           Data Type
WMA                           object
Date                           int64
Domestic and Industry c/m3   float64
Irrigation c/m3              float64
Forestry c/m3                float64

Missing values:
No missing values.

Duplicate rows:
0

First 5 rows:

,WMA,Date,Domestic and Industry c/m3,Irrigation c/m3,Forestry c/m3
0,Berg Olifants,2025,6.59,3.22,3.15
1,Breede Gouritz,2025,6.14,3.43,1.76
2,Inkomati Usuthu,2025,5.48,2.70,2.15
3,Limpopo NorthWest,2025,5.21,3.84,3.09
4,Mzimvubu Tsitsikamma,2025,4.38,3.50,3.18

Numerical summary:

,count,mean,std,min,25%,50%,75%,max
Date,9.0,2025.000000,0.000000,2025.00,2025.00,2025.00,2025.00,2025.00
Domestic and Industry c/m3,9.0,4.581111,1.488367,1.98,3.56,4.78,5.48,6.59
Irrigation c/m3,9.0,2.981111,0.827880,1.15,2.64,3.22,3.50,3.84
Forestry c/m3,9.0,2.358889,1.010105,0.00,2.15,2.64,3.09,3.18

====================================================================================================
DATASET: Timeseries Households_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 35

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'April 1994', 'April 1995', 'April 1996', 'April 1997', 'April 1998', 'April 1999', 'April 2000', 'April 2001', 'April 2002', 'April 2004', 'April 2005', 'April 2006', 'April 2007', 'April 2008', 'April 2009', 'April 2010', 'April 2011', 'April 2012', 'April 2013', 'April 2014', 'April 2015', 'April 2016', 'April 2017', 'April 2018', 'April 2019', 'April 2020', 'April 2021', 'April 2022', 'April 2023', 'April 2024', 'April 2025', 'April 2026']

Data types:

           Data Type
Region        object
Time Frame    object
Unnamed: 2    object
April 1994    object
April 1995    object
April 1996    object
April 1997    object
April 1998    object
April 1999    object
April 2000    object
April 2001    object
April 2002    object
April 2004    object
April 2005    object
April 2006    object
April 2007    object
April 2008    object
April 2009    object
April 2010    object
April 2011    object
April 2012    object
April 2013    object
April 2014    object
April 2015    object
April 2016    object
April 2017    object
April 2018    object
April 2019    object
April 2020    object
April 2021    object
April 2022    object
April 2023    object
April 2024    object
April 2025    object
April 2026    object

Missing values:

            Missing Values
Time Frame               1
Unnamed: 2              10
April 1994               1
April 1995               1
April 1996               1
April 1997               1
April 1998               1
April 1999               1
April 2000               1
April 2001               1
April 2002               1
April 2004               1
April 2005               1
April 2006               1
April 2007               1
April 2008               1
April 2009               1
April 2010               1
April 2011               1
April 2012               1
April 2013               1
April 2014               1
April 2015               1
April 2016               1
April 2017               1
April 2018               1
April 2019               1
April 2020               1
April 2021               1
April 2022               1
April 2023               1
April 2024               1
April 2025               1
April 2026               1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,April 1994,April 1995,April 1996,April 1997,April 1998,April 1999,April 2000,...,April 2017,April 2018,April 2019,April 2020,April 2021,April 2022,April 2023,April 2024,April 2025,April 2026
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,674 814,716 493,760 743,807 730,857 635,910 638,966 931,...,1 928 958,2 063 091,2 150 924,2 196 476,2 243 001,1 841 886,1 879 191,1 917 263,1 957 863,1 999 327
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,417 911,442 164,467 847,495 038,523 835,554 333,586 634,...,1 183 242,1 265 542,1 319 400,1 347 343,1 375 878,1 322 267,1 364 820,1 408 735,1 438 582,1 469 057
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,498 971,529 782,562 507,597 248,634 137,673 317,714 930,...,1 352 475,1 446 278,1 507 844,1 539 784,1 572 389,1 420 998,1 461 524,1 503 219,1 535 062,1 567 566
3,Emfuleni,April 2026,NaN,125 377,133 102,141 300,150 003,159 248,169 071,179 505,...,263 813,281 072,293 031,299 242,305 585,297 907,305 424,313 129,319 762,326 534
4,Lesedi,April 2026,NaN,12 323,13 082,13 891,14 749,15 660,16 625,17 653,...,40 891,43 735,45 596,46 561,47 546,42 599,43 927,45 294,46 254,47 233

Numerical summary:
No numerical columns.

====================================================================================================
DATASET: Residential Tariffs_ 2026_04_21
====================================================================================================
Rows: 11
Columns: 7

Column names:
['Region', 'Time Frame', 'Unnamed: 2', 'Tariff 0-6kl (incl#VAT)', 'Tariff 6-20kl (incl#VAT)', 'Tariff 20-60kl (incl#VAT)', 'Tariff >60kl (incl#VAT)']

Data types:

                          Data Type
Region                       object
Time Frame                   object
Unnamed: 2                   object
Tariff 0-6kl (incl#VAT)      object
Tariff 6-20kl (incl#VAT)     object
Tariff 20-60kl (incl#VAT)    object
Tariff >60kl (incl#VAT)      object

Missing values:

                           Missing Values
Time Frame                              1
Unnamed: 2                             10
Tariff 0-6kl (incl#VAT)                 1
Tariff 6-20kl (incl#VAT)                1
Tariff 20-60kl (incl#VAT)               1
Tariff >60kl (incl#VAT)                 1

Duplicate rows:
0

First 5 rows:

,Region,Time Frame,Unnamed: 2,Tariff 0-6kl (incl#VAT),Tariff 6-20kl (incl#VAT),Tariff 20-60kl (incl#VAT),Tariff >60kl (incl#VAT)
0,City of Johannesburg Metropolitan Municipality,2 018,NaN,"R0,00","R13,90","R33,73","R38,13"
1,City of Tshwane Metropolitan Municipality,2 018,NaN,"R10,95","R18,89","R29,39","R33,63"
2,Ekurhuleni Metropolitan Municipality,2 018,NaN,"R0,00","R18,30","R26,80","R31,83"
3,Emfuleni,2 018,NaN,"R15,99","R26,94","R39,35","R43,57"
4,Lesedi,2 018,NaN,"R16,06","R19,50","R28,06","R42,45"

Numerical summary:
No numerical columns.

COLUMN-LEVEL AUDIT

In [11]:
column_audit = []

for name, df in datasets.items():

    for col in df.columns:

        column_audit.append({

            "Dataset": name,

            "Column": col,

            "Data Type": str(
                df[col].dtype
            ),

            "Rows": len(df),

            "Missing": int(
                df[col].isnull().sum()
            ),

            "Missing %": round(
                df[col].isnull().mean() * 100,
                2
            ),

            "Unique Values": int(
                df[col].nunique(
                    dropna=True
                )
            ),

            "Duplicate Values": int(
                df[col].duplicated().sum()
            )
        })

column_audit_df = pd.DataFrame(
    column_audit
)

display(
    column_audit_df
)

,Dataset,Column,Data Type,Rows,Missing,Missing %,Unique Values,Duplicate Values
0,NIWIS_Water Supply Reliability - population_16...,Unnamed: 0,float64,144,144,100.00,0,143
1,NIWIS_Water Supply Reliability - population_16...,WSA Name,object,144,0,0.00,144,0
2,NIWIS_Water Supply Reliability - population_16...,population,object,144,0,0.00,144,0
3,NIWIS_Water Supply Reliability - population_16...,population with access to water,object,144,9,6.25,135,8
4,NIWIS_Water Supply Reliability - population_16...,population Reliable Supply,object,144,0,0.00,144,0
...,...,...,...,...,...,...,...,...
308,Residential Tariffs_ 2026_04_21,Unnamed: 2,object,11,10,90.91,1,9
309,Residential Tariffs_ 2026_04_21,Tariff 0-6kl (incl#VAT),object,11,1,9.09,8,2
310,Residential Tariffs_ 2026_04_21,Tariff 6-20kl (incl#VAT),object,11,1,9.09,10,0
311,Residential Tariffs_ 2026_04_21,Tariff 20-60kl (incl#VAT),object,11,1,9.09,10,0
312,Residential Tariffs_ 2026_04_21,Tariff >60kl (incl#VAT),object,11,1,9.09,10,0

MISSING VALUE AUDIT

In [12]:
missing_columns = column_audit_df[
    column_audit_df["Missing"] > 0
].copy()

print(
    "Columns containing missing values:"
)

display(
    missing_columns
)

Columns containing missing values:

,Dataset,Column,Data Type,Rows,Missing,Missing %,Unique Values,Duplicate Values
0,NIWIS_Water Supply Reliability - population_16...,Unnamed: 0,float64,144,144,100.00,0,143
3,NIWIS_Water Supply Reliability - population_16...,population with access to water,object,144,9,6.25,135,8
6,NIWIS_Water Supply Reliability - population_16...,Urban population,object,144,2,1.39,142,1
7,NIWIS_Water Supply Reliability - population_16...,Urban population with access to water,object,144,2,1.39,142,1
8,NIWIS_Water Supply Reliability - population_16...,Urban population Reliable Supply,object,144,2,1.39,142,1
...,...,...,...,...,...,...,...,...
308,Residential Tariffs_ 2026_04_21,Unnamed: 2,object,11,10,90.91,1,9
309,Residential Tariffs_ 2026_04_21,Tariff 0-6kl (incl#VAT),object,11,1,9.09,8,2
310,Residential Tariffs_ 2026_04_21,Tariff 6-20kl (incl#VAT),object,11,1,9.09,10,0
311,Residential Tariffs_ 2026_04_21,Tariff 20-60kl (incl#VAT),object,11,1,9.09,10,0
312,Residential Tariffs_ 2026_04_21,Tariff >60kl (incl#VAT),object,11,1,9.09,10,0

DUPLICATE AUDIT

In [13]:
duplicate_summary = (
    overview_df[
        [
            "Dataset",
            "Rows",
            "Duplicate Rows"
        ]
    ]
    .sort_values(
        "Duplicate Rows",
        ascending=False
    )
)

display(
    duplicate_summary
)

                                              Dataset   Rows  Duplicate Rows
8                NIWIS_GroundwaterStatus_16-Jul-2026    1947               1
1                     Water demand growth_ 2026_04_21     11               0
0   NIWIS_Water Supply Reliability - population_16...    144               0
2   NIWIS_Access to Water Infrastructure Delivered...      0               0
3                Institutional Compliance_ 2026_04_21     11               0
5   Drinking Water Quality Compliance - SANS 241 _...      4               0
4          Microbiological _ Acute Health_ 2026_04_21     11               0
6                 Surface Water Storage ( 2020 -2026)    375               0
7            Households Served with Water_ 2026_04_21     11               0
9                   Surface Water Storage (2014-2020)    374               0
10               People Served with Water_ 2026_04_21     11               0
11         Areas of Highest Vulnerability_ 2026_04_21     11               0
12    Protests Identified by Municipal IQ_ 2026_04_21     11               0
13                 Verified - River Flow ( National )      7               0
14                                            Weather  21301               0
15                       Total Households_ 2026_04_21     11               0
16                        Potable Systems_ 2026_04_21     61               0
17            Source of Water Households _ 2026_04_21     10               0
18            Vulnerability Score Per leg_ 2026_04_21     11               0
19                       Total Population_ 2026_04_21     11               0
20                  TimeSeries Population_ 2026_04_21     11               0
21                Piped Water Households _ 2026_04_21     10               0
22               NIWIS_WasteWaterQuality_16-Jul-2026     143               0
23                            Operational_ 2026_04_21     11               0
24                             NIWIS_RWT_16-Jul-2026       9               0
25                  Timeseries Households_ 2026_04_21     11               0
26                    Residential Tariffs_ 2026_04_21     11               0

IDENTIFY DATE/TIME VARIABLES

In [14]:
date_columns = []

for name, df in datasets.items():

    for col in df.columns:

        col_lower = str(
            col
        ).lower()

        if (
            "date" in col_lower
            or "time" in col_lower
            or "timestamp" in col_lower
            or "month" in col_lower
            or "year" in col_lower
        ):

            date_columns.append({

                "Dataset": name,

                "Column": col,

                "Data Type": str(
                    df[col].dtype
                ),

                "Example Values":
                    df[col]
                    .dropna()
                    .astype(str)
                    .head(5)
                    .tolist()
            })

date_columns_df = pd.DataFrame(
    date_columns
)

display(
    date_columns_df
)

,Dataset,Column,Data Type,Example Values
0,Water demand growth_ 2026_04_21,Time Frame,object,"[2 018, 2 018, 2 018, 2 018, 2 018]"
1,Institutional Compliance_ 2026_04_21,Time Frame,object,"[April 2022, April 2022, April 2022, April 202..."
2,Microbiological _ Acute Health_ 2026_04_21,Time Frame,object,"[2 026, 2 026, 2 026, 2 026, 2 026]"
3,Surface Water Storage ( 2020 -2026),'DateTime,object,"['2020-10-01 00:00:00, '2020-10-08 00:00:00, '..."
4,Households Served with Water_ 2026_04_21,Time Frame,object,"[April 2026, April 2026, April 2026, April 202..."
5,Surface Water Storage (2014-2020),'DateTime,object,"['2014-10-01 00:00:00, '2014-10-08 00:00:00, '..."
6,People Served with Water_ 2026_04_21,Time Frame,object,"[April 2026, April 2026, April 2026, April 202..."
7,Areas of Highest Vulnerability_ 2026_04_21,Time Frame,object,"[2 018, 2 018, 2 018, 2 018, 2 018]"
8,Protests Identified by Municipal IQ_ 2026_04_21,Time Frame,object,"[2 018, 2 018, 2 018, 2 018, 2 018]"
9,Weather,DATE,object,"[2000-01-01, 2000-01-02, 2000-01-03, 2000-01-0..."
10,Total Households_ 2026_04_21,Time Frame,object,"[April 2026, April 2026, April 2026, April 202..."
11,Potable Systems_ 2026_04_21,Time Frame,object,"[April 2022, April 2022, April 2022, April 202..."
12,Source of Water Households _ 2026_04_21,Time Frame,object,"[Oct 2011, Oct 2011, Oct 2011, Oct 2011, Oct 2..."
13,Vulnerability Score Per leg_ 2026_04_21,Time Frame,object,"[2 018, 2 018, 2 018, 2 018, 2 018]"
14,Total Population_ 2026_04_21,Time Frame,object,"[April 2026, April 2026, April 2026, April 202..."
15,TimeSeries Population_ 2026_04_21,Time Frame,object,"[April 2026, April 2026, April 2026, April 202..."
16,Piped Water Households _ 2026_04_21,Time Frame,object,"[Oct 2011, Oct 2011, Oct 2011, Oct 2011, Oct 2..."
17,Operational_ 2026_04_21,Time Frame,object,"[2 026, 2 026, 2 026, 2 026, 2 026]"
18,NIWIS_RWT_16-Jul-2026,Date,int64,"[2025, 2025, 2025, 2025, 2025]"
19,Timeseries Households_ 2026_04_21,Time Frame,object,"[April 2026, April 2026, April 2026, April 202..."
20,Residential Tariffs_ 2026_04_21,Time Frame,object,"[2 018, 2 018, 2 018, 2 018, 2 018]"

IDENTIFY LOCATION VARIABLES

In [15]:
location_keywords = [
    "region",
    "municipality",
    "province",
    "district",
    "city",
    "location",
    "area"
]

location_columns = []

for name, df in datasets.items():

    for col in df.columns:

        col_lower = str(
            col
        ).lower()

        if any(
            keyword in col_lower
            for keyword in location_keywords
        ):

            location_columns.append({

                "Dataset": name,

                "Column": col,

                "Unique Values": int(
                    df[col].nunique(
                        dropna=True
                    )
                ),

                "Example Values":
                    df[col]
                    .dropna()
                    .astype(str)
                    .unique()[:5]
                    .tolist()
            })

location_columns_df = pd.DataFrame(
    location_columns
)

display(
    location_columns_df
)

,Dataset,Column,Unique Values,Example Values
0,Water demand growth_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
1,Institutional Compliance_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
2,Microbiological _ Acute Health_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
3,Households Served with Water_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
4,People Served with Water_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
5,Areas of Highest Vulnerability_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
6,Areas of Highest Vulnerability_ 2026_04_21,4# Technical Staff Capacity (Numbers),4,"[Low, Extreme, Moderate, High]"
7,Protests Identified by Municipal IQ_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
8,Protests Identified by Municipal IQ_ 2026_04_21,Electricity,8,"[76.0, 29.0, 31.0, 1.0, 2.0]"
9,Total Households_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
10,Potable Systems_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
11,Potable Systems_ 2026_04_21,System area,30,"[Alexandra,East Bank ,Tsutsumani ,Bultfontein ..."
12,Source of Water Households _ 2026_04_21,Region,10,[City of Johannesburg Metropolitan Municipalit...
13,Source of Water Households _ 2026_04_21,Regional/local water scheme (operated by munic...,9,"[1 371 966, 825 746, 972 647, 211 967, 26 377]"
14,Vulnerability Score Per leg_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
15,Vulnerability Score Per leg_ 2026_04_21,4# Technical Staff Capacity (Numbers),8,"[79.0, 20.0, 80.0, 15.0, 69.0]"
16,Total Population_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
17,TimeSeries Population_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
18,Piped Water Households _ 2026_04_21,Region,10,[City of Johannesburg Metropolitan Municipalit...
19,Operational_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
20,Timeseries Households_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...
21,Residential Tariffs_ 2026_04_21,Region,11,[City of Johannesburg Metropolitan Municipalit...

NUMERICAL VARIABLE AUDIT

In [16]:
numeric_summary = []

for name, df in datasets.items():

    numeric_cols = df.select_dtypes(
        include=np.number
    ).columns

    for col in numeric_cols:

        numeric_summary.append({

            "Dataset": name,

            "Column": col,

            "Minimum": df[col].min(),

            "Maximum": df[col].max(),

            "Mean": df[col].mean(),

            "Median": df[col].median(),

            "Std": df[col].std(),

            "Missing": int(
                df[col].isnull().sum()
            )
        })

numeric_summary_df = pd.DataFrame(
    numeric_summary
)

display(
    numeric_summary_df
)

,Dataset,Column,Minimum,Maximum,Mean,Median,Std,Missing
0,NIWIS_Water Supply Reliability - population_16...,Unnamed: 0,NaN,NaN,NaN,NaN,NaN,144
1,Water demand growth_ 2026_04_21,% Water Demand Growth,-10.13,8.90,0.651000,0.575,4.909982,1
2,Water demand growth_ 2026_04_21,% Non-Revenue Water,23.00,48.80,33.889000,35.020,7.591215,1
3,Water demand growth_ 2026_04_21,% Water Losses,23.00,48.80,31.864000,30.250,7.504036,1
4,Institutional Compliance_ 2026_04_21,Potable Water Compliance Percentage,62.20,103.51,93.051000,99.540,14.545463,1
...,...,...,...,...,...,...,...,...
65,Operational_ 2026_04_21,Compliance Percentage,0.00,99.19,76.927000,96.990,40.711937,1
66,NIWIS_RWT_16-Jul-2026,Date,2025.00,2025.00,2025.000000,2025.000,0.000000,0
67,NIWIS_RWT_16-Jul-2026,Domestic and Industry c/m3,1.98,6.59,4.581111,4.780,1.488367,0
68,NIWIS_RWT_16-Jul-2026,Irrigation c/m3,1.15,3.84,2.981111,3.220,0.827880,0
69,NIWIS_RWT_16-Jul-2026,Forestry c/m3,0.00,3.18,2.358889,2.640,1.010105,0

OUTLIER AUDIT USING IQR

In [17]:
outlier_summary = []

for name, df in datasets.items():

    numeric_cols = df.select_dtypes(
        include=np.number
    ).columns

    for col in numeric_cols:

        series = df[col].dropna()

        if len(series) < 4:
            continue

        Q1 = series.quantile(0.25)

        Q3 = series.quantile(0.75)

        IQR = Q3 - Q1

        lower_bound = (
            Q1 - 1.5 * IQR
        )

        upper_bound = (
            Q3 + 1.5 * IQR
        )

        outliers = (
            (series < lower_bound)
            |
            (series > upper_bound)
        )

        outlier_summary.append({

            "Dataset": name,

            "Column": col,

            "Q1": Q1,

            "Q3": Q3,

            "IQR": IQR,

            "Lower Bound":
                lower_bound,

            "Upper Bound":
                upper_bound,

            "Outlier Count":
                int(outliers.sum()),

            "Outlier %": round(
                outliers.mean() * 100,
                2
            )
        })

outlier_df = pd.DataFrame(
    outlier_summary
)

display(
    outlier_df.sort_values(
        "Outlier Count",
        ascending=False
    )
)

,Dataset,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count,Outlier %
45,Weather,PRCP,0.000000,4.300000,4.300000,-6.450000,10.750000,1028,12.82
47,Weather,TMAX,22.000000,28.700000,6.700000,11.950000,38.750000,49,0.25
46,Weather,TAVG,14.300000,20.900000,6.600000,4.400000,30.800000,40,0.19
15,Surface Water Storage ( 2020 -2026),'2025/2026,84.365152,94.346891,9.981739,69.392543,109.319499,14,4.64
50,Potable Systems_ 2026_04_21,Drinking Water Quality Percentage,98.390000,100.000000,1.610000,95.975000,102.415000,8,13.33
...,...,...,...,...,...,...,...,...,...
56,Vulnerability Score Per leg_ 2026_04_21,7# Drinking Water Safety & Regulatory Compliance,65.000000,93.500000,28.500000,22.250000,136.250000,0,0.00
60,Piped Water Households _ 2026_04_21,Unspecified,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.00
61,Piped Water Households _ 2026_04_21,Not applicable,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.00
65,NIWIS_RWT_16-Jul-2026,Domestic and Industry c/m3,3.560000,5.480000,1.920000,0.680000,8.360000,0,0.00
64,NIWIS_RWT_16-Jul-2026,Date,2025.000000,2025.000000,0.000000,2025.000000,2025.000000,0,0.00

MASTER AUDIT REPORT

In [18]:
audit_report = overview_df.copy()

audit_report["Missing %"] = (
    audit_report["Missing Values"]
    / audit_report["Rows"]
    * 100
).round(2)

audit_report["Duplicate %"] = (
    audit_report["Duplicate Rows"]
    / audit_report["Rows"]
    * 100
).round(2)

display(
    audit_report
)

,Dataset,Rows,Columns,Memory (MB),Missing Values,Duplicate Rows,Numeric Columns,Categorical Columns,Missing %,Duplicate %
0,NIWIS_Water Supply Reliability - population_16...,144,14,0.10,189,0,1,13,131.25,0.00
1,Water demand growth_ 2026_04_21,11,10,0.01,18,0,3,7,163.64,0.00
2,NIWIS_Access to Water Infrastructure Delivered...,0,4,0.00,0,0,0,4,NaN,NaN
3,Institutional Compliance_ 2026_04_21,11,5,0.00,13,0,2,3,118.18,0.00
4,Microbiological _ Acute Health_ 2026_04_21,11,8,0.00,16,0,2,6,145.45,0.00
5,Drinking Water Quality Compliance - SANS 241 _...,4,2,0.00,0,0,1,1,0.00,0.00
6,Surface Water Storage ( 2020 -2026),375,9,0.05,1953,0,8,1,520.80,0.00
7,Households Served with Water_ 2026_04_21,11,17,0.01,25,0,2,15,227.27,0.00
8,NIWIS_GroundwaterStatus_16-Jul-2026,1947,8,0.69,2511,1,1,7,128.97,0.05
9,Surface Water Storage (2014-2020),374,9,0.05,1971,0,8,1,527.01,0.00
10,People Served with Water_ 2026_04_21,11,17,0.01,25,0,1,16,227.27,0.00
11,Areas of Highest Vulnerability_ 2026_04_21,11,21,0.01,29,0,0,21,263.64,0.00
12,Protests Identified by Municipal IQ_ 2026_04_21,11,16,0.00,24,0,13,3,218.18,0.00
13,Verified - River Flow ( National ),7,2,0.00,0,0,1,1,0.00,0.00
14,Weather,21301,14,8.86,38846,0,7,7,182.37,0.00
15,Total Households_ 2026_04_21,11,8,0.01,16,0,1,7,145.45,0.00
16,Potable Systems_ 2026_04_21,61,11,0.04,69,0,2,9,113.11,0.00
17,Source of Water Households _ 2026_04_21,10,13,0.01,20,0,1,12,200.00,0.00
18,Vulnerability Score Per leg_ 2026_04_21,11,9,0.00,17,0,6,3,154.55,0.00
19,Total Population_ 2026_04_21,11,8,0.01,16,0,1,7,145.45,0.00
20,TimeSeries Population_ 2026_04_21,11,35,0.03,43,0,0,35,390.91,0.00
21,Piped Water Households _ 2026_04_21,10,12,0.01,19,0,2,10,190.00,0.00
22,NIWIS_WasteWaterQuality_16-Jul-2026,143,6,0.04,143,0,1,5,100.00,0.00
23,Operational_ 2026_04_21,11,8,0.00,16,0,2,6,145.45,0.00
24,NIWIS_RWT_16-Jul-2026,9,5,0.00,0,0,4,1,0.00,0.00
25,Timeseries Households_ 2026_04_21,11,35,0.03,43,0,0,35,390.91,0.00
26,Residential Tariffs_ 2026_04_21,11,7,0.00,15,0,0,7,136.36,0.00

SAVE AUDIT RESULTS

In [19]:
audit_dir = "Outputs/DataAudit"

os.makedirs(
    audit_dir,
    exist_ok=True
)

overview_df.to_csv(
    os.path.join(
        audit_dir,
        "dataset_overview.csv"
    ),
    index=False
)

column_audit_df.to_csv(
    os.path.join(
        audit_dir,
        "column_audit.csv"
    ),
    index=False
)

missing_columns.to_csv(
    os.path.join(
        audit_dir,
        "missing_columns.csv"
    ),
    index=False
)

duplicate_summary.to_csv(
    os.path.join(
        audit_dir,
        "duplicate_summary.csv"
    ),
    index=False
)

numeric_summary_df.to_csv(
    os.path.join(
        audit_dir,
        "numeric_summary.csv"
    ),
    index=False
)

outlier_df.to_csv(
    os.path.join(
        audit_dir,
        "outlier_summary.csv"
    ),
    index=False
)

audit_report.to_csv(
    os.path.join(
        audit_dir,
        "master_audit_report.csv"
    ),
    index=False
)

print(
    "All audit reports saved successfully."
)

print(
    f"Location: {audit_dir}"
)

All audit reports saved successfully.
Location: Outputs/DataAudit